---
title: "Marco de Sendai"
format: html
editor: visual
---

## Marco de Sendai para la Reducción del Riesgo de Desastres 2015-2030

El Marco de Sendai para la Reducción del Riesgo de Desastres 2015-2030 es el instrumento internacional vigente que orienta la acción mundial en gestión del riesgo de desastres. Fue acordado en la Tercera Conferencia Mundial de las Naciones Unidas sobre Reducción del Riesgo de Desastres, celebrada en Sendai, Japón, en marzo de 2015, y respaldado por la Asamblea General de las Naciones Unidas en junio del mismo año. Sucede al Marco de Acción de Hyogo 2005-2015 y establece siete metas globales, cuatro prioridades de acción y trece principios rectores orientados a prevenir nuevos riesgos, reducir los existentes y fortalecer la resiliencia.

# Implementación del Marco de Sendai

<iframe width="800" height="600" src="https://app.powerbi.com/view?r=eyJrIjoiZTIxYWVkMzktODRhYS00ZWFmLTljYWYtMTEzMzE3ZjA5ODQxIiwidCI6IjBmOWUzNWRiLTU0NGYtNGY2MC1iZGNjLTVlYTQxNmU2ZGM3MCIsImMiOjh9&pageName=31bb51f734eacbb9cda1" frameborder="0" allowFullScreen="true">

</iframe>

# Enlaces de interés

- [Sendai Framework Monitor – Home page](https://sendaimonitor.undrr.org/)
- [Science Technology Commitment to support implementation of Sendai Framework](https://sendaicommitments.undrr.org/commitment/science-technology-commitment-support-implementation-sendai-framework)
- [F-5: Number of international, regional and bilateral programmes and initiatives for the transfer and exchange of science, technology and innovation in disaster risk reduction for developing countries](https://sendaicommitments.undrr.org/sendai-targets-indicators/target-f-substantially-enhance-international-cooperation-developing-4)
- [Sendai Voluntary Commitments (SFVC) – Home page](https://sendaicommitments.undrr.org/)
