---
title: "Myst, Zaar"
format: html
editor: visual
---

# Myst

-   Mi proyecto paralelo de Myst
-   Myst. [*Link*](https://mystmd.org/guide).
    -   Get Started. Your first steps with MyST. [*Link*](https://mystmd.org/guide/quickstart)

::: {.callout-tip appearance="minimal"}
## Como instalar Myst

Revise el tutorial por extenso aquí: [*link*](https://mystmd.org/guide/quickstart)

-   Instale Python, MyST Markdown CLI, y VS-Code

-   Revise en consola si Myst se instaló correctamente: `myst -v`

-   Descargue el contenido de ejemplo y navegue hasta la carpeta

    -   `git clone https://github.com/jupyter-book/mystmd-quickstart.git`
    -   `cd mystmd-quickstart`
    -   \`myst\` aparecera este mensaje " 💾 Writing new project and site config file: myst.yml — ? Would you like to run myst start now? (Y/n)"
    -   Luego podrá abrir el nuevo proyecto en su navegador.
:::

::: {.callout-tip appearance="minimal"}
## Como configurar Myst

-   Debe existir al meno un archivo en el proyecto ¨El archivo index.md servirá como página principal del sitio.¨
-   `myst start` para ver el sitio web localmente
-   Agregar contenido: Crear más archivos .md o notebooks .ipynb
-   Configurar: Editar `myst.yml` para personalizar título, descripción, etc. 4. Estructura: Crear subcarpetas y organizar tu contenido
-   Estructura: Crear subcarpetas y organizar tu contenido
:::

::: callout-note
## Comando rapidos

`myst start` Preview en navegador `myst build --html` Build estático (para generar HTML)
:::

{{< video "https://youtu.be/YGzBF-2wAWU" width = "400" >}} SciPy Proceedings 2025. MyST Markdown and Curvenote

{{< video "https://youtu.be/gGPizw_URxM" width = "400" >}} Rowan Cockett- SciPy Proceedings: An Exemplar for Publishing Computational Open Science \| SciPy 2025

## Myst en publicacion científica

-   AGU Notebooks. La Palma Seismicity 2021. [*Link*](https://notebooks-now.github.io/submission-myst-full/)

## Lecturas

-   Reflections on MyST-ification. 2025. [*Link*](https://projectpythia.org/posts/2025/mystification/)
-   AGU. About Notebooks Now!. [*Link*](https://data.agu.org/notebooks-now/about)*.*

## Zaar

## Lecturas

-   Zarr in the Browser — Fast, Flexible, and Surprisingly Powerful for Big Geo Data. 2025. [*Link.*](https://medium.com/@tobias.ramalho.ferreira/zarr-in-the-browser-fast-flexible-and-surprisingly-powerful-for-big-geo-data-eeb90ddf8a3d)