---
title: "Atajos para Quarto"
format: html
editor: visual
---

# Insertar videos

``` {.Markdown style="color: gray"}
Insertar video en dos columnas

::: {layout-ncol=2} 
{{< video "https://youtu.be/BY32QADSuNM" >}}
{{< video "https://youtu.be/BY32QADSuNM" >}}
Texto de la caja (opcional)
:::
```

``` {.Markdown style="color: gray"}
Insertar video de un live: cambiar "live" por "embed"
https://www.youtube.com/embed/srgbUPu9Mo4
```

# [Callout blocks](https://quarto.org/docs/authoring/callouts.html)

There are five different types of callouts available: `note` , `warning,` `important` , `tip` , `caution` . The color and icon will be different depending upon the type that you select. Here are what the various types look like in HTML output.

``` {.Markdown style="color: gray;"}
{.callout-note collapse="true"} Note that there are five types of callouts, including: `note` , `warning,` `important` , `tip` , `caution`. 
```

::: callout-note
Note that there are five types of callouts, including: `note`, `tip`, `warning`, `caution`, and `important`.
:::

::: callout-warning
Callouts provide a simple way to attract attention, for example, to this warning.
:::

::: callout-important
## This is Important

Danger, callouts will really improve your writing.
:::

::: callout-tip
## Tip With Title

This is an example of a callout with a title.
:::

::: {.callout-caution collapse="true"}
## Expand To Learn About Collapse

This is an example of a 'collapsed' caution callout that can be expanded by the user. You can use `collapse="true"` to collapse it by default or `collapse="false"` to make a collapsible callout that is expanded by default.
:::

::: {.callout-caution collapse="true" style="color: purple" appearance="minimal"}
## Expand To Learn About Collapse \[with minimal atribute\]

This is an example of a 'collapsed' caution callout that can be expanded by the user and minimal atributes with `{.callout-caution collapse="true" style="color: purple" appearance="minimal"}`
:::

# Texto desplegable

<details>

<summary>Texto desplegable</summary>

``` {.markdown style="color: gray"}
<details> <summary>Título del texto desplegable</summary>
-   Contenido
-   Contenido
-   Contenido
</details> 
```

</details>