---
title: "Migración humana"
format: html
editor: visual
---

"En 2024, más personas vivían fuera de sus países de origen que en cualquier otro momento de la historia moderna, [según las Naciones Unidas](#0) . Es un cambio radical que transformará la política, la economía y las sociedades civiles durante generaciones."

# Lecturas

-   Measuring Global Migration Flows using Online Data. PNAS. 2025. [*Link*](https://www.pnas.org/doi/10.1073/pnas.2409418122)
-   To Understand Global Migration, You Have to See It First. NYT. 2025. [*Link*](https://www.nytimes.com/interactive/2025/04/17/opinion/global-migration-facebook-data.html)
-   Facebook data used to study global human migration patterns. 2025. [Link](https://phys.org/news/2025-05-facebook-global-human-migration-patterns.html)

![Estimated international migration flows in 2022, in millions of people. (A) International migration flows between and within regions in 2022. Lines measure aggregate flows between all country pairs in each region. (B) Top and bottom five countries by annual net migration in 2022. Orange bars depict countries with net emigration; blue bars depict those with net immigration. (C) Top five countries by annual gross migration inflows in 2022. (D) Top five countries by annual gross migration outflows in 2022. (E) Top five (directed) country pairs for annual migration in 2022. PNAS. 2025. [*Link*](https://www.pnas.org/doi/10.1073/pnas.2409418122)](https://www.pnas.org/cms/10.1073/pnas.2409418122/asset/6de69522-f829-4efe-b635-322106ed2386/assets/images/large/pnas.2409418122fig02.jpg){alt="Estimated international migration flows in 2022, in millions of people. (A) International migration flows between and within regions in 2022. Lines measure aggregate flows between all country pairs in each region. (B) Top and bottom five countries by annual net migration in 2022. Orange bars depict countries with net emigration; blue bars depict those with net immigration. (C) Top five countries by annual gross migration inflows in 2022. (D) Top five countries by annual gross migration outflows in 2022. (E) Top five (directed) country pairs for annual migration in 2022."}