{
  "hash": "44bbdc0db1df80f7144110b6b6e9a917",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Modelos mixtos y medidas repetidas\"\nsubtitle: \"Minicurso de R · Módulo 6\"\ndescription: \"Por qué ignorar la dependencia entre observaciones es un error, cómo modelarla con efectos aleatorios (lme4 y nlme) y cómo interpretar los resultados en diseños de medidas repetidas.\"\nauthor: \"Mauricio Romero\"\ndate: 2026-09-25\nformat: html\neditor: visual\ncategories: [R, modelos mixtos, lme4, nlme, medidas repetidas]\n---\n\n::: {.callout-note appearance=\"minimal\"}\n**Duración estimada:** 4 horas · **Nivel:** avanzado · **Prerrequisitos:** Módulo 5 (regresión y ANOVA).\n:::\n\n## Objetivos de aprendizaje\n\nAl terminar este cuaderno podrás:\n\n1. Reconocer cuándo las observaciones **no son independientes** (medidas repetidas, sitios, parcelas) y por qué eso invalida un `lm()` ordinario.\n2. Distinguir **efectos fijos** de **efectos aleatorios**.\n3. Ajustar modelos con **intercepto aleatorio** y con **pendiente aleatoria** usando `lme4`.\n4. Interpretar los **componentes de varianza** y la correlación intraclase (ICC).\n5. Comparar modelos y diagnosticar los supuestos.\n6. Explicar la relación entre un modelo mixto, el ANOVA de medidas repetidas y la prueba t pareada.\n7. Ajustar un modelo **no lineal mixto** con `nlme`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(lme4)        # lmer(): modelos mixtos\nlibrary(lmerTest)    # valores p para lmer\nlibrary(nlme)        # lme() y nlme(): estructuras de correlación y modelos no lineales\nlibrary(performance) # ICC y diagnósticos\nset.seed(2026)\n\ntheme_set(theme_minimal(base_size = 12) + theme(panel.grid.minor = element_blank()))\n```\n:::\n\n\n## 1. El problema: observaciones que no son independientes\n\nLos modelos del Módulo 5 suponen que cada fila es **independiente** de las demás. Esto se rompe cuando:\n\n- se mide **al mismo individuo** varias veces (medidas repetidas, series por sujeto);\n- las observaciones vienen de **grupos** (estudiantes en colegios, parcelas en una misma finca, sitios en un mismo arrecife);\n- hay una estructura jerárquica o espacial.\n\nObservaciones del mismo grupo se parecen entre sí más que a las de otro grupo. Si se ignora esa **correlación**, el modelo cree que tiene más información independiente de la que realmente hay (**pseudoreplicación**), los errores estándar se subestiman y los valores p resultan demasiado optimistas (Hurlbert, 1984).\n\n### Efectos fijos y aleatorios\n\nUn **modelo mixto** combina dos tipos de efectos:\n\n| | Efectos fijos | Efectos aleatorios |\n|---|---|---|\n| Qué son | Los niveles que **interesan en sí mismos** (tratamiento, tiempo) | Niveles **muestreados de una población** de grupos (sujetos, sitios) |\n| Qué se estima | Un coeficiente por nivel o pendiente | Una **varianza** entre grupos |\n| Ejemplo | `Days` (días de privación de sueño) | `Subject` (los 18 voluntarios) |\n\nPara un modelo con intercepto y pendiente aleatorios por sujeto $j$:\n\n$$\ny_{ij} = (\\beta_0 + b_{0j}) + (\\beta_1 + b_{1j})\\, x_{ij} + \\varepsilon_{ij}, \\qquad\n\\begin{pmatrix} b_{0j} \\\\ b_{1j} \\end{pmatrix} \\sim N(\\mathbf{0}, \\Sigma), \\quad \\varepsilon_{ij} \\sim N(0, \\sigma^2)\n$$\n\nLos $\\beta$ son los efectos fijos (el promedio de la población). Los $b_j$ son las **desviaciones de cada sujeto** respecto a ese promedio.\n\n## 2. Los datos: privación de sueño\n\n`sleepstudy` reúne el tiempo de reacción medio (en ms) de 18 conductores de camión durante 10 días en que solo durmieron 3 horas por noche (Belenky et al., 2003).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(sleepstudy)\nas_tibble(sleepstudy)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 180 × 3\n   Reaction  Days Subject\n      <dbl> <dbl> <fct>  \n 1     250.     0 308    \n 2     259.     1 308    \n 3     251.     2 308    \n 4     321.     3 308    \n 5     357.     4 308    \n 6     415.     5 308    \n 7     382.     6 308    \n 8     290.     7 308    \n 9     431.     8 308    \n10     466.     9 308    \n# ℹ 170 more rows\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(sleepstudy, aes(Days, Reaction, group = Subject)) +\n  geom_line(colour = \"grey60\") +\n  geom_smooth(aes(group = 1), method = \"lm\", colour = \"#e76f51\", linewidth = 1.2, se = FALSE) +\n  scale_x_continuous(breaks = 0:9) +\n  labs(x = \"Días de privación de sueño\", y = \"Tiempo de reacción (ms)\")\n```\n\n::: {.cell-output-display}\n![Tiempo de reacción de cada sujeto (líneas grises) y tendencia promedio (línea roja). Los sujetos difieren en el nivel inicial y en la velocidad con que se deterioran.](06-modelos-mixtos_files/figure-html/fig-espagueti-1.png){#fig-espagueti width=1050}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(sleepstudy, aes(Days, Reaction)) +\n  geom_point(size = 1) +\n  geom_smooth(method = \"lm\", se = FALSE, colour = \"#264653\", linewidth = 0.6) +\n  facet_wrap(~ Subject, nrow = 3) +\n  scale_x_continuous(breaks = c(0, 3, 6, 9)) +\n  labs(x = \"Días\", y = \"Reacción (ms)\")\n```\n\n::: {.cell-output-display}\n![Regresión por sujeto. Las pendientes e interceptos varían mucho: es justo la variación que un modelo con efectos aleatorios busca capturar.](06-modelos-mixtos_files/figure-html/fig-por-sujeto-1.png){#fig-por-sujeto width=1050}\n:::\n:::\n\n\n## 3. Ignorar la dependencia: ¿cuánto importa?\n\nComparemos tres modelos para el efecto de los días:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_lm  <- lm(Reaction ~ Days, data = sleepstudy)                      # ignora los sujetos\nm_int <- lmer(Reaction ~ Days + (1 | Subject), data = sleepstudy)    # intercepto aleatorio\nm_pen <- lmer(Reaction ~ Days + (Days | Subject), data = sleepstudy) # intercepto y pendiente aleatorios\n\ntibble(modelo = c(\"lm (ignora sujetos)\", \"Intercepto aleatorio\", \"Intercepto + pendiente aleatorios\"),\n       pendiente = c(coef(m_lm)[\"Days\"], fixef(m_int)[\"Days\"], fixef(m_pen)[\"Days\"]),\n       error_est = c(summary(m_lm)$coefficients[\"Days\", 2],\n                     summary(m_int)$coefficients[\"Days\", 2],\n                     summary(m_pen)$coefficients[\"Days\", 2])) |>\n  knitr::kable(digits = 2)\n```\n\n::: {.cell-output-display}\n\n\n|modelo                            | pendiente| error_est|\n|:---------------------------------|---------:|---------:|\n|lm (ignora sujetos)               |     10.47|      1.24|\n|Intercepto aleatorio              |     10.47|      0.80|\n|Intercepto + pendiente aleatorios |     10.47|      1.55|\n\n\n:::\n:::\n\n\nLa pendiente estimada es la misma en los tres modelos, pero su **error estándar** cambia bastante: 1,24 con `lm`, 0,80 con intercepto aleatorio y 1,55 con pendiente aleatoria. Hay dos lecciones:\n\n- El `lm` trata las 180 mediciones como independientes, cuando en realidad son 10 mediciones de cada uno de 18 personas. Su error (1,24) queda por debajo del real (1,55).\n- El modelo con **solo intercepto aleatorio** es el más optimista (0,80). Supone que todos los sujetos se deterioran a la **misma velocidad** y solo difieren en el nivel de partida. Como en los datos la velocidad sí varía, ese modelo subestima la incertidumbre sobre el efecto promedio. Omitir un efecto aleatorio que existe en los datos produce intervalos demasiado angostos (Barr et al., 2013).\n\n## 4. Modelo con intercepto aleatorio\n\nLa sintaxis de `lmer()` agrega los efectos aleatorios entre paréntesis: `(efecto | grupo)`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(m_int)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: Reaction ~ Days + (1 | Subject)\n   Data: sleepstudy\n\nREML criterion at convergence: 1786.5\n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-3.2257 -0.5529  0.0109  0.5188  4.2506 \n\nRandom effects:\n Groups   Name        Variance Std.Dev.\n Subject  (Intercept) 1378.2   37.12   \n Residual              960.5   30.99   \nNumber of obs: 180, groups:  Subject, 18\n\nFixed effects:\n            Estimate Std. Error       df t value Pr(>|t|)    \n(Intercept) 251.4051     9.7467  22.8102   25.79   <2e-16 ***\nDays         10.4673     0.8042 161.0000   13.02   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n     (Intr)\nDays -0.371\n```\n\n\n:::\n:::\n\n\nSe lee así:\n\n- **Efectos fijos**: cada día adicional sin dormir aumenta el tiempo de reacción en unos 10 ms (IC 95 % más abajo).\n- **Efectos aleatorios**: la varianza entre sujetos en el intercepto (`Subject (Intercept)`) y la varianza residual (dentro de sujetos).\n\n### Correlación intraclase (ICC)\n\nEl ICC es la proporción de la varianza total que se debe a **diferencias entre grupos**:\n\n$$\nICC = \\frac{\\sigma^2_{sujeto}}{\\sigma^2_{sujeto} + \\sigma^2_{residual}}\n$$\n\nUn ICC alto indica que las observaciones del mismo grupo se parecen mucho y que ignorar la estructura sería grave.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nicc(m_int)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Intraclass Correlation Coefficient\n\n    Adjusted ICC: 0.589\n  Unadjusted ICC: 0.424\n```\n\n\n:::\n\n```{.r .cell-code}\nconfint(m_int, parm = \"Days\", method = \"Wald\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        2.5 %   97.5 %\nDays 8.891041 12.04353\n```\n\n\n:::\n:::\n\n\n## 5. Modelo con pendiente aleatoria\n\nComo los sujetos no solo difieren en el nivel de partida sino también en **cuánto se deterioran**, permitimos que la pendiente varíe:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(m_pen)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: Reaction ~ Days + (Days | Subject)\n   Data: sleepstudy\n\nREML criterion at convergence: 1743.6\n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-3.9536 -0.4634  0.0231  0.4634  5.1793 \n\nRandom effects:\n Groups   Name        Variance Std.Dev. Corr \n Subject  (Intercept) 612.10   24.741        \n          Days         35.07    5.922   0.07 \n Residual             654.94   25.592        \nNumber of obs: 180, groups:  Subject, 18\n\nFixed effects:\n            Estimate Std. Error      df t value Pr(>|t|)    \n(Intercept)  251.405      6.825  17.000  36.838  < 2e-16 ***\nDays          10.467      1.546  17.000   6.771 3.26e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n     (Intr)\nDays -0.138\n```\n\n\n:::\n\n```{.r .cell-code}\nVarCorr(m_pen)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Groups   Name        Std.Dev. Corr  \n Subject  (Intercept) 24.7407        \n          Days         5.9221  0.066 \n Residual             25.5918        \n```\n\n\n:::\n:::\n\n\n`VarCorr()` muestra la desviación estándar del intercepto (≈ 25 ms) y de la pendiente (≈ 6 ms/día), y su correlación. Una correlación cercana a cero indica que el nivel inicial no predice la velocidad del deterioro.\n\n### ¿Cuál modelo es mejor?\n\nPara comparar modelos **anidados que difieren en efectos aleatorios**, se ajustan por máxima verosimilitud restringida (REML, por defecto) y se comparan con una prueba de razón de verosimilitudes. Con `anova()` sobre los modelos, `lmerTest` los reajusta automáticamente cuando hace falta:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(m_int, m_pen, refit = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nData: sleepstudy\nModels:\nm_int: Reaction ~ Days + (1 | Subject)\nm_pen: Reaction ~ Days + (Days | Subject)\n      npar    AIC    BIC  logLik -2*log(L)  Chisq Df Pr(>Chisq)    \nm_int    4 1794.5 1807.2 -893.23    1786.5                         \nm_pen    6 1755.6 1774.8 -871.81    1743.6 42.837  2   4.99e-10 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nAIC(m_int, m_pen)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      df      AIC\nm_int  4 1794.465\nm_pen  6 1755.628\n```\n\n\n:::\n:::\n\n\nEl modelo con pendiente aleatoria ajusta mucho mejor, y como consecuencia, los intervalos de confianza para el efecto de los días son más realistas.\n\n### Efectos aleatorios: ¿cómo se desvía cada sujeto?\n\nLos **BLUPs** (*best linear unbiased predictors*) son las desviaciones estimadas de cada sujeto respecto al promedio. Se pueden ver como un gráfico tipo \"oruga\":\n\n\n::: {.cell}\n\n```{.r .cell-code}\nre <- ranef(m_pen)$Subject |>\n  as_tibble(rownames = \"Subject\") |>\n  rename(Intercepto = `(Intercept)`, Pendiente = Days) |>\n  pivot_longer(-Subject, names_to = \"efecto\", values_to = \"desviacion\") |>\n  group_by(efecto) |>\n  mutate(Subject = fct_reorder(Subject, desviacion)) |>\n  ungroup()\n\nggplot(re, aes(desviacion, Subject)) +\n  geom_vline(xintercept = 0, linetype = 2, colour = \"#e76f51\") +\n  geom_point(colour = \"#264653\") +\n  facet_wrap(~ efecto, scales = \"free\") +\n  labs(x = \"Desviación respecto al promedio\", y = NULL)\n```\n\n::: {.cell-output-display}\n![Desviaciones estimadas de cada sujeto (BLUPs) respecto al intercepto (izquierda) y a la pendiente (derecha) promedios. Los sujetos 309 y 337 son los extremos en el intercepto, y el 335 y el 308 en la pendiente.](06-modelos-mixtos_files/figure-html/fig-blups-1.png){#fig-blups width=1050}\n:::\n:::\n\n\n### Predicciones por sujeto: el efecto de \"encogimiento\"\n\nLos modelos mixtos **suavizan** las estimaciones de cada sujeto hacia el promedio poblacional, en especial cuando hay pocos datos (*shrinkage*). Compara la regresión por separado con la que ofrece el modelo mixto:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsleepstudy$pred_mixto <- predict(m_pen)\nsleepstudy$pred_pob   <- predict(m_pen, re.form = NA)   # solo efectos fijos\n\nggplot(sleepstudy, aes(Days)) +\n  geom_point(aes(y = Reaction), size = 0.8) +\n  geom_smooth(aes(y = Reaction), method = \"lm\", se = FALSE, colour = \"grey60\", linewidth = 0.5) +\n  geom_line(aes(y = pred_mixto), colour = \"#e76f51\") +\n  geom_line(aes(y = pred_pob), colour = \"black\", linetype = 2) +\n  facet_wrap(~ Subject, nrow = 3) +\n  scale_x_continuous(breaks = c(0, 3, 6, 9)) +\n  labs(x = \"Días\", y = \"Reacción (ms)\")\n```\n\n::: {.cell-output-display}\n![Rectas individuales ajustadas por separado (gris) frente a las predicciones del modelo mixto (rojo) y al efecto fijo promedio (negro). El modelo mixto acerca las rectas extremas al promedio y es más estable.](06-modelos-mixtos_files/figure-html/fig-encogimiento-1.png){#fig-encogimiento width=1050}\n:::\n:::\n\n\n## 6. Diagnóstico\n\nSe revisan los residuos y también los efectos aleatorios, porque se supone que ambos son normales:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(patchwork)\nd <- tibble(aj = fitted(m_pen), res = resid(m_pen))\nre_int <- ranef(m_pen)$Subject[[\"(Intercept)\"]]\n\n(ggplot(d, aes(aj, res)) + geom_point(alpha = 0.5) + geom_hline(yintercept = 0, colour = \"#e76f51\") +\n   labs(x = \"Ajustados\", y = \"Residuos\")) |\n(ggplot(d, aes(sample = res)) + stat_qq(alpha = 0.5) + stat_qq_line(colour = \"#e76f51\") +\n   labs(x = \"Teóricos\", y = \"Residuos\")) |\n(ggplot(tibble(re_int), aes(sample = re_int)) + stat_qq() + stat_qq_line(colour = \"#e76f51\") +\n   labs(x = \"Teóricos\", y = \"Interceptos aleatorios\"))\n```\n\n::: {.cell-output-display}\n![Diagnóstico del modelo mixto. Izquierda: residuos frente a ajustados. Centro: Q-Q de los residuos. Derecha: Q-Q de los interceptos aleatorios.](06-modelos-mixtos_files/figure-html/fig-diag-mixto-1.png){#fig-diag-mixto width=1500}\n:::\n:::\n\n\n::: {.callout-tip}\n## Consejo\nCon pocos grupos (menos de unos 5 a 6) es difícil estimar una varianza entre grupos. En ese caso conviene usar el grupo como efecto **fijo**. También, si aparece el aviso `singular fit`, el modelo es más complejo de lo que los datos permiten: simplifica los efectos aleatorios.\n:::\n\n## 7. Medidas repetidas: relación con la prueba t pareada y el ANOVA\n\nCuando solo hay **dos momentos**, un modelo con intercepto aleatorio por sujeto es **equivalente** a la prueba t pareada. Lo comprobamos con los días 0 y 9:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndos <- sleepstudy |> filter(Days %in% c(0, 9))\nancho <- dos |> select(Subject, Days, Reaction) |> pivot_wider(names_from = Days, values_from = Reaction, names_prefix = \"d\")\n\nt.test(ancho$d9, ancho$d0, paired = TRUE)$p.value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.311418e-06\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(lmer(Reaction ~ factor(Days) + (1 | Subject), data = dos))$coefficients[\"factor(Days)9\", ]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Estimate   Std. Error           df      t value     Pr(>|t|) \n9.419942e+01 1.353899e+01 1.700000e+01 6.957640e+00 2.311418e-06 \n```\n\n\n:::\n:::\n\n\nEl valor p es **idéntico**. La ventaja del modelo mixto es que se generaliza a más de dos momentos, admite **datos desbalanceados** (sujetos con mediciones faltantes, algo que el ANOVA clásico de medidas repetidas no tolera) y permite covariables continuas.\n\n## 8. Estructuras de correlación con `nlme`\n\n`nlme::lme()` es el paquete clásico y permite especificar **estructuras de correlación** entre las mediciones del mismo sujeto, útil con series temporales. Por ejemplo, un proceso autorregresivo de orden 1 (AR1), donde mediciones consecutivas se parecen más que las lejanas:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_ar1 <- lme(Reaction ~ Days, random = ~ 1 | Subject,\n             correlation = corAR1(form = ~ Days | Subject), data = sleepstudy)\nsummary(m_ar1)$tTable\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                Value Std.Error  DF   t-value      p-value\n(Intercept) 252.84144  10.94093 161 23.109688 5.261088e-53\nDays         10.46687   1.34408 161  7.787388 7.884026e-13\n```\n\n\n:::\n\n```{.r .cell-code}\nm_sin <- lme(Reaction ~ Days, random = ~ 1 | Subject, data = sleepstudy)\nanova(m_sin, m_ar1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      Model df      AIC      BIC    logLik   Test  L.Ratio p-value\nm_sin     1  4 1794.465 1807.192 -893.2325                        \nm_ar1     2  5 1746.191 1762.100 -868.0955 1 vs 2 50.27402  <.0001\n```\n\n\n:::\n:::\n\n\nLa estructura AR1 mejora claramente el ajuste (AIC de 1794 a 1746): las mediciones de días consecutivos de un mismo sujeto se parecen más entre sí que las de días lejanos, más allá de que sea el mismo sujeto. Es un modelo distinto al de pendiente aleatoria (que tenía un AIC de 1756) y ambos explican parte de la misma variación; también se pueden combinar.\n\n## 9. Modelos no lineales mixtos\n\nMuchos procesos (crecimiento, cinética química) no son lineales. `nlme()` ajusta una curva no lineal en la que **algunos parámetros varían por grupo**. Ejemplo: el crecimiento en altura de 14 árboles de pino (`Loblolly`) que se aproxima a una asíntota:\n\n$$\naltura = Asym + (R_0 - Asym)\\, e^{-e^{lrc}\\, edad}\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_nl <- nlme(height ~ SSasymp(age, Asym, R0, lrc),\n             data = Loblolly,\n             fixed = Asym + R0 + lrc ~ 1,\n             random = Asym ~ 1 | Seed,          # cada árbol tiene su propia asíntota\n             start = c(Asym = 94, R0 = -8.25, lrc = -3.2))\nsummary(m_nl)$tTable\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          Value  Std.Error DF   t-value      p-value\nAsym 101.448063 2.46160066 68  41.21223 7.874756e-50\nR0    -8.627523 0.31795212 68 -27.13466 3.341766e-38\nlrc   -3.233727 0.03426941 68 -94.36189 7.807066e-74\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nedades <- seq(3, 25, length.out = 100)\ncurva_pob <- tibble(age = edades, height = predict(m_nl, newdata = data.frame(age = edades, Seed = NA), level = 0))\n\nLoblolly |>\n  mutate(ajustado = fitted(m_nl)) |>\n  ggplot(aes(age)) +\n  geom_point(aes(y = height, colour = Seed), size = 1.4, show.legend = FALSE) +\n  geom_line(aes(y = ajustado, colour = Seed, group = Seed), linewidth = 0.4, show.legend = FALSE) +\n  geom_line(data = curva_pob, aes(y = height), linewidth = 1.2) +\n  scale_colour_viridis_d() +\n  labs(x = \"Edad (años)\", y = \"Altura (pies)\")\n```\n\n::: {.cell-output-display}\n![Crecimiento de 14 pinos. Puntos: datos; líneas: curvas ajustadas por árbol; línea negra: curva promedio de la población.](06-modelos-mixtos_files/figure-html/fig-nlme-1.png){#fig-nlme width=1050}\n:::\n:::\n\n\n## Ejercicios\n\n1. **Intercepto aleatorio.** Con `Orthodont` (paquete `nlme`), ajusta `distance ~ age + (1 | Subject)` con `lmer()`. ¿Cuánto crece la distancia por año? ¿Cuál es el ICC?\n2. **Pendiente aleatoria.** Añade `age` como pendiente aleatoria. ¿Mejora el modelo (usa `anova()` y AIC)?\n3. **Efecto fijo del sexo.** Agrega `Sex` y su interacción con `age`. ¿Crece igual la distancia en niños y niñas?\n4. **Pseudoreplicación.** Ajusta el mismo modelo con `lm()` y compara los errores estándar. ¿Qué observas?\n\n::: {.callout-note collapse=\"true\"}\n## Soluciones sugeridas\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(Orthodont, package = \"nlme\")\no1 <- lmer(distance ~ age + (1 | Subject), data = Orthodont)\no2 <- lmer(distance ~ age + (age | Subject), data = Orthodont)\nfixef(o1)[\"age\"]; icc(o1)$ICC_adjusted\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      age \n0.6601852 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6857391\n```\n\n\n:::\n\n```{.r .cell-code}\nanova(o1, o2, refit = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nData: Orthodont\nModels:\no1: distance ~ age + (1 | Subject)\no2: distance ~ age + (age | Subject)\n   npar    AIC    BIC  logLik -2*log(L)  Chisq Df Pr(>Chisq)\no1    4 455.00 465.73 -223.50    447.00                     \no2    6 454.64 470.73 -221.32    442.64 4.3658  2     0.1127\n```\n\n\n:::\n\n```{.r .cell-code}\no3 <- lmer(distance ~ age * Sex + (1 | Subject), data = Orthodont)\nsummary(o3)$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                Estimate Std. Error       df    t value     Pr(>|t|)\n(Intercept)   16.3406250  0.9813122 103.9864 16.6518101 4.193843e-31\nage            0.7843750  0.0775011  79.0000 10.1208235 6.441815e-16\nSexFemale      1.0321023  1.5374208 103.9864  0.6713206 5.035049e-01\nage:SexFemale -0.3048295  0.1214209  79.0000 -2.5105197 1.409745e-02\n```\n\n\n:::\n\n```{.r .cell-code}\nrbind(lm = summary(lm(distance ~ age, data = Orthodont))$coefficients[\"age\", 1:2],\n      mixto = summary(o1)$coefficients[\"age\", 1:2])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       Estimate Std. Error\nlm    0.6601852 0.10918158\nmixto 0.6601852 0.06160592\n```\n\n\n:::\n:::\n\n:::\n\n## Para profundizar\n\n- Bates, D., Mächler, M., Bolker, B. y Walker, S. (2015). Fitting linear mixed-effects models using lme4. *Journal of Statistical Software*, 67(1), 1–48. <https://doi.org/10.18637/jss.v067.i01>\n- Pinheiro, J. C. y Bates, D. M. (2000). *Mixed-Effects Models in S and S-PLUS*. Springer.\n- Zuur, A. F., Ieno, E. N., Walker, N., Saveliev, A. A. y Smith, G. M. (2009). *Mixed Effects Models and Extensions in Ecology with R*. Springer.\n- Barr, D. J., Levy, R., Scheepers, C. y Tily, H. J. (2013). Random effects structure for confirmatory hypothesis testing: keep it maximal. *Journal of Memory and Language*, 68(3), 255–278.\n- Hurlbert, S. H. (1984). Pseudoreplication and the design of ecological field experiments. *Ecological Monographs*, 54(2), 187–211.\n- Belenky, G. et al. (2003). Patterns of performance degradation and restoration during sleep restriction. *Journal of Sleep Research*, 12(1), 1–12.\n\n::: {.callout-note appearance=\"minimal\"}\n## Reproducibilidad\nEste cuaderno se ejecutó con R 4.5.2 y lme4 2.0.6.\n:::\n",
    "supporting": [
      "06-modelos-mixtos_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}