---
title: "Escritura y publicación académica"
format: html
editor: visual
---

# **Lectura y videos de introducción al tema**

::: {layout-ncol="2"}
{{< video "https://youtu.be/7_jkXN8dsaE?t=6246" >}} Por qué es importante saber leer y escribir. Mision de sabios 2020 (1:44-1:48). "*Un país que no sabe leer y escribir es un país que no sabe pensar. Un país que no sabe pensar* *es un país que no puede entrar en la innovación*."

{{< video "https://youtu.be/9AN2tbfSGm4?si=Q4CjOY2qbf1lAHG6" >}} Why Do Academics Write So Poorly?
:::

-   Steve Pinker

    -   Why Academics Stink at Writing by Steven Pinker. [*Link*](https://www.google.com/search?q=Why+Academics+Stink+at+Writing+by+Steven+Pinker&rlz=1C5OZZY_enCO1132CO1132&oq=Why+Academics+Stink+at+Writing+by+Steven+Pinker&gs_lcrp=EgZjaHJvbWUyBggAEEUYOdIBBzEzNGowajSoAgCwAgE&sourceid=chrome&ie=UTF-8#:~:text=Why%2DAcademics%2DStink,2016/06%20%E2%80%BA%20Wh...)
    -   *Por qué los académicos apestan cuando escriben*. [***Link***](https://davidlabaree-com.translate.goog/2021/07/08/pinker-why-academics-stink-at-writing/?_x_tr_sl=en&_x_tr_tl=es&_x_tr_hl=es-419&_x_tr_pto=nui)
    -   Lingüística, Estilo y Escritura en el Siglo 21. Steven Pinker. [*Link*](https://www.youtube.com/watch?v=OV5J6BfToSw)*.*
    -   Why academic writing stinks and how to fix it. [*Link*](https://www.chronicle.com/article/why-academics-stink-at-writing-and-how-to-fix-it/)
    -   On bad and good writing. [*Link*](https://www.youtube.com/watch?v=IMVOHeQYCUY)*.*

-   The best way to teach people critical thinking is to teach them to write. [*Link*](https://x.com/ScholarshipfPhd/status/1929240865907618048)

    ::: {.callout-tip title="**Mandamientos de la escritura académica** (Algunos basados en [Hugh Kearns](https://twitter.com/ithinkwellHugh))"}
    -   La escritura se realiza oración por oración.
    -   La escritura se realiza oración por oración.
    -   Sin buenas oraciones no hay buenos párrafos. Sin párrafos no hay manuscrito (artículo, artículo científico, capítulo o informe).
    -   Sujeto-verbo-predicado es la estructura más poderosa en redacción.
    -   *KISS* (keep it simple, stupid).
    -   Sin lectura, no hay escritura.
    -   ¿Puedo expresarlo en menos palabras?
    -   La mala escritura, precede la buena escritura (para escribir bien, primero hay que escribir mal). No tener miedo a eliminar lo escrito.
    -   Escribir es esencialmente reescribir (pero necesita identificar la mala escritura y saber reparar lo que está mal escrito).
    -   Es mejor entregar un 80% de 100%, que entregar un 0% de 100%.
    -   Escriba sus vivencias, sorprenda al lector y dígale algo que no sepa.
    :::

# La oración

-   De la oración simple a la oración compuesta. 1993. Héctor Campos. [*Link*](https://books.google.com.co/books?id=elBtphM7K3wC&printsec=frontcover&source=gbs_ge_summary_r&cad=0#v=onepage&q&f=false)
-   Construir bien en español: la corrección sintáctica. Hortensia Martínez, 2005. [*Link*](https://books.google.com.co/books?id=S4yeEGoP1dUC&printsec=frontcover&source=gbs_ge_summary_r&cad=0#v=onepage&q&f=false).
-   Gramática y ortografía básicas de la lengua española. RAE. [*Link*](https://www.rae.es/obras-academicas/gramatica/gramatica-y-ortografia-basicas-de-la-lengua-espanola).
-   Piled Modifiers, Buried Verbs, and Other Turgid Prose in the *American Political Science Review*. [*Link*](https://www.cambridge.org/core/journals/ps-political-science-and-politics/article/abs/piled-modifiers-buried-verbs-and-other-turgid-prose-in-the-american-political-science-review/A69D5F1A3CB222EFA4DCAE8993FACC72#)
-   Aprender a aprender. Entender cómo funciona nuestro cerebro para mejorar nuestro proceso creativo y de escritura.

# El párrafo

-   La cocina de la escritura. Cassany, Daniel. Anagrama. 2006. [*Link*](http://www.anagrama-ed.es/libro/argumentos/la-cocina-de-la-escritura/9788433913920/A_162). 2021 [*Link*](https://books.google.com.co/books?id=vHIZEAAAQBAJ&printsec=frontcover&dq=La+cocina+de+la+escritura+Daniel+Cassany&hl=es-419&sa=X&redir_esc=y#v=onepage&q=La%20cocina%20de%20la%20escritura%20Daniel%20Cassany&f=false)
-   Strategies for Successful Writing A Rhetoric, Research Guide, Reader and Handbook. 2015. James A. Reinking, Robert A. von der Osten. [*Link*](https://books.google.com.co/books?id=c1m6BwAAQBAJ). [*Link*](https://www.pearson.com/us/higher-education/program/Reinking-Strategies-for-Successful-Writing-A-Rhetoric-Research-Guide-Reader-and-Handbook-Plus-My-Lab-Writing-with-e-Text-Access-Card-Package-10th-Edition/PGM202268.html?tab=contents).
-   Steps to Writing Well with Additional Readings. Jean Wyrick. Cengage Learning. 2021. [*Link*](https://books.google.com.co/books?id=oJQMEAAAQBAJ)*, [link](https://www.cengagebrain.com.mx/shop/isbn/9781337899796)*.
-   Exploring Writing: Sentences and Paragraphs. 2005. [*Link*](https://books.google.com.co/books?id=i0QuPwAACAAJ&).
-   Effective Academic Writing 1: The Paragraph. Alice Savage, Masoud Shafiei. [*Link*](https://books.google.com.co/books?id=Z15_QwAACAAJ&).
-   The Writer’s Diet. [*Link*](http://writersdiet.com/).
-   Trees, maps, and theorems. [*Link*](http://www.principiae.be/X0300.php).
-   Web de Publicaciones Chicago Press. [*Link*](http://www.press.uchicago.edu/ucp/books/series/CGWEP.html).
-   Tipos de párrafo. The University of Manchester. [*Link*](https://www.phrasebank.manchester.ac.uk/).
-   **Argumentación**
    -   La estructura de la ciencia. Nagel, E., Editorial Paidós, 2006. [*Link*](https://books.google.com.co/books?id=TD2P5I3zGrEC&printsec=frontcover&hl=es&source=gbs_ge_summary_r&cad=0#v=onepage&q&f=false).

    -   10 Ideas Clave. Competencias en argumentación y uso de pruebas. Jimenez, 2010. [*Link*](https://books.google.com.co/books?id=q_A4e536y3wC&printsec=frontcover&source=gbs_ge_summary_r&cad=0#v=onepage&q&f=false).

    -   Key concepts for making informed choices. Nature 2019. [*Link*](https://wordpress.com/block-editor/post/mauricioromerot.wordpress.com/346).

    -   A Practical Study of Argument, Cengage Learning. Govier, T. 2009. [*Link*](https://books.google.es/books?id=IUxXbUvDiswC&printsec=frontcover&hl=es&source=gbs_ge_summary_r&cad=0#v=onepage&q&f=false).

    -   The Uses of Argument, Cambridge University Press. Toulmin, S. E. 2003. [*Link*](https://books.google.com.co/books?id=8UYgegaB1S0C&printsec=frontcover&source=gbs_ge_summary_r&cad=0#v=onepage&q&f=false).

    -   Argumentation in Science Education: Perspectives from Classroom-Based Research, Springer. Erduran, S. and M. Aleixandre. 2007. [*Link*](https://www.springer.com/gp/book/9781402066696).

    -   Natural Language → Knowledge Graph. [*Link*](https://github.com/varunshenoy/GraphGPT). 🤔

# El estilo científico

## **Textos de referecia**

-   Simon & Schuster Handbook for Writers, 10th Edition. By Lynn Quitman Troyka, Doug Hesse. Pearson. 2013. [*Link*](https://books.google.com.co/books?id=NppKBAAAQBAJ).
-   Pinker, S. The Sense of Style: The Thinking Person's Guide to Writing in the 21st Century. New York, NY: Penguin. [*Link*](https://stevenpinker.com/publications/sense-style-thinking-persons-guide-writing-21st-century).
-   A Writers Reference. Diana Hacker, Nancy Sommers. 2016. [*Link*](https://books.google.com.co/books?id=Hvq6DAAAQBAJ).

::: {layout-ncol="2"}
{{< video "https://www.youtube.com/watch?v=OV5J6BfToSw" >}} Lingüística, Estilo y Escritura en el Siglo 21 - con Steven Pinker

{{< video "https://youtu.be/H5JWKbrHOAE" >}} Introducing the 7th Ed. APA Style Publication Manual

Escribiendo con estilo
:::

-   **Manuales de estilo**
    -   Manual de publicaciones de Ia American Psychological Association
        -   Tercera edición. [*Link*](https://books.google.com.co/books?id=PQf-CAAAQBAJ).
        -   Séptima (inglés) y cuarta edición (español). [*Link*](https://apastyle.apa.org/).
        -   APA Style CENTRAL for Students. [*Link*](http://www.apastyle.org/products/asc-for-students.aspx).
    -   Scientific Style and Format: The CSE Manual for Authors, Editors, and Publishers. [*Link*](https://books.google.com.co/books?id=aCsjngEACAAJ).
    -   The Chicago Manual of Style. [*Link*](https://www.chicagomanualofstyle.org/16/contents.html).
        -   Chicago Style Workout 62: Dashes. [*Link*](https://cmosshoptalk.com/2022/02/22/chicago-style-workout-62-dashes).
        -   When to Capitalize after a Colon. [*Link*](https://cmosshoptalk.com/2022/02/15/when-to-capitalize-after-a-colon/).
    -   Manual del estilo del Servicio Geológico Colombiano. [*Link*](https://libros.sgc.gov.co/index.php/editorial/catalog/book/74).
    -   **RAE**. Lenguaje inclusivo. [*Link*](https://www.rae.es/espanol-al-dia/los-ciudadanos-y-las-ciudadanas-los-ninos-y-las-ninas)*, [Link](https://www.rae.es/sites/default/files/Informe_lenguaje_inclusivo.pdf).*
-   Cómo se hace una tesis. Umberto Eco. 2014. [*Link*](https://books.google.com.co/books?id=6i0lBQAAQBAJ&dq=como+escribir+una+tesis+umberto+eco&source=gbs_navlinks_s)

::: callout-tip
## Elementos de estilo

-   Running-heads. CMS. [*Link*](https://www.chicagomanualofstyle.org/search.html?clause=run-in+heading)*.*
:::

# **El papel del editor y procesos editoriales**

-   Editor Roles and Responsibilities. Council of Science Editors. [*Link*](https://www.councilscienceeditors.org/resource-library/editorial-policies/white-paper-on-publication-ethics/2-1-editor-roles-and-responsibilities/).
-   Manual de edición académica. Jorge Beltrán. Editorial Universidad Nacional de Colombia. [*Link*](https://www.uneditorial.com/manual-de-edicion-academica-sistemas-de-informacion.html). [*Link*](https://editorial.unal.edu.co/fileadmin/recursos/editorial/guias/guia-basica-procesos-editoriales.pdf).
-   Guía básica de procesos editoriales. Editorial Universidad Nacional de Colombia. [*Link*](https://editorial.unal.edu.co/fileadmin/recursos/editorial/guias/guia-basica-procesos-editoriales.pdf).
-   How Books and Journals Are Produced. [*Link*](https://www.chicagomanualofstyle.org/help-tools/production-technologies.html).

# **Nuevas formas de publicación de libros**

-   Quarto. [*Link*](https://quartopub.com/)
    -   Creating a book. [*Link*](https://quarto.org/docs/books/)
-   Ejemplo libro Quarto.
    -   [*Link*](https://github.com/hadley/r4ds). [*Link*](https://openintro-ims.netlify.app/data-hello)*.*
-   Bookdown. [*Link*](https://bookdown.org/).
    -   Bookdown: Authoring Books and Technical Documents with R Markdown. [*Link*](https://bookdown.org/yihui/bookdown/).
    -   Escritura de libros con bookdown. [*Link*](https://rubenfcasal.github.io/bookdown_intro/).
-   The Epidemiologist R Handbook. [*Link*](https://epirhandbook.com/).
-   Reproducible Medical Research with R. [*Link*](https://bookdown.org/pdr_higgins/rmrwr/).
-   Gitbook. [*Link*](https://www.gitbook.com/)
-   Overleaf. [*Link*](https://www.overleaf.com/learn/latex/Tutorials). Books templates. *Link*.
-   Markdown syntax. [*Link*](https://daringfireball.net/projects/markdown/syntax).
-   **Herramientas**
-   **Gramática y estilo**
    -   Grammarly. [*Link*](https://app.grammarly.com/)*.*
    -   Writefull. [*Link*](https://writefull.com/).
    -   The WritersDiet Test. [*Link*](http://writersdiet.com/?page_id=4).
    -   Writing Clarity Calculator. [*Link*](http://writingclaritycalculator.com/).
    -   IA Writter. [*Link*](https://ia.net/es/writer).
    -   Selecting vocabulary: Academic word list. [*Link*](http://www.uefap.com/vocab/select/awl.htm?utm_content=buffera660d&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer).
-   **Vocabulary**.
    -   Scite.ai tracks positive and negative citations. [*Link*](https://scite.ai/). [*Link*](https://www.nature.com/articles/d41586-020-01324-6).
    -   Robo-writers: the rise and risks of language-generating AI. Nature, 2021. [*Link*](https://www.nature.com/articles/d41586-021-00530-0#ref-CR2).
    -   Poor English skills? New AIs help researchers to write better. Nature. 2022. [*Link*](https://www.nature.com/articles/d41586-022-02767-9).
-   **Plagio**
    -   10 Types of Plagiarism in Research. [*Link*](https://www.wiley.com/network/researchers/submission-and-navigating-peer-review/10-types-of-plagiarism-in-research?hootPostID=3095d30299084add258f76762d80796a).
    -   Plagiarism detectors are a crutch, and a problem. Nature. [*Link*](https://www.nature.com/articles/d41586-019-00893-5).\*\*
    -   Cómo la tesis de Jennifer Arias puede afectar la cultura científica del País. [*Link*](https://www.lasillavacia.com/historias/historias-silla-llena/como-la-tesis-de-jennifer-arias-puede-afectar-la-cultura-cientifica-del-pais/?fbclid=IwAR0TjPCkw764NAHiWRNirrYd1y3oKTWHNHyTNzZilokzGbJ23PxHLMPp82U).
    -   Plagio ¿qué es y cómo actúa la legislación colombiana frente a este? UNAL 2020. [*Link*](http://www.unperiodico.unal.edu.co/pages/detail/plagio-que-es-y-como-actua-la-legislacion-colombiana-frente-a-este/).
    -   Así son los talleres clandestinos que producen miles de investigaciones científicas falsas. [*Link*](https://www.elconfidencial.com/tecnologia/ciencia/2022-12-26/talleres-clandestinos-investigaciones-falsas_3546695/).
-   **Español**
    -   PlagScan. [*Link*](https://www.plagscan.com/es/).\*\*\*
    -   Plagium. [*Link*](http://www.plagium.com/).
-   **Inglés**
    -   Ithenticate. [*Link*](http://www.ithenticate.com/)
    -   Turnitin. [*Link*](https://www.turnitin.com/).
    -   Plagiarism Checker. [*Link*](http://www.plagiarismchecker.com/).
    -   Copyscape. [*Link*](https://www.copyscape.com/).
-   **Para resumir artículos** (esto debe actualizarse)
    -   Auto articles: an experiment in AI-generated content. Nature. [*Link*](https://www.natureindex.com/news-blog/auto-articles-an-experiment-in-ai-generated-content).
    -   Paper Digest. [*Link*](https://www.paper-digest.com/).
    -   SCITLDR. [*Link*](https://scitldr.apps.allenai.org/).
    -   tl;dr: this AI sums up research papers in a sentence. Nature. [*Link*](https://www.nature.com/articles/d41586-020-03277-2).
    -   Summarization. Huggingface. [*Link*](https://huggingface.co/tasks/summarization).
-   **Para parafresear texto** (esto debe actualizarse)
    -   Quillbot. [*Link*](https://quillbot.com/).
-   **Para explorar la literatura científica**
    -   Connected papers. [*Link*](https://www.connectedpapers.com/).
    -   Drowning in the literature? These smart software tools can help. [*Link*](https://www.nature.com/articles/d41586-021-02346-4).
    -   **litsearchr** an R package to facilitate quasi-automatic search strategy development for systematic reviews. [*Link*](https://elizagrames.github.io/litsearchr/).
-   **Referencias bibliográficas**
    -   AnyStyle. [*Link*](https://anystyle.io/).
-   **Para transformar texto a voz**
    -   Natural readers. [*Link*](https://www.naturalreaders.com/).
-   **AI. Para pensar en lo que viene** (esto debe actualizarse)
    -   A.I. Is Mastering Language. Should We Trust What It Says? NYT 2022 [*Link*](https://www.nytimes.com/2022/04/15/magazine/ai-language.html).
    -   Escritores están empezando a utilizar inteligencia artificial para producir novelas rápidamente. [*Link*](https://www.dw.com/es/escritores-est%C3%A1n-empezando-a-utilizar-inteligencia-artificial-para-producir-novelas-r%C3%A1pidamente/a-62569707).
    -   Poor English skills? New AIs help researchers to write better. Nature. 2022. [*Link*](https://www.nature.com/articles/d41586-022-02767-9).
    -   Best Practices for Using AI When Writing Scientific Manuscripts, 2023. [*Link*](https://pubs.acs.org/doi/10.1021/acsnano.3c01544)
-   **Herramientas de inteligencia artificial** (esto debe actualizarse)
    -   Top 10 Alternatives to GPT-3. [*Link*](https://analyticsindiamag.com/top-10-alternatives-to-gpt-3/).
    -   How To Use ChatGPT To Create AI Art Prompts. [*Link*](https://medium.com/mlearning-ai/how-to-use-chatgpt-to-create-ai-art-prompts-7a63e402814d)
    -   The Role of AI in Drug Discovery: Challenges, Opportunities, and Strategies. 2022. [*Link*](https://arxiv.org/abs/2212.08104).

Grammarly

Sudowrite

Chat GPT

::: callout-tip
## **Umberto Eco’s 36 Rules for Writing Well [Link](https://www.openculture.com/2021/06/umberto-ecos-36-rules-for-writing-well-in-english-or-italian.html).**

-   *Avoid alliterations, even if they’re manna for morons.*
-   *Avoid clichés: they’re like death warmed over.*
-   *Never generalize.*
-   *Hold those quotes. Emerson aptly said, “I hate quotes. Tell me only what you know.”*
-   *Don’t write one-word sentences. Ever.*
-   *Recognize the difference between the semicolon and the colon: even if it’s hard.*
-   *Do you really need rhetorical questions?*
-   *Be concise; try expressing your thoughts with the least possible number of words, avoiding long sentences– or sentences interrupted by incidental phrases that always confuse the casual reader– in order to avoid contributing to the general pollution of information, which is surely (particularly when it is uselessly ripe with unnecessary explanations, or at least non indispensable specifications) one of the tragedies of our media-dominated time.*
-   *Don’t be emphatic! Be careful with exclamation marks!*
-   *No need to tell you how cloying preteritions are.*
:::

-   **Ejercicios de redacción**
    -   Teach With These 13 Times Columns. NYT. 2023. [*Link*](https://www.nytimes.com/2023/01/04/learning/lesson-plans/teach-with-these-13-times-columns.html).
    -   Del diálogo de saberes a la negociación cultural.Recuperar, deconstruir, resignificar y recrear saberes. 2015. Revista Red Pensar. [*Link*](https://ojs.redpensar.ulasalle.ac.cr/index.php/redpensar/article/view/77).
    -   El poder de la Cartografía Social en las prácticas contrahegemónicas o La Cartografía Social como estrategia para diagnosticar nuestro territorio. 2006. [*Link*](http://beu.extension.unicen.edu.ar/xmlui/handle/123456789/365).

# Dónde está la información científica

Esta es una lista de las principales bases de datos de artículos científicos y libros. Algunas de estas son gratuitas, otras por suscripción institucional. No se listan casas editoriales (e.g. Springer o Elsevier). Consulte su biblioteca para conocer sus suscripciones vigentes. No se presentan bases de datos especializadas como las de medicina, química, derecho o educación.

-   **Mundiales**
-   ***Por suscripción***
-   Scopus. \*[Link](https://www.scopus.com/).\*\*[Link-PUJ](https://javeriana.libguides.com/az.php)\*
    -   Videos de entrenamiento. [*Link*](https://www.youtube.com/playlist?list=PLybnJ-_lBeFYde-V1TR9-s-6Ef1NhZIC9).
-   Web of Science. [*Link*](http://apps.webofknowledge.com/)*.*
    -   Entrenamiento. [*Link*](http://clarivate.libguides.com/webofscienceplatform).
    -   Videos. [*Link*](https://www.youtube.com/user/WoSTraining).
-   ASTM. [*Link*](https://www.astm.org/)*.*
-   ***Abiertos***
-   D imensions. [*Link*](https://www.dimensions.ai/).
    -   Videos entrenamiento.[*Link*](https://dimensions.freshdesk.com/support/solutions/articles/23000018802-how-to-search-in-dimensions). [*Link*](https://www.youtube.com/channel/UCUweBvolfJTXEAxDCc5lntQ).
    -   Producción para Covid. [*Link*](https://l.facebook.com/l.php?u=https%3A%2F%2Ft.co%2F1HfeaRv4wx%3Famp%3D1%26fbclid%3DIwAR3my8MP12w-gI7VwS_pORTQQgbxZ-wMXiDZ1I48-N2PuD9DtTGIN-G61vk&h=AT2h_360FADm3nMf-yWLT185f4tn4MOOEluce2px8IHDvKVbd7FhV2L5PAlbfs7KRkLeLc_Tdv_yiUtAJoojgKOJNCylKH6lE9Gn8fd6XIq4YbRg7aOuGLYrorlPDocOndGHAsj7Yc2rLY8O4Qykf-8&__tn__=-UK-R&c%5B0%5D=AT0IlQMCWSnRTK5SUm-Pt0J-3TaHxn0qMA8aR2TyiT0TgSnuAYMo1_OyDV4fXtORPhY7lT-aE5zmsRBEeJI4OLH02Lv9FHv_r8rtAIVYYx009wRwJu-VLbib8EiiixQimB4JPv4T7enAigr3ki9RhTz9Y2bqHc8e71aTVW41gccbpUc).
    -   Dimensions API Lab. [*Link*](https://api-lab.dimensions.ai/).
-   Open Alex. [Link](https://openalex.org/)
-   Google Académico. [*Link*](https://scholar.google.com/)*.*
-   Semantic Scholar. [*Link*](https://www.semanticscholar.org/).
-   Bielefeld Academic Search Engine. [Link](https://www.base-search.net/).
-   Ovid. [*Link*](http://ovidsp.tx.ovid.com/)*.*
    -   ROR. [*Link*](https://ror.org/scope/).
    -   Open Alex. [*Link*](https://docs.openalex.org/).
-   Proquest. [*Link*](http://search.proquest.com/)*.*
-   Ulrichweb. [*Link*](http://ulrichsweb.serialssolutions.com/)*.*
-   zbMath. [*Link*](https://zbmath.org/).
-   1finder. [*Link*](https://www.1science.com/1findr/).
-   Lens. [*Link*](https://www.lens.org/).
-   DataSearch Elsevier. [*Link*](https://datasearch.elsevier.com/#/).
-   Google Dataset Search. [*Link*](https://toolbox.google.com/datasetsearch).
-   DOI
    -   Search doi. [*Link*](https://dx.doi.org/)
    -   Short doi. [*Link*](http://shortdoi.org/)
-   **Latinoamericanas**
    -   Scielo. [*Link*](http://www.scielo.org/).
    -   Latindex. [*Link*](http://www.latindex.org/).
    -   Redalyc. [*Link*](https://www.redalyc.org/home.oa).
    -   Dialnet. [*Link*](https://dialnet.unirioja.es/).
-   **Libros**
    -   Google Books. [*Link*](https://books.google.com/).
    -   Amazon Books. [*Link*](https://www.amazon.com/books-used-books-textbooks/).
    -   WorldCat. [*Link*](https://www.worldcat.org/).
-   **Bases de datos de videos académicos**. Además de Youtube, estos son algunos enlaces útiles.
    -   Oregon State University. [*Link*](https://media.oregonstate.edu/).
    -   Learning Centre JCU. [*Link*](https://www.jcu.edu.au/students/learning-centre).
    -   Integration and Application Network. Imágenes. [*Link*](http://ian.umces.edu/imagelibrary/).
    -   MIT Open Courseware. [*Link*](https://ocw.mit.edu/index.htm).
    -   Open Yale Courses. [*Link*](https://oyc.yale.edu/).
-   **Identificadores de investigación.**
    -   Global Research Identifier Database. GRID. [*Link*](https://www.grid.ac/)

# Bibliometría

-   Bibliometrics for Librarians. [*Link*](https://pdoehle.github.io/bibliometrics-for-librarians/).
-   **Lecturas para uso de bases de datos y métricas de la ciencia**
    -   Citation Performance Indicators — A Very Short Introduction. 2017. [*Link*](https://scholarlykitchen.sspnet.org/2017/05/15/citation-performance-indicators-short-introduction/)
    -   Contra el pensamiento mágico de la bibliometría. [*Link*](https://listserv.rediris.es/cgi-bin/wa?A2=IWETEL;a5e19177.2207a&S=).
    -   Collaboration in an invisible college. Price D, Beaver D. 1966. American Psychologist. [*Link*](https://www.researchgate.net/profile/Donald_Beaver2/publication/17263883_Collaboration_in_an_invisible_college/links/54070ff80cf23d9765a8342e.pdf).
    -   Games academics play and their consequences: how authorship, *h* -index and journal impact factors are shaping the future of academia. 2019. [*Link*](https://royalsocietypublishing.org/doi/10.1098/rspb.2019.2047).
    -   New tools for measuring academic performance. Science. 2017. [*Link*](http://www.sciencemag.org/careers/features/2017/02/new-tools-measuring-academic-performance?utm_source=sciencecareers&utm_medium=facebook&utm_campaign=CPOfeature-11041).
    -   Open-access megajournals lose momentum. Science. 2019. [*Link*](https://science.sciencemag.org/content/365/6458/1067)
    -   Rethinking impact factors: better ways to judge a journal. Nature. 2019. [*Link*](https://www.nature.com/articles/d41586-019-01643-3).
    -   Seven Myths in Bibliometrics. About facts and fiction in quantitative science studies. 2013. [*Link*](http://www.tandfonline.com/doi/abs/10.1080/09737766.2008.10700836).
    -   Scientific literature: Information overload. Nature. 2016. [*Link*](http://www.nature.com/naturejobs/science/articles/10.1038/nj7612-457a?WT.mc_id=TWT_NatureNews)
    -   Science and inequality. Nature. 2016. [*Link*](http://www.nature.com/news/science-s-1-how-income-inequality-is-getting-worse-in-research-1.20651?WT.mc_id=FBK_NA_1609_FHNEWSFSCIENCES1PERCENT_PORTFOLIO). [*Link*](http://www.nature.com/news/socio-economic-inequality-in-science-is-on-the-rise-1.20654?WT.ec_id=NATURE-20160922&spMailingID=52357585&spUserID=MjA1NjE1MDUwMQS2&spJobID=1003755044&spReportId=MTAwMzc1NTA0NAS2). [*Link*](http://www.nature.com/news/science-and-inequality-1.20652?WT.ec_id=NATURE-20160922&spMailingID=52357585&spUserID=MjA1NjE1MDUwMQS2&spJobID=1003755044&spReportId=MTAwMzc1NTA0NAS2).
    -   The holy grail of science policy: Exploring and combining bibliometric tools in search of scientific excellence. Scientometrics. 2003. [*Link*](http://www.cwts.nl/tvr/documents/avr-holygrail.pdf).
    -   The matthew effect in science: The reward and communication systems of science are considered. Science. Merton R. 1968. [*Link*](http://www.garfield.library.upenn.edu/merton/matthew1.pdf)
    -   Time to remodel the journal impact factor. Nature. 2016. [*Link*](http://www.nature.com/news/time-to-remodel-the-journal-impact-factor-1.20332?WT.mc_id=TWT_NatureNews).
    -   The quiet rise of the NIH’s hot new metric. Nature. 2016. [*Link*](http://www.nature.com/news/the-quiet-rise-of-the-nih-s-hot-new-metric-1.20957).
    -   Torres-Salinas, D. web page. [*Link.*](https://sites.google.com/go.ugr.es/torressalinas/talks?authuser=0)
    -   How to Use the Science Citation Index. 1967. Video. [*Link*](https://www.youtube.com/watch?v=abNZ66ZLbjU), [*Link*](https://www.youtube.com/watch?v=qowEMw8TZds).
    -   How will you judge me if not by impact factor? Nature 2018. [*Link*](https://www.nature.com/articles/d41586-018-05467-5?fbclid=IwAR2_v449dj0Ts8lpdQ5vA1JtmpeD10AaKdFH7Zf5XN2hzZLZDISvABuFPBo).
    -   What do citation counts measure? A review of studies on citing behaviour. Journal of Documentation. 2008. [*Link*](http://pubman.mpdl.mpg.de/pubman/item/escidoc:1758962/component/escidoc:1758961/BornmannLutzCitingBehavior.pdf).
    -   Zipf, Power-laws, and Pareto - a ranking tutorial. [*Link*](http://www.hpl.hp.com/research/idl/papers/ranking/ranking.html)*. [Link](http://power%20laws%2C%20pareto%20distributions%20and%20zipf%27s%20law/). [Link](http://tuvalu.santafe.edu/~aaronc/powerlaws/data.htm).*

Science of Science Summer School. [*Link*](https://s4.scienceofscience.org/).

Retos de la medición de la CTeI

-   **Administrador de referencias bibliográficas**
-   EndNote. [*Link*](http://community.thomsonreuters.com/ts/?category.id=endnote). Training. [*Link*](http://endnote.com/training).
-   Mendeley. [*Link*](https://www.mendeley.com/). Cómo usar Mendeley. [*Link*](http://bibliolab.co/como-usar-mendeley/)
-   Papers. [*Link*](http://papersapp.com/).
-   Citedrive (for Overleaf, LaTeX, and R Markdown users). [*Link*](https://citedrive.com/).
-   Zotero. [*Link*](https://www.zotero.org/). Zotero Scihub. [*Link*](https://github.com/ethanwillis/zotero-scihub). Acceso Webdav: [Nextcloud](https://docs.nextcloud.com/server/latest/user_manual/es/files/access_webdav.html), [Koofr](https://koofr.eu/blog/posts/koofr-with-zotero-via-webdav)
-   Para Google Docs: Paperpile. [*Link*](https://paperpile.com/). Using Zotero with Google Docs. [*Link*](https://www.zotero.org/support/google_docs).
-   Adding references to EndNote from a Word document. [*Link*](https://guides.library.uwa.edu.au/c.php?g=595333&p=4118568).
-   Crossref. Get persistent links for your reference list or bibliography. [*Link*](https://doi.crossref.org/simpleTextQuery).\*\*
-   Find journal Title abbreviations. [*Link*](http://library.stanford.edu/guides/find-journal-abbreviations)*.* Caltech Library. [*Link*](https://www.library.caltech.edu/journal-title-abbreviations).

<https://youtu.be/BdOrncz0NYQ>

-   **Cómo encontrar los pdfs del texto completo de una publicación:**
    -   Utilice las suscripciones a revistas y bases de datos de su institución.
    -   Instale el pluggin para Chrome Kopernio [*Link*](https://kopernio.com/).
    -   Buscar la publicación en Google Scholar, luego busque si el pdf está disponible.
    -   Busque en la página personal de los autores \> escriba a los autores.
    -   Busque en otros servicios como Academia, Twitter, o en google con el comando: *titulo* filetype:pdf
    -   Open Access Button. [*Link*](https://openaccessbutton.org/)
-   **Cómo leer un paper**
    -   How to (seriously) read a scientific paper. [*Link*](https://www.sciencemag.org/careers/2016/03/how-seriously-read-scientific-paper).
    -   How to read a paper. [*Link*](https://drive.google.com/file/d/1AvaXdTNU1LPd1ShdUfV2fsxQtZzW2aFT/view).
    -   Resumir un paper. Owl Purdue. Synthesizing Sources. [*Link*](https://owl.purdue.edu/owl/research_and_citation/conducting_research/research_overview/synthesizing_sources.html)
-   **Lecturas:**
    -   Defrosting the Digital Library: Bibliographic Tools for the Next Generation Web. PLoS Comput Biol. 2008. [*Link*](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1000204)
    -   Strategic Reading, Ontologies, and the Future of Scientific Publishing. Science. 2009. [*Link*](http://science.sciencemag.org/content/325/5942/828).
    -   Research Weaving: Visualizing the Future of Research Synthesis. Tree. 2018. [*Link*](https://www.cell.com/trends/ecology-evolution/fulltext/S0169-5347(18)30278-7).
    -   Relationship between conservation biology and ecology shown through machine reading of 32,000 articles. Con Bio, 2010. [*Link*](https://conbio.onlinelibrary.wiley.com/doi/full/10.1111/cobi.13435).
    -   Lithium-Ion Batteries A Machine-Generated Summary of Current Research. Springer, 2019. [*Link.*](https://link.springer.com/book/10.1007/978-3-030-16800-1)
    -   Covid-19
        -   Scientists are drowning in COVID-19 papers. Can new tools keep them afloat? Science. [**Link**](https://www.sciencemag.org/news/2020/05/scientists-are-drowning-covid-19-papers-can-new-tools-keep-them-afloat#).
        -   Waste in covid-19 research. BMJ. [*Link*](https://www.bmj.com/content/369/bmj.m1847).

<https://youtu.be/r-7gQw8eRM0>

-   **Trabajo colaborativo**
    -   Overleaf - Latex Collaborative Writing. [*Link*](https://www.overleaf.com/).
    -   Authorea. .
    -   Manuscripts. [*Link*](https://www.manuscriptsapp.com/).
    -   Google Colaboratory. [*Link*](https://colab.research.google.com/notebooks/intro.ipynb).
    -   Or simply use Google Docs or Word online.
    -   Trello. [*Link*](https://trello.com/).
    -   How to manage a multi-author megapaper. .
    -   Three ways to collaborate on writing. [*Link*](https://www.natureindex.com/news-blog/three-ways-to-collaborate-on-writing).
    -   This simple tool can help you manage multiple research projects. [*Link*](https://www.natureindex.com/news-blog/simple-tool-can-help-manage-multiple-research-science-projects).
    -   How to collaborate more effectively: 5 tips for researchers. [*Link*](https://www.natureindex.com/news-blog/how-to-collaborate-more-effectively-five-tips-for-researchers-science).
    -   Synchronized editing: the future of collaborative writing. [*Link*](https://www.nature.com/articles/d41586-020-00916-6).
-   **DoaThon**
    -   Open doathon. [*Link*](https://doathon.opencon.community/)

# Revisión y síntesis de eviencia

-   **Topic modelling**
    -   Global evidence of human well-being and biodiversity impacts of natural climate solutions. Nature sustainability. 2024. [*Link*](https://www.nature.com/articles/s41893-024-01454-z#Sec13)
-   **Revisión y Meta-Análisis**
    -   Introduction to Systematic Review and Meta-Analysis. Coursera. [*Link*](https://www.coursera.org/learn/systematic-review).
    -   How researchers can improve the quality of systematic reviews. Nature. 2019. [*Link*](https://www.natureindex.com/news-blog/how-researchers-can-improve-the-quality-of-systematic-reviews).
    -   Research Weaving: Visualizing the Future of Research Synthesis. TREE. 2019. [*Link*](https://www.cell.com/trends/ecology-evolution/fulltext/S0169-5347(18)30278-7).
    -   Lecture 1 - scoping and searching studies for meta-analysis \| Hard-Boiled Synthesis (Fall 2020). [*Link*](https://youtu.be/rM4MQA5hU6c).
    -   Evidence Synthesis Hackathon. [*Link*](https://www.eshackathon.org/projects.html). [*Link*](https://twitter.com/eshackathon).
-   **Herramientas con AI**
    -   [NoteBook LM](https://notebooklm.google/).
    -   [Abstrackr](http://abstrackr.cebm.brown.edu/account/login)
    -   Leveraging artificial intelligence to enhance systematic reviews in health research: advanced tools and challenges. 2024. [*Link*](https://systematicreviewsjournal.biomedcentral.com/articles/10.1186/s13643-024-02682-2).
    -   [Scispace](https://typeset.io/). Literature search; Data extraction
        -   What is SciSpace. [*Link*](https://libguides.library.arizona.edu/ai-researchers/scispace).
    -   [Elicit.org](https://elicit.com/). Literature search; Data extraction; Synthesis
    -   [SWIFT-Review](https://www.sciome.com/swift-review/). Identifying research question; Screening; Data extraction; Synthesis
    -   [Research Rabbit](https://www.researchrabbit.ai/). Literature mapping.
    -   [Connected papers.](https://www.connectedpapers.com/)

ESMARConf2023: Workshop 1 - Test, adjust for and report publication bias

# Traducción y Mooc´s

-   **Traducción** (además de Google Translate)
    -   Deepl. [*Link.*](https://www.deepl.com/Translator)
    -   Linguee. [*Link*](http://www.linguee.es/).
    -   Word Reference. [*Link*](http://www.wordreference.com/es/).
-   **Otros recursos para autores**
    -   Springer's Author Academy. .
    -   Resources for authors. Wiley. .
    -   Nature toolbox. Toolbox: Nature's hub for scientific software, apps and online tools. [*Link*](http://www.nature.com/news/toolbox).
    -   Purdue Online Writting Lab. [*Link*](https://owl.purdue.edu/owl/research_and_citation/conducting_research/research_overview/synthesizing_sources.html).
-   **MOOC'S**
    -   **Inglés**
        -   Principles of Written English. edX. [*Link*](https://courses.edx.org/courses/BerkeleyX/ColWri2.1x/3T2013/courseware/c7ca27002260401c826f66e17daff0d1/2ec8c927a35845988547d330e0631618/). Writing in the sciences. Stanford. [*Link*](https://lagunita.stanford.edu/courses/Medicine/SciWrite./Fall2015/about).Learn English, British Council. [*Link*](https://learnenglish.britishcouncil.org/).Master Classes Nature. [*Link*](https://masterclasses.nature.com/).Getting published in peer review by Professor Joshua Cinner. CGIAR. [*Link*](https://fish.cgiar.org/news-and-updates/multimedia/getting-published-peer-review-professor-joshua-cinner).Purdue OWL. [*Link*](https://owl.english.purdue.edu/).How to Write and Publish a Scientific Paper. Coursera. [*Link*](https://www.coursera.org/learn/how-to-write-a-scientific-paper) Toefl. edX. [*Link*](https://www.edx.org/course/toeflr-test-preparation-insiders-guide-etsx-toeflx).
    -   **Español**
        -   Fundamentos de la escritura. [Link](https://www.coursera.org/learn/escritura-esp).
        -   Fundamentos de la escritura académica. [*Link*](https://www.coursera.org/learn/escritura-academica-esp)*.*
        -   Redacción de documentos empresariales de gran impacto. [*Link*](https://www.coursera.org/learn/escritura-en-negocios).
        -   LEO. Universidad de los Andes. [*Link*](http://leo.uniandes.edu.co/index.php/escritura-sec-menu).
        -   Sexta edición del curso en línea «Corrección ortográfica: la puntuación». RAE. [*Link*](http://www.rae.es/noticias/sexta-edicion-del-curso-en-linea-correccion-ortografica-la-puntuacion).
        -   Curso Breve de Escritura Jurídica. Universidad de los Ándes. [*Link*](https://justicia.uniandes.edu.co/index.php/eventos/8-blog/16-escriturajuridica).
        -   Manual de escritura juridica. [*Link*](https://www.derechopenalenlared.com/libros/manual-de-escritura-juridica.pdf)

# Título

-   Existen al menos cinco formas de escribir un título: como resultado/conclusión, como objetivo, como hipótesis/explicación, como pregunta y como título de película.
-   The advantage of short paper titles. 2015. [*Link*](https://royalsocietypublishing.org/doi/10.1098/rsos.150266).
-   Do hyphens in article titles harm citation counts? 2019. [*Link*](https://www.cwts.nl/blog?article=n-r2x254). [*Link*](https://ieeexplore.ieee.org/document/8708940).
-   The 10 most common mistakes when choosing a title for your paper. [*Link*](https://www.annaclemens.com/blog/get-ask-academic-professional-development-funding).

# Resumen

-   How to construct a Nature summary paragraph. Nature. [*Link*](https://www.nature.com/documents/nature-summary-paragraph.pdf).

# Autoria

-   CRediT taxonomy. . [*Link*](https://www.cell.com/pb/assets/raw/shared/guidelines/CRediT-taxonomy.pdf).
-   Orcid. [Link](https://orcid.org/).
-   ResearcherID. [*Link*](https://www.researcherid.com/).
-   Google Académico. [*Link*](https://scholar.google.com/).
-   Guía para crear perfiles de autor. [*Link*](https://guiastematicas.bibliotecas.uc.cl/IP_academica/buenaspracticas/orcid).
-   Authorship issue explained. Indian J Plast Surg. 2010. [*Link*](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3010799/#).
-   The chaperone effect in scientific publishing. PNAS 2018. [*Link*](https://www.pnas.org/content/115/50/12603).
-   One mentor isn’t enough. Here’s how I built a network of mentors. [*Link*](https://www.sciencemag.org/careers/2021/03/one-mentor-isnt-enough-heres-how-i-built-network-mentors).

<https://youtu.be/o9LvfGFv1D4>

# Introducción

-   How To Choose a Good Scientific Problem. 2009. Molecular Cell. [*Link*](https://www.sciencedirect.com/science/article/pii/S1097276509006418).
-   De la teoría a los datos o de los datos a la teoría (aproximación deductiva vs inductiva).
    -   Ejemplo. Black holes and quantum information. [*Link*](https://asset-pdf.scinapse.io/prod/2998851352/2998851352.pdf).
-   Tema vs. temática. Problema vs problemática. [*Link*](https://fundeu.do/tematica-no-es-lo-mismo-que-tema/)
-   **Objetivo, hipótesis o pregunta.**
-   Causal assumptions and causal inference in ecological experiments. Tree, 2021. .
-   Causal Inference in R Workshop. [*Link*](https://github.com/malcolmbarrett/causal_inference_r_workshop).
-   **Hipotesis**
    -   When are hypotheses useful in ecology and evolution? Ecology and Evolution. 2021. [*Link*](https://onlinelibrary.wiley.com/doi/10.1002/ece3.7365).
-   **Preguntas**
    -   Finding a Good Research Question, in Theory. Science. 2012. [*Link*](https://www.science.org/doi/full/10.1126/science.335.6075.1439-a).
    -   Developing great research questions. AJHP 2008. [*Link*](https://doi.org/10.2146/ajhp070276).
    -   Setting a research question, aim and objective. Nurse Reesearcher. 2014. [*Link*](https://journals.rcni.com/nurse-researcher/setting-a-research-question-aim-and-objective-nr.23.4.19.s5).
-   **Escritura de objetivos**
-   **Prueba de redacción de objetivo** (forma)
    -   Las tres partes básicas de un buen objetivo, son: 1) la acción (verbo en infinitivo), 2) el objeto sobre el que recae la acción (sujeto) y 3) la descripción de la acción (a veces detalles)
    -   Ejemplo: 1) proveer 2) trabajos 3) en el sector industrial
-   **Prueba SMART** (fondo)
    -   SMART. [*Link*](https://www.dropbox.com/es/business/resources/smart-goals).
    -   Qué son los objetivos SMART. [*Link*](https://www.tableau.com/es-mx/learn/articles/smart-goals-criteria#:~:text=El%20m%C3%A9todo%20SMART%20afirma%20que,crear%20m%C3%A9tricas%20y%20metas%20concretas.).
    -   **S** pecific (específico) = variables independientes, dependientes y conceptos clave
    -   **M** easurable (medible) = producto, entregable, VD, VI
    -   **A** chievable (alcanzable) = ¿puedo lograrlo con mis recursos?)
    -   **R** elevant or **R** ealistic (realista) = ¿es útil?)
    -   **T** ime-bound (limitado en el tiempo) = cronograma y presupuesto
-   **Uso de verbos en objetivos**
    -   Taxonomía de Bloom. [*Link*](https://www3.gobiernodecanarias.org/medusa/edublog/cprofestenerifesur/2015/12/03/la-taxonomia-de-bloom-una-herramienta-imprescindible-para-ensenar-y-aprender/).

# Métodos

-   **Diseño experimental**
-   A manifesto for reproducible science. 2017. Nature Human Behaviour. [*Link*](http://www.nature.com/articles/s41562-016-0021).
-   Causal Inference: The Mixtape. [*Link*](https://mixtape.scunning.com/introduction.html).
-   Collection. Scientific Rigour and Reproducibility. [*Link.*](https://www.nature.com/collections/byblhcfwhw)
-   Verification, Validation, and Confirmation of Numerical Models in the Earth Sciences. Science. 1994. [*Link*](https://www.science.org/doi/10.1126/science.263.5147.641).
-   El agite. El gato y la caja. 2019. [*Link*](https://elgatoylacaja.com.ar/el-agite/).
-   Experimental Design Assistant. NC3R. [*Link*](https://eda.nc3rs.org.uk/).
-   How To Make Your Data Analysis Notebooks More Reproducible. [*Link*](https://github.com/karthik/rstudio2019).
-   Measurement error and the replication crisis. 2017. Science. [*Link*](http://science.sciencemag.org/content/355/6325/584.full?utm_source=sciencemagazine&utm_medium=facebook-text&utm_campaign=gelman-11067).
    -   ***P-value***
    -   The Proposal to Lower *P*  Value Thresholds to.005. Jama. [*Link*](https://jamanetwork.com/journals/jama/fullarticle/2676503).
    -   Scientists rise up against statistical significance. [*Link*](https://www.nature.com/articles/d41586-019-00857-9).
    -   Moving beyond *P*  values: data analysis with estimation graphics. [*Link*](https://www.nature.com/articles/s41592-019-0470-3).
    -   Science Forum: Ten common statistical mistakes to watch out for when writing or reviewing a manuscript. [*Link*](https://elifesciences.org/articles/48175).
    -   Collection. Interdisciplinary science. Nature. [*Link*](https://www.nature.com/news/interdisciplinarity-1.18295).
    -   Collection. Co-production of research. Nature. [*Link*](https://www.nature.com/collections/nnqkvntryl).
-   **FAIR Science** (findable, accessible, interoperable and reusable)
    -   Make scientific data FAIR. Nature 2019. [*Link*](https://www.nature.com/articles/d41586-019-01720-7#ref-CR2).
    -   The FAIR Guiding Principles for scientific data management and stewardship. [*Link*](https://www.nature.com/articles/sdata201618).
    -   Data management made simple. Nature. [*Link*](https://www.nature.com/articles/d41586-018-03071-1).
    -   Does your code stand up to scrutiny? Nature. [*Link*](https://www.nature.com/articles/d41586-018-02741-4).
    -   A call for clean code to effectively communicate science. [*Link*](https://besjournals.onlinelibrary.wiley.com/doi/10.1111/2041-210X.13961)
    -   Everyone needs a data-management plan. Nature. [*Link*](https://www.nature.com/articles/d41586-018-03065-z).
    -   Depositing and reporting of reagents: Accelerating open and reproducible science. [*Link*](https://blogs.plos.org/plos/2019/05/depositing-and-reporting-of-reagents-accelerating-open-and-reproducible-science/).
    -   Special Topics In Data Science: Reproducibility for Data Science\*\*\*. [*Link*](https://canvas.uw.edu/courses/1354201).
    -   Data Management Services. Stanford. [*Link*](https://library.stanford.edu/research/data-management-services)
        -   Best practices for file formats. [*Link*](https://library.stanford.edu/research/data-management-services/data-best-practices/best-practices-file-formats)
    -   Better Science through Better Data 2019 (#SciData19). [*Link*](https://figshare.com/collections/Better_Science_through_Better_Data_2019_SciData19_/4740722).
    -   Critiqued coronavirus simulation gets thumbs up from code-checking efforts. Nature. [*Link*](https://www.nature.com/articles/d41586-020-01685-y).
    -   Open science. Webinar Elsevier. [*Link*](https://www.brighttalk.com/service/player/en-US/theme/default/channel/15611/webcast/414950/play?showChannelList=true).
    -   UNESCO Open Science. [*Link*](https://www.unesco.org/en/natural-sciences/open-science).
    -   Data management and best practice for plant science. Nature. [*Link*](https://www.nature.com/articles/nplants201786).
    -   The Overlap Between FAIR for Research Software and Open Science. 2022. [*Link*](https://zenodo.org/record/6340732#.YlxRyJPMLx6)
    -   Open science, done wrong, will compound inequities. Nature 2022. [*Link*](https://www.nature.com/articles/d41586-022-00724-0).
    -   Introducing the FAIR Principles for research software. Scientific Data 2022. [*Link*](https://www.nature.com/articles/s41597-022-01710-x).
    -   Journal of Statistical Software. [*Link*](https://www.jstatsoft.org/index).
-   **Videos Fair Science**
    -   Science as Amateur Software Development. [*Link*](https://youtu.be/zwRdO9_GGhY?t=1).
    -   Leiden University Libraries & Elsevier Seminars on Reproducible Research. [*Link*](https://www.youtube.com/playlist?list=PL-vTxWFyVBpEllXo6thA8ZQ_OpYkThIfQ).

<https://youtu.be/nWaM6XmQEmU>

-   **Data Availability.**
    -   Nature. Data Availability Statements. .
    -   Figshare. [*Link*](https://figshare.com/).
    -   Dryad. [*Link.*](http://datadryad.org/)
    -   Zenodo. [*Link*](https://zenodo.org/).
    -   GitHub. [*Link*](https://github.com/).
    -   Colaboratory - Google. [*Link*](https://colab.research.google.com/notebooks/intro.ipynb).
    -   re3data. [*Link*](https://www.re3data.org/)
    -   Dataone. [*Link*](https://www.dataone.org/)
    -   Research Data Management and Sharing. Coursera. [*Link*](https://www.coursera.org/learn/data-management/home/welcome).
    -   University of Cambridge Research Data Management. [*Link*](https://www.data.cam.ac.uk/).
    -   Lista de repositorios.[*Link*](https://www.nature.com/sdata/policies/repositories). [*Link*](https://datamed.ucsd.edu/repository_list.php).
    -   The Wild World of Data Repositories. [*Link*](https://ropensci.org/commcalls/dec2020-datarepos/).
    -   Supercharge your research: a ten-week plan for open data science. Nature. [*Link*](https://www.nature.com/articles/d41586-019-03335-4?utm_source=twitter&utm_medium=social&utm_content=organic&utm_campaign=NGMT_2_JNC_Nature).
    -   Make code accessible with these cloud services. Nature. [*Link*](https://www.nature.com/articles/d41586-019-03366-x?utm_source=twitter&utm_medium=social&utm_content=organic&utm_campaign=NGMT_2_JNC_Nature).
    -   Data project checklist. [*Link*](https://www.fast.ai/2020/01/07/data-questionnaire/).
    -   Eleven tips for working with large data sets. Nature. [*Link*](https://www.nature.com/articles/d41586-020-00062-z).
-   **Articulos de ejemplo open science**
    -   Diversification insulates fisher catch. Science. [*Link*](https://advances.sciencemag.org/content/6/8/eaaz0587).

<https://vimeo.com/492310551>

<https://youtu.be/Y9uLH9cWitg?list=PL-vTxWFyVBpEllXo6thA8ZQ_OpYkThIfQ>

# Resultados. Figuras y Tablas

-   Rewriting results sections in the language of evidence. TREE. 2022. [*Link*](https://doi.org/10.1016/j.tree.2021.10.009).
-   Publishing Figures: Eight Tips for Achieving High-Quality Results A training resource of the ISMTE. [*Link*](https://slideplayer.com/slide/8087580/).
-   The Glamour of Graphics - William Chase. [*Link*](https://resources.rstudio.com/rstudio-conf-2020/the-glamour-of-graphics-william-chase).
-   Ten Simple Rules for Better Figures. PLoS. [*Link*](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003833).
-   Error bars in experimental biology. JBC. [*Link*](http://jcb.rupress.org/content/177/1/7).
-   Beyond Bar and Line Graphs: Time for a New Data Presentation Paradigm. PLoS. [*Link*](https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.1002128).
-   How can we make better graphs? An initiative to increase. Pharmaceutical Statistics. [*Link*](https://onlinelibrary.wiley.com/doi/full/10.1002/pst.1912).
-   Journal of Biogeography. Figures: the Art of Science. [*Link*](https://journalofbiogeographynews.org/2020/07/15/figures-the-art-of-science/).
-   Annual Reviews Graphics Guide. [*Link*](https://www.annualreviews.org/pb-assets/Authors%20Assets/AR-Graphics-Guide-1553624162667.pdf).
-   A protocol for conducting and presenting results of regression-type analyses. 2017. Methods in ecology and evolution. [*Link*](http://onlinelibrary.wiley.com/doi/10.1111/2041-210X.12577/abstract?wol1URL=/doi/10.1111/2041-210X.12577/abstract&regionCode=CO&identityKey=73d4045a-5635-4e82-b17f-04bbb0b75423).
-   Science–graphic art partnerships to increase research impact. Communications Biology, 2019. [*Link*](https://www.nature.com/articles/s42003-019-0516-1).
-   Algunos sitios de ejemplo para gráficas en R
    -   From data to viz. [*Link*](https://www.data-to-viz.com/).\*\*\*
    -   r-graph gallery. [*Link*](http://www.r-graph-gallery.com/).
    -   A Compendium of Clean Graphs in R. [*Link*](http://shinyapps.org/apps/RGraphCompendium/index.php).
    -   Fundamentals of Data Visualization. Claus O. Wilke. [*Link*](https://serialmentor.com/dataviz/).
    -   BBC Visual and Data Journalism cookbook for R graphics. [*Link*](https://bbc.github.io/rcookbook/).
-   **Tablas**
    -   R Data.table. [*Link*](https://github.com/Rdatatable/data.table).
    -   R gt package. [*Link*](https://gt.rstudio.com/)
    -   10+ Guidelines for Better Tables in R. [*Link*](https://themockup.blog/posts/2020-09-04-10-table-rules-in-r/).
-   **Mapas**
    -   NYTimes. Ejemplo. [*Link*](https://www.nytimes.com/interactive/2022/world/europe/ukraine-maps.html).
-   **Ilustración científica**
    -   Visualizing Science: Illustration and Beyond. Scientific American. [*Link*](https://blogs.scientificamerican.com/sa-visual/visualizing-science-illustration-and-beyond/).
    -   A microbiome silver bullet for honey bees. Science. [*Link*](https://science.sciencemag.org/content/367/6477/504/tab-figures-data)
    -   OUR FAVORITE SCIENCE ILLUSTRATIONS OF 2019. Science. [*Link*](https://vis.sciencemag.org/illustrationsof2019/).
    -   The Guild Handbook of Scientific Illustration. [*Link*](https://books.google.com.co/books?id=hF3IDwAAQBAJ&printsec=frontcover&hl=es&source=gbs_ge_summary_r&cad=0#v=onepage&q&f=false)
    -   The Science Book: Big Ideas Simply Explained. [*Link*](https://books.google.com.co/books?id=Z4eKBgAAQBAJ&printsec=frontcover&dq=The+Science+Book:+Big+Ideas+Simply+Explained&hl=es&sa=X&ved=0ahUKEwiLu9Tp08PoAhUySN8KHTA4CE8Q6AEIKjAA#v=onepage&q=The%20Science%20Book%3A%20Big%20Ideas%20Simply%20Explained&f=false).
    -   Preparing Scientific Illustrations. Springer. [*Link*](https://www.springer.com/gp/book/9780387945811).
    -   GNSI. [*Link*](https://www.gnsi.org/). Charla. [*Link*](https://www.facebook.com/gnsiart/videos/2161928834078467/).
-   **Infografías**
    -   Infografías: El poder del storytelling visual. [*Link*](https://books.google.com.co/books?id=vB7UurQuCBwC&printsec=frontcover&dq=Infographic+Design:+Visual+Storytelling+With+Information+and+Data&hl=es-419&sa=X&ved=2ahUKEwjWqMXFvqH3AhWDRjABHQiMC8MQ6AF6BAgLEAI#v=onepage&q&f=false).
-   **Recursos para ilustración y figuras**
    -   Mind the graph. [*Link*](https://mindthegraph.com/).
    -   Biorender. [*Link*](https://biorender.com/).
    -   Biocoins. [*Link*](https://bioicons.com/)*.*
    -   Reactome. [*Link*](https://reactome.org/icon-lib)
    -   The noun project. [*Link*](https://thenounproject.com/).
    -   Health icons. [*Link*](https://healthicons.org/).
    -   SVGrepo SVG Vectors and Icons. [*Link.*](https://www.svgrepo.com/)
    -   **Bancos de imagenes abiertos**
        -   Pixabay. [*Link*](https://pixabay.com/es/).
        -   Unplash. [*Link*](https://unsplash.com/es).
        -   Freepik. [*Link*](https://www.freepik.es/).
        -   Pexels. [*Link*](https://www.pexels.com/es-es/).
    -   Iconos.
        -   Iconduck. [*Link*](https://iconduck.com/).
        -   SVG Repo. [*Link*](https://www.svgrepo.com/).
    -   Diagram.net. [*Link*](https://app.diagrams.net/).
-   **Software**
    -   Figma. [*Link*](https://www.figma.com/)
    -   Inkscape. [*Link*](https://inkscape.org/es/).
-   <https://youtu.be/3IuoK07YDds>

# Discusión, Conclusiones

# Agradecimientos

-   Ver manuales de estilo.
-   Funder registry. [Link](https://www.crossref.org/services/funder-registry/).

# Selección de revista para publicación

-   **Herramientas**
    -   Wiley find a journal. .
    -   Elsevier Journal Finder. [*Link*](http://journalfinder.elsevier.com/)*.*
-   **Ranking de revistas**
    -   Scimago Journal Rank. [*Link*](http://www.scimagojr.com/).
    -   The Eigenfactor Metrics. [*Link*](http://www.eigenfactor.org/).
    -   CiteScore. [*Link*](https://www.scopus.com/sources).
    -   Journal Citation Reports. [*Link*](https://clarivate.com/webofsciencegroup/solutions/journal-citation-reports/).
    -   CWTS Leiden Ranking. [*Link*](http://www.leidenranking.com/).
    -   Journal Scholar Metrics. [*Link*](http://www.journal-scholar-metrics.infoec3.es/layout.php?id=home)*.*
    -   Nature Index. [*Link*](http://www.natureindex.com/).
    -   Citation Performance Indicators — A Very Short Introduction. [*Link*](https://scholarlykitchen.sspnet.org/2017/05/15/citation-performance-indicators-short-introduction/).
-   **Preprints**
    -   Ten simple rules to consider regarding preprint submission. PLoS. [*Link*](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005473).Preprint servers facilitate scientific discourse. PNAS. 2017. [*Link*](http://www.pnas.org/content/114/48/12630.full).
    -   Wiley’s Preprints Policy. .
-   **Lista de servidores de preprints [*Link*](https://en.wikipedia.org/wiki/List_of_preprint_repositories)**
    -   bioRxiv. [*Link*](https://www.biorxiv.org/).
    -   arXiv. [*Link*](https://arxiv.org/).
    -   Preprints. [*Link*](https://www.preprints.org/).
    -   Research Square. [*Link*](https://www.researchsquare.com/).
    -   Scielo preprints. [*Link*](https://preprints.scielo.org/index.php/scielo).
-   **Predatory Publishers**.
    -   Predatory publishers are corrupting open access. Nature. 2012. [*Link.*](http://www.nature.com/news/predatory-publishers-are-corrupting-open-access-1.11385)
-   **Controversia del acceso abierto**
    -   Pay Wall The Movie. [*Link*](https://paywallthemovie.com/).

<https://www.youtube.com/watch?v=zAzTR8eq20k>

# Envío del artículo

## **Cómo escribir un *cover letter***

-   Crafting cover letters. Nature Geoscience. [*Link*](https://www.nature.com/articles/s41561-021-00824-y).
-   How to write a cover letter. Nature. [*Link*](http://blogs.nature.com/methagora/2013/09/how-to-write-a-cover-letter.html).
-   Initial submission Nature journals. .
-   Writing a winning cover letter. Science. [*Link*](http://www.sciencemag.org/careers/2014/08/writing-winning-cover-letter).
-   Why has submitting a manuscript to a journal become so difficult? A call to simplify an overly complicated process. [*Link*](http://blogs.lse.ac.uk/impactofsocialsciences/2017/05/10/why-has-submitting-a-manuscript-to-a-journal-become-so-difficult-a-call-to-simplify-an-overly-complicated-process/).

# Revisión por pares

::: {.callout-note appearance="simple"}
## Busqueda de pares

-   Tools for finding reviewers and how to use them. SAGE. [*Link*](https://us.sagepub.com/en-us/sam/tools-for-finding-reviewers-and-how-to-use-them)
-   How to find peer reviewers - an editor's guide. [*Link*](https://editorresources.taylorandfrancis.com/managing-peer-review-process/how-to-find-peer-reviewers-an-editors-guide/)
-   Finding Peer Reviewers. BMC. [*Link*](https://www.biomedcentral.com/about/foreditors/manuscript-handling-information/selecting-peer-reviewers)
-   Búsqueda de pares en Colombia por CvLac. [*Link*](https://scienti.minciencias.gov.co/ciencia-war/jsp/enRecurso/IndexRecursoHumanoBusquedaTematica.jsp).
:::

-   Nature master classes. Focus on Peer Review. [*Link*](https://masterclasses.nature.com/focus-on-peer-review-online-course/16605550)
-   Editing of reviewer comments: Forum discussion topic March 2020. [*Link*](https://publicationethics.org/editing-reviewer-comments-forum-discussion-topic-march-2020).
-   Cases in publication ethics. [*Link*](https://publicationethics.org/cases).
-   How small changes to a paper can help to smooth the review process. Nature. [*Link*](https://www.nature.com/articles/d41586-019-01431-z).
-   How not to respond to reviewers: Eight simple tips. Nature. 2016 [*Link*](http://blogs.nature.com/naturejobs/2016/08/19/how-not-to-respond-to-reviewers-eight-simple-tips/).
-   Let’s make peer review scientific. [*Link*](http://www.nature.com/news/let-s-make-peer-review-scientific-1.20194?WT.ec_id=NATURE-20160707&spMailingID=51772103&spUserID=MjA1NTkxOTIzMgS2&spJobID=960792730&spReportId=OTYwNzkyNzMwS0)*.*
-   Publons. Track your research impact. [*Link*](https://publons.com/).
-   The Importance of Quality Control in Medical Writing. [*Link*](http://blog.amwa.org/the-importance-of-quality-control-in-medical-writing).
-   Ten simple rules for writing a response to reviewers. [*Link*](http://journals.plos.org/ploscompbiol/article?id=10.1371%2Fjournal.pcbi.1005730).
-   What is the future of peer review in ecology?[*Link*](http://www.britishecologicalsociety.org/video-future-peer-review-ecology/?platform=hootsuite)*.*
-   What Makes a Good Peer Review: Peer Review Week 2016. [*Link*](https://methodsblog.com/2016/09/20/what-makes-a-good-review/amp/?__twitter_impression=true).
-   *Cómo realizar una revisión por pares. [Enlace](https://docs.google.com/presentation/d/1z6SFEyqb2-qjMKYR7Z_t6wslYGetKG_LqG0tlyxPjIU/edit?usp=sharing)*

::: {layout-ncol="2"}
{{< video "https://youtu.be/HJYB1IaS598" >}} COPE. Artificial intelligence and peer review

{{< video "https://youtu.be/C0cchYD9hpY" >}} How to master peer review

{{< video "https://youtu.be/x1H3bG-HNX0" >}} Peer Reviewer Training – How to Get Published EURAXESS

Revisión por pares
:::

# Post-publicación y divulgación

-   **Twitter**
    -   Twitter for Scientists. [*Link*](https://t4scientists.com/)
    -   10 tips for tweeting research. Nature. [*Link*](https://www.natureindex.com/news-blog/ten-tips-tweeting-research-academic).
    -   How academics should use Twitter. [*Link*](https://www.natureindex.com/news-blog/how-academics-should-use-twitter-social-media).
    -   For scientists skittish about Twitter, here's a plan. [*Link*](https://www.natureindex.com/news-blog/why-scientists-are-reluctant-to-tweet-plan).
    -   On Birds, Twitter and Teaching. NYTimes. [*Link*](https://dotearth.blogs.nytimes.com/2011/05/05/on-birds-twitter-and-teaching/).
    -   The role of Twitter in the life cycle of a scientific publication. PeerJ. [*Link*](https://peerj.com/preprints/16/).
    -   The top 50 science stars of Twitter. Science 2018. [*Link*](http://www.sciencemag.org/news/2014/09/top-50-science-stars-twitter).
    -   La influencia de Twitter sobre el impacto de tus artículos científicos. [*Link*](https://francis.naukas.com/2019/04/22/la-influencia-de-twitter-sobre-el-impacto-de-tus-articulos-cientificos/).
    -   The Kardashian index: a measure of discrepant social media profile for scientists. [*Link*](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-014-0424-0).
-   **Periodismo científico**
    -   Sección de ciencia NY Times. [*Link*](https://www.nytimes.com/video/science).
        -   Ejemplo NY Times. [*Link*](https://www.nytimes.com/2017/05/15/health/pesticides-epa-chlorpyrifos-scott-pruitt.html)
    -   Sección de ciencia El Pais de España. [*Link*](https://elpais.com/elpais/ciencia.html).
    -   Science journalism can be evidence-based, compelling — and wrong. 2017. Nature. [*Link*](http://www.nature.com/news/science-journalism-can-be-evidence-based-compelling-and-wrong-1.21591?WT.mc_id=TWT_NatureNews).
-   **Lecturas en comunicación científica**
    -   Evaluating big deal journal bundles. [*Link*](http://www.pnas.org/content/111/26/9425.abstract).
    -   Fewer numbers, better science. Nature. 2016. [*Link*](http://www.nature.com/news/fewer-numbers-better-science-1.20858?WT.mc_id=TWT_NatureNews).
    -   Higgs would not find his boson in today's 'publish or perish' research culture. The Guardian. 2016. [*Link*](https://www.theguardian.com/commentisfree/2014/feb/14/higgs-boson-publish-or-perish-science-culture?CMP=share_btn_tw).
    -   Languages Are Still a Major Barrier to Global Science. Plos Biology. 2016. [*Link*](http://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.2000933).
    -   Demasiados papers. El Pais. [*Link*](https://elpais.com/elpais/2019/02/18/ciencia/1550484222_682428.html).
-   **Publicar en la web.**
    -   Gitbooks. [*Link*](https://www.gitbook.com/). Ejemplos [*Link*](https://universidad-de-los-andes.gitbooks.io/). [*Link*](https://volaya.github.io/libro-sig/index.html).
    -   R-Markdown. [*Link*](https://rmarkdown.rstudio.com/).
-   **Actividades post-publicación ([*Link*](https://youtu.be/k1pKfD_B9Rw))**
    -   Nature authors tips for promoting your research. .
    -   Wiley Editing Services. Extend the reach and impact of your research. [*Link*](https://wileyeditingservices.com/en/article-promotion/).
-   **Lista de actividades**
-   **Comparta su trabajo en sus redes sociales**
    -   Publique su trabajo en redes sociales como Twitter, Facebook y otras redes. Comparta el enlace a su capítulo, emplee hashtags relevantes para su tema y etiquete a los coautores.
    -   También se recomienda hacerlo en los grupos de Whatsapp y similares.
-   **Actualice su perfil profesional**
    -   Resalte este logro profesional actualizando su perfil de LinkedIn, página web personal, hoja de vida del servidor público, CvLAC o similares.
-   **Utilice plataformas de intercambio de investigaciones**
    -   Cree o actualice su perfil de Google Académico para seguir las citas de su publicación y visibilizar su nombre en los resultados de búsqueda de Google Académico.
    -   También actualice perfiles de investigador en Orcid, ResearchGate, Mendeley, Academia.edu, Loop y en sociedades científicas.
-   **Si cuenta con un blog resalte los puntos clave de su trabajo.**
    -   Los blogs pueden ser una herramienta útil para explicar o ampliar su investigación para un público más general. Si mantiene un blog personal o contribuye a un blog en su campo, considere escribir una entrada sobre su capítulo.
-   **Videos**
    -   Los videos son cada vez más populares para compartir información e ideas. En un video de YouTube podría resumir el alcance y hallazgos clave de su capítulo, como también podría proporcionar más detalles sobre su investigación y métodos.
-   **Haga que los resultados de su investigación se puedan compartir y descubrir**
    -   Puede optar por depositar los datos de investigación en repositorios de datos científicos. Al hacer que los datos de su investigación estén disponibles, puede ayudar a promover su publicación y fomentar las citas.
    -   Una lista de repositorios es: <https://www.nature.com/sdata/policies/repositories>
-   **Promocione su trabajo dentro de su institución**
    -   Comparta su trabajo con sus colegas cercanos, emplee el capítulo como material de clase con sus estudiantes, y fomente su uso en su red profesional para que se emplee como fuente de estudio o de referencia.
-   **Comunique su trabajo como un artículo divulgativo**
    -   Comparta el valor de su investigación a través de un artículo divulgativo. Puede contactar un periodista científico que le ayude a conectar lo conceptual con lo práctico para hacer que su investigación sea comprensible para una audiencia general.
    -   Su oficina de prensa o el periodista científico puede ayudarle a encontrar un titular y una imagen que llamen la atención de su capítulo.
    -   Intente publicar el artículo divulgativo en periódicos nacionales, portales de noticias, comunicados de prensa, blog, o en boletines.
-   **Creación de infografías**
    -   Comunicar visualmente su investigación en una infografía atractiva y compartirla por redes sociales puede resumir su investigación de una manera comprensible para una audiencia general.
    -   Venngage. [*Link*](https://es.venngage.com/).

"Publishing in Academic Journals" - Part of How to Get Published EURAXESS webinar series. [*Enlace*](https://euraxess.ec.europa.eu/worldwide/north-america/publishing-academic-journals-part-how-get-published-euraxess-webinar)

# Ética en la publicación

-   OSTP Advancing New Scientific Integrity Principles. [*Link*](https://www.aip.org/fyi/2022/ostp-advancing-new-scientific-integrity-principles).
-   Systematic manipulation of the publication process. COPE. [*Link*](https://doi.org/10.24318/cope.2019.2.23)
-   **Controversias éticas**
    -   Consent to publish identifiable information (including Acknowledgements)
    -   Data or image fabrication/falsification or "massaging" (e.g., p-hacking, HARKing)
    -   Data sharing (ignoring FAIR principles; inappropriate sharing of sensitive data)
    -   Duplicate submission/publication
    -   Hoax submissions
    -   Inadequate/selective reporting of research (irreproducible research and bias)
    -   Inappropriate references/poor attribution
    -   Journal IF "shopping"
    -   Papermills
    -   Peer review manipulation or bias Plagiarism (ideas as well as text)
    -   Propaganda disguised as scholarly work
    -   Text recycling /redundant publication
    -   Unethical research (e.g., vulnerable groups, lack of consent, handling of animals etc-)

**Para editores**

-   Currículo del editor. Minciencias. [*Link*](https://minciencias.gov.co/content/curriculo-del-editor).
-   Cómo cargar libros a Google Books. [*Link*](https://support.google.com/books/partner/answer/107073?hl=en).
-   El Escándalo Sokal. [*Link*](https://es.m.wikipedia.org/wiki/Esc%C3%A1ndalo_Sokal).
-   Alternativas a OJS.[*Link*](https://paideiastudio.net/alternativas-a-ojs-6-opciones).
-   The Beginning of the End of Publisher-Society Partner Contracts. 2022. [*Link*](https://scholarlykitchen.sspnet.org/2022/10/24/the-beginning-of-the-end-of-publisher-society-partner-contracts/).
-   The Rapid Growth of Mega-Journals. Threats and Opportunities. JAMA. 2023. [*Link*](https://jamanetwork.com/journals/jama/fullarticle/2802853).
-   Editor workshop Coalition for Publishing Data in the Earth and Space Sciences. [*Link*](https://copdess.org/editor-workshop-webinar-series/)
    -   The Intersection of the Data Repository and Journal Workflow — Coordination of Data Preservation with the Paper Peer-Review Process.
    -   Overview of the Software Citation Guidance for Authors and Journals by the FORCE11 Software Citation Implementation Working Group
    -   Rubric for Models and Model Data — Best Practices for Preservation and Replicability

**Posters y diapositivas**

-   Ten simple rules for effective presentation slides. PloS. *Link*.
-   Template here: [https://osf.io/ef53g](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqa05tRFNadjJTeDJUZ1F4Ri0wMkxNZzN2Tmtod3xBQ3Jtc0ttdnhEcXJCQ2Y4UGoya1dGM0FhVmk3YW5hdHJMRno5MUdaVFZKTXphZlNjZGl4ZnRMU1VlSjRPQ2J1SndZTlNLVllseFIzckd6T0R0c2hiR2lGcU5CRHFoTUdrWEZDdG5fbW01VGItQlNOQnZPM3RvTQ&q=https%3A%2F%2Fosf.io%2Fef53g%2F)

How to create a better research poster in less time

**Charlas**

Cómo parecer inteligente en tu charla TEDx

### #Otros temas en publicación académica

-   **Lecturas redacción científica**
    -   Artículos científicos: mientras más narrativos, más citados. ScieDevNet. [*Link*](http://m.scidev.net/america-latina/comunicacion/noticias/articulos-cientificos-mientras-mas-narrativos-mas-citados.html) Challenge the impact factor. Nature Biomedical Engineering. 2017. [*Link*](https://www.nature.com/articles/s41551-017-0103).English Communication for Scientists. Unit 2: Writing Scientific Papers Scitable. [*Link*](http://www.nature.com/scitable/ebooks/english-communication-for-scientists-14053993/118519636#bookContentViewAreaDivID).Novelist Cormac McCarthy’s tips on how to write a great science paper. Nature 2018. [*Link*](https://www.nature.com/articles/d41586-019-02918-5).The British Ecological Society Short Guide to Scientific Writing. [*Link*](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)1365-2664/journal-resources/guide-to-scientific-writing.html?platform=hootsuite).Tips. [*Link*](https://dynamicecology.wordpress.com/2018/08/27/put-your-take-home-message-at-the-top-of-your-slides/amp/?__twitter_impression=true). [*Link*](http://journals.sagepub.com/doi/full/10.1177/1075547018781917). [*Link*](https://dynamicecology.wordpress.com/2018/03/05/when-writing-tell-us-your-biological-results/).Science Writing: Some Tips for Beginners. Science. 2005. [*Link*](http://www.sciencemag.org/careers/2005/05/science-writing-some-tips-beginners)*.*Scientific writing: A very short cheat sheet. Nature 2016. [*Link*](http://blogs.nature.com/naturejobs/2016/10/28/scientific-writing-a-very-short-cheat-sheet/).
    -   Starting a Career in Science Writing. Science. 2005. [*Link*](http://www.sciencemag.org/careers/2005/05/starting-career-science-writing).
    -   The 1-hour workday. Science. 2016. [*Link*](http://science.sciencemag.org/content/353/6300/718).
    -   The pressure to publish pushes down quality. [*Link*](http://www.nature.com/news/the-pressure-to-publish-pushes-down-quality-1.19887?WT.ec_id=NATURE-20160512&spMailingID=51353744&spUserID=MjA1NjE1MDUwMQS2&spJobID=921389953&spReportId=OTIxMzg5OTUzS0)*.*
    -   What Types of Medical Writing Are There?. [*Link*](http://blog.amwa.org/what-types-of-medical-writing-are-there).
    -   You do not need to work 80 hours a week to succeed in academia. Times Higher Education. 2015. [*Link*](https://www.timeshighereducation.com/blog/you-do-not-need-work-80-hours-week-succeed-academia).
    -   Hablar es un instinto, escribir un arte. 2020. [Link](https://www.letraslibres.com/espana-mexico/ciencia-y-tecnologia/hablar-es-un-instinto-escribir-un-arte).
    -   Editorial—A plea for scholarly writing. [*Link*](https://doi.org/10.1093/icb/icn072).
-   **Política científica**
    -   The developing world needs more than numbers. Nature 2017. [*Link*](http://www.nature.com/news/the-developing-world-needs-more-than-numbers-1.21395?WT.ec_id=NATURE-20170202&spMailingID=53329754&spUserID=MjA1NjE1MDUwMQS2&spJobID=1100183226&spReportId=MTEwMDE4MzIyNgS2).
    -   Publindex. Unal Radio. [*Link*](http://unradio.unal.edu.co/nc/detalle/cat/un-analisis/article/publindex.html).
-   **Presentación en público**
    -   How I conquered my fear of public speaking and learned to give effective presentations. Science. [*Link*](https://www.sciencemag.org/careers/2019/08/how-i-conquered-my-fear-public-speaking-and-learned-give-effective-presentations).
    -   Efecto Dunning-Kruger. [*Link*](https://es.wikipedia.org/wiki/Efecto_Dunning-Kruger)*.*
    -   Sindrome del impostor. [*Link*](https://es.wikipedia.org/wiki/S%C3%ADndrome_del_impostor). [*Link*](https://www.forbes.com/sites/ashleystahl/2017/12/10/feel-like-a-fraud-heres-how-to-overcome-imposter-syndrome/#17a2efdd4d31). [*Link*](https://www.theguardian.com/commentisfree/2017/sep/19/fraud-impostor-syndrome-confidence-self-esteem).
        -   Test. [*Link*](http://impostortest.nickol.as/).
        -   Imposter Syndrome Treat the Cause, Not the Symptom. JAMA. 2019. [*Link*](https://jamanetwork.com/journals/jama/fullarticle/2740724).
    -   Think Well. [*Link*](https://www.ithinkwell.com.au/research).
    -   PechaKucha. [*Link*](https://es.wikipedia.org/wiki/PechaKucha).
-   **Revistas científicas colombianas**
    -   Videos. Conversatorio Ciencia UdeA. 2017. [*Link*](http://original.livestream.com/udeasala2/video?clipId=pla_4e69c2cf-8b0d-46ac-948a-066dd03b99e7). [*Link*](http://original.livestream.com/udeasala2/video?clipId=pla_1c5912cb-cc6d-4a41-8746-7dff385dcda5&utm_source=lslibrary&utm_medium=ui-thumb).
    -   UN-Radio. Publindex. [*Link*](http://unradio.unal.edu.co/nc/detalle/cat/un-analisis/article/publindex.html)*. [Link](http://unradio.unal.edu.co/nc/detalle/cat/hipotesis/article/publindex-1.html).*
    -   Contribución a la evaluación del modelo Publindex de Colciencias. [*Link*](https://www.youtube.com/watch?v=pNyyvdtM6ag).
    -   Artículos revistas revista ASUC. 2019. [*Link*](http://aseuc.org.co/unilibros/uflip/Unilibros-de-Colombia-26-2019/page_18.html).
-   **Tendencias en publicación académica**
    -   Megajournals. [*Link*](http://blogs.springeropen.com/springeropen/2016/06/13/a-few-words-on-sound-science-megajournals-and-an-announcement-about-springerplus/).
    -   Tag Publishing at Nature Journal. [*Link*](http://www.nature.com/nature/archive/subject.html?code=479).
    -   Beat it, impact factor! Publishing elite turns against controversial metric. Nature. 2016. [*Link*](https://www.nature.com/news/beat-it-impact-factor-publishing-elite-turns-against-controversial-metric-1.20224).
    -   Revistas Académicas Latinoamericanas. Isidro Aguillo. Fundación Konrad Lorenz 2019. [*Link*](https://youtu.be/2u9gdpSM4iI).
    -   Science Editor. [*Link.*](https://www.csescienceeditor.org/issue/fall-2019-%e2%80%a2-vol-42-no-3/)
    -   A proposal for the future of scientific publishing in the life sciences. PloS. [*Link*](https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.3000116).
-   **Procastinar**
    -   Procrastinar no es un asunto de holgazanería, sino de manejo de las emociones. NYTimes. [*Link*](https://www.nytimes.com/es/2019/03/26/como-evitar-la-procrastinacion/).
-   **Organización de eventos** - **Congresos**
    -   Swapcard. [*Link*](http://app.swapcard.com/).Open Conference Systems. [*Link*](https://pkp.sfu.ca/ocs/).Event Managment System Indico. [*Link*](https://sandbox.getindico.io/).
    -   Conference app. Event Pilot. [*Link*](https://ativsoftware.com/).
    -   Hopin. [*Link*](https://hopin.com/).
    -   Attendify. [*Link*](https://attendify.com/).
    -   Accelevents. [*Link*](https://www.accelevents.com/).
    -   Whova. [*Link*](https://whova.com/)
    -   Peewah. [*Link*](https://peewah.co/)
    -   Bizzabo. [*Link*](https://www.bizzabo.com/pricing#broadcast)
    -   17 Conference Apps to Improve the Attendee Experience. [*Link*](https://memberclicks.com/blog/conference-app/)
    -   Agenda
        -   Ejemplo de agenda en Calendario Gmail. [*Link*](https://calendar.google.com/calendar/u/0/embed?height=650&wkst=1&bgcolor=%23ffffff&ctz=America/Bogota&mode=AGENDA&&dates=20220627/20220629&showTitle=0&showNav=0&showDate=0&showPrint=1&showTabs=1&showCalendars=1&showTz=1&src=Y19wdmY2Y3FibjRlcWw0ZHMyMG1tbWpkbmZpNEBncm91cC5jYWxlbmRhci5nb29nbGUuY29t&color=%23A79B8E). [*Como*](https://help.edublogs.org/embed-google-calendar-page/).
-   **Cómo construir un MOOC.**
    -   Eduvolución. [*Link*](https://eduvolucion.com/index.html).
    -   Making a MOOC. [*Link*](https://harvardx.harvard.edu/blog/making-mooc).
    -   The MOOC pivot. Science. [*Link*](http://science.sciencemag.org/content/363/6423/130.summary).
-   **Películas temas científicos**
    -   Particle fever. [*Link*](https://www.youtube.com/watch?v=Rikc7foqvRI).
    -   Chasing coral. [*Link*](http://www.chasingcoral.com/).
-   **Diagramación, diseño**
    -   The design decisions behind *Nature* ’s new look.[*Link*](https://www.nature.com/articles/d41586-019-03083-5).
-   **Ilustración**
    -   Visualizing Science: Illustration and Beyond. [*Link*](https://blogs.scientificamerican.com/sa-visual/visualizing-science-illustration-and-beyond/).

Isidro Aguillo - Revistas Académicas Latinoamericanas. Conferencia en Universidad Konrad Lorenz 2019

-   [**Ten simple rules series**](https://journals.plos.org/ploscompbiol/search?filterJournals=PLoSCompBiol&q=Ten+simple%20rules%20&page=1) [**PLoS**](https://journals.plos.org/ploscompbiol/search?filterJournals=PLoSCompBiol&q=Ten+simple%20rules%20&page=1)
    -   Ten Simple Rules for Writing a PLOS Ten Simple Rules Article. [*Link*](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003858).
    -   Ten Simple Rules for Reviewers. [*Link*](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.0020110).
    -   Ten simple rules for responsible referencing. [*Link*](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1006036).
    -   Ten simple rules for structuring papers. [*Link*](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005619).
    -   Ten Simple Rules for Experiments? Provenance. [*Link*](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1004384).
    -   Ten Simple Rules for Better Figures. [*Link*](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003833).
    -   Ten Simple Rules for a Successful Collaboration. [Link](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.0030044).
    -   Ten Simple Rules for Getting Published. [*Link*](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.0010057).
    -   Ten simple rules for writing a response to reviewers. [*Link*](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005730).
    -   Ten simple rules for scientists: Improving your writing productivity. [*Link*](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1006379).

# Diapositivas

-   Slidev. [*Link*](https://www.producthunt.com/posts/slidev).

# **Otras lecturas**

-   Cass Sunstein, el arquitecto de las decisiones. El Pais. 2017. [*Link*](http://elpaissemanal.elpais.com/confidencias/cass-sunstein/)*. [Link](https://scholar.google.com/citations?user=ddq2_gkAAAAJ&hl=es&oi=sra)*.
-   How Chronic Fatigue Syndrome Affects Your Metabolism. Psmag. [*Link*](https://psmag.com/how-chronic-fatigue-syndrome-affects-your-metabolism-f4682f9d1b67#.nkcbhflls).
-   Reducing cognitive load. [*Link*](https://drk-lo.github.io/lotterhoslabprotocols/ReducingCognitiveLoad/)
-   The state of the nation starts in your street. The Conversation. 2017. [*Link*](https://theconversation.com/hugh-mackay-the-state-of-the-nation-starts-in-your-street-72264?utm_medium=email&utm_campaign=Latest%20from%20The%20Conversation%20for%20February%202%202017%20-%206661&utm_content=Latest%20from%20The%20Conversation%20for%20February%202%202017%20-%206661+CID_12897e0ff5d26b0f332db2b898153bd5&utm_source=campaign_monitor&utm_term=Hugh%20Mackay%20the%20state%20of%20the%20nation%20starts%20in%20your%20street).
-   Taking distrust of science seriously. EMBO Reports. 2017. [*Link*](http://embor.embopress.org/content/early/2017/05/30/embr.201744294.full).
-   Workplace habits: Full-time is full enough. Some scientists are fighting a toxic belief that a 50-hour working week is 'slacking off'. [*Link*](http://www.nature.com/nature/journal/v546/n7656/full/nj7656-175a.html?WT.mc_id=TWT_NatureNews&sf84131996=1).
-   We need a science of philanthropy. Nature. 2017. [*Link*](http://www.nature.com/news/we-need-a-science-of-philanthropy-1.22100?WT.mc_id=TWT_NatureNews&sf86800362=1).
-   WORKING LIFE. A retirement ‘hobby’. 2017. Science. [*Link*](http://science.sciencemag.org/content/355/6324/542.full?utm_source=sciencemagazine&utm_medium=facebook-text&utm_campaign=6324workinglife-10896).
-   The Rise of the Scientist-Bureaucrat. Survival Guide for Researchers in the 21st Century. [*Link*](https://link.springer.com/book/10.1007/978-3-030-12326-0).

## **Cursos de actualización profesional**

-   George Mason University. Smithsonian Conservation Biology Institute. [*Link*](http://smconservation.gmu.edu/).
-   IELTS Academic Test Preparation. Edx. [*Link*](https://www.edx.org/course/ielts-academic-test-preparation-uqx-ieltsx-0).

## **Asociaciones profesionales**

-   The National Association of Science Writers. [*Link*](https://www.nasw.org/).

## **Varios** - Utilidades en Word

-   Construir tabla de contenido en Word para documento con capítulos. [*Link*.](https://support.office.com/en-us/article/Add-chapter-numbers-to-captions-in-Word-76aa8706-3453-4a72-ad5c-b87d90ce1698)
-   Creación y actualización de índices. [*Link*](https://support.office.com/es-es/article/creaci%C3%B3n-y-actualizaci%C3%B3n-de-%C3%ADndices-cc502c71-a605-41fd-9a02-cda9d14bf073).

## **Ciencia y política**

-   Cuatro motivos por los que hacen falta más científicos en política. [*Link*](http://www.huffingtonpost.es/manuel-souto/cuatro-motivos-por-los-qu_b_11718424.html).
-   Expect knowledge. [*Link.*](http://www.nature.com/news/expect-knowledge-1.19771?WT.ec_id=NATURE-20160421&spMailingID=51196306&spUserID=MjA1NjE1MDUwMQS2&spJobID=902556060&spReportId=OTAyNTU2MDYwS0)
-   If you want to win the game, you must join in. [*Link.*](http://www.nature.com/news/if-you-want-to-win-the-game-you-must-join-in-1.9580)
-   Ninguna comunidad ancestral y milenaria conoce más sobre cáncer que la medicina moderna. Periódico UNAL. [*Link*](https://unperiodico.unal.edu.co/pages/detail/ninguna-comunidad-ancestral-y-milenaria-conoce-mas-sobre-cancer-que-la-medicina-moderna/).

## **Ciencia en Colombia**

-   Scienti - Colciencias. [*Link*](http://www.colciencias.gov.co/scienti)
-   Observatorio colombiano de ciencia y tecnología. [*Link*](http://ocyt.org.co/es-es/)
    -   Informe Anual de Indicadores de Ciencia y Tecnología 2018. [*Link*](http://www.ocyt.org.co/proyectos-y-productos/informe-anual-de-indicadores-de-ciencia-y-tecnologia-2018/).
-   DNP, SGR. Ciencia, Tecnología e Innovación. [Link](https://www.sgr.gov.co/Inversi%C3%B3n/CienciaTecnolog%C3%ADaeInnovaci%C3%B3n.aspx).

## **Podcast en ciencia**

-   Hablemos de física. UNradio. [*Link*](http://unradio.unal.edu.co/nc/detalle/cat/hablemos-de-fisica.html).
-   Hipótesis. UNradio. [*Link*](http://unradio.unal.edu.co/nc/detalle/cat/hipotesis/article/extension-facultad-de-ciencias.html).
-   Investigación de impacto. U Javeriana. [*Link*](http://www.javeriana.edu.co/javerianaestereo/podcast/index.php?cat=InvestigacindeImpacto).
-   Metacampus. Universidad Nacional. [*Link*](http://metacampus.unal.edu.co/index.php?id=118&no_cache=1).

## **Cómo funciona la ciencia, el método científico**

-   *Preguntas, ecuaciones, cálculos, experimento, teoría, leyes y principios*. Boltzmann and the Arrow of Time: A Recent Perspective. [*Link*](https://www.cornell.edu/video/leonard-susskind-1-boltzmann-and-the-arrow-of-time/s417).