---
title: "Cafés especiales"
format: html
editor: visual
---

------------------------------------------------------------------------

# Calidad y evaluación del café

-   [En busca de la taza de café perfecta](https://enlaceejemplo.com/)
-   [The Coffee Maker. NYT, 2022](https://www.nytimes.com/)
-   Evaluación
    -   [EL CAFÉ DE CALIDAD Y EL SISTEMA DE EVALUACIÓN DE LOS 100 PUNTOS](https://enlaceejemplo.com/)
-   Secado
    -   [Todo Lo Que Necesitas Saber Sobre El Café Honey](https://enlaceejemplo.com/)
    -   [HONEY PROCESS ¿EN QUÉ CONSISTE?](https://enlaceejemplo.com/)

# Métodos de preparación de café

-   Prensa francesa
-   V60
-   Chemex
-   Aeropress
-   Expresso

## Hoop

-   Ceado. [*Link*](https://coffee.ceado.com/en/products/86-hoop_coffee_brewer/56-hoop)

{{< video "https://youtu.be/14Wte33lAVE width=500" >}} Ceado

------------------------------------------------------------------------

# Tiendas de café

-   **Usaquén**
    -   [San Alberto](https://www.cafesanalberto.com/)
    -   [Colo Coffee](https://www.colocoffee.co/)
    -   [Catación Pública](https://www.catacionpublica.com/)
-   **Chapinero**
    -   [Libertario](https://cafelibertario.com/)
    -   [Devoción](https://www.devocion.com.co/)
    -   [Varietale](https://www.varietale.com.co/)
    -   [Café Cultor](https://cafecultor.com/)
    -   [Amor Perfecto](https://amorperfecto.com/)
    -   [Colo Coffee](https://www.colocoffee.co/)
    -   [Tropicalia](https://www.tropicaliacafe.com/)
    -   [Azahar](https://azaharcoffee.com/)
    -   [Alma](https://almacafe.com.co/)
    -   [Jon Dech Cafe](https://jondechcafe.com/)
    -   [Bogota Coffee Roasters](https://bogotacoffeeroasters.com/)
    -   [Cafe de la Tintería](https://cafedelatinteria.com/)
-   **Marcas de café especial de Colombia**
    -   [Enigma](https://cafesenigma.com/)
    -   [Solarte](https://cafesolarte.com/)
    -   [Laderas del Tapias](https://laderasdeltapias.com/)
    -   [Divisas de la virgen](https://enlaceejemplo.com/)
    -   [Pergamino](https://pergaminocafe.com/)
    -   [5cento](https://5centocafe.com/)
    -   [Café Sommelier](https://cafesommelier.com/)
    -   [Serranias de Jardin](https://serraniasdejardin.com/)
-   **Tiendas de café especial**
    -   [Cafés de origen *la más completa hasta ahora*](https://enlaceejemplo.com/)
-   **Buscadores**
    -   [Freshfarmer](https://www.freshfarmer.co/)
    -   [m.cultivo](https://mcultivo.com/)
    -   [Mapa Coffee masters 2022](https://enlaceejemplo.com/)
-   **Accesorios**
    -   [La feria de la greca](https://enlaceejemplo.com/)

::: callout-tip
Influenciadores

-   James Hoffmann [Webpage](https://www.jameshoffmann.co.uk/) [Youtube](https://www.youtube.com/channel/UCMb0O2CdPBNi-QqPk5T3gsQ) Instagram @jimseven

-   Tanner coffee [Enlace a Facebook](https://www.facebook.com/reel/548751493636877)
:::

------------------------------------------------------------------------

# Podcast

-   [Vivir Café Revista en Podcast. Por Hugo Sabogal](https://enlaceejemplo.com/)
-   **Enlaces del programa**
    -   [*Innovakit*](https://enlaceejemplo.com/)
    -   <https://indestec.com.co>
    -   <http://vivircafe.com>
    -   <https://www.qimacoffee.com>
    -   <https://www.asopep.org>
    -   <https://federaciondecafeteros.org/wp/sostenibilidad/eje-social>
    -   <https://coocentral.com>
    -   <http://cafemontesycolinas.com/index1.html>
    -   <https://lapalmayeltucanhotel.com>
    -   <https://www.eternitycoffeeroasters.com>
    -   <https://www.thecoffeequest.com>
    -   <https://www.campesinospecialtycoffee.com>
    -   <https://mastercol.co>
    -   <https://lltostadores.com>
    -   <https://guayacancafe.negocio.site>
    -   <http://tazadeexcelenciacolombia.com>
    -   <https://allianceforcoffeeexcellence.org>
    -   <http://www.supremo.be>
    -   <http://www.asecc.co>
    -   <http://www.4point0brands.com>
    -   [Caravella coffee importers](https://caravellacoffee.com/)
    -   [Guayacán Café](https://guayacancafe.negocio.site/)

## Ciencia y otras lecturas

-   [Systematically Improving Espresso: Insights from Mathematical Modeling and Experiment. Matter, 2020](https://www.cell.com/matter/fulltext/S2590-2385(19)30410-2)
-   [Paper-Filtered Coffee and Cholesterol](https://enlaceejemplo.com/)