---
title: "Vida laboral"
format: html
editor: visual
---

# **Trabajo en equipo**

-   **Working in Teams: A Practical Guide**. Coursera. [*Link*](https://www.edx.org/course/working-in-teams-a-practical-guide).
-   «Esto podría haber sido un email»: cómo las reuniones innecesarias ahogan a los trabajadores. [*Link*](https://smoda.elpais.com/trabajo/esto-podria-haber-sido-un-email-como-las-reuniones-innecesarias-ahogan-a-los-trabajadores/)
    -   *“Antes trabajábamos en silos, en departamentos estancos, de forma individual”, recuerda. Pero el mundo laboral es cada vez más complejo y comunitario, por lo que las empresas requieren cada vez más de “inteligencia colectiva, de colaboración, de trabajo en red, de modelos de trabajo participativos para poder innovar, de trabajar por objetivos, de transparencia en el proceso del cual formo parte”, etc.*

Working in Teams: A Practical Guide

# **Cultura laboral**

-   **Gig Economy**
    -   Desperate Venezuelans are making money by training AI for self-driving cars. [*Link*](https://www.technologyreview.com/s/614194/venezuela-crisis-platform-work-trains-self-driving-car-ai-data/amp/?__twitter_impression=true).
    -   Amazon Mechanical Turk. [Link](https://www.mturk.com/).
    -   Scale. [*Link*](https://scale.com/).
    -   Hive Work. [*Link*](https://hivemicro.com/).
    -   Playment. [Link](https://playment.io/jobs/).
-   **Procastinar**
-   Procrastinar no es un asunto de holgazanería, sino de manejo de las emociones. NYTimes. [*Link*](https://www.nytimes.com/es/2019/03/26/como-evitar-la-procrastinacion/).
-   **Lecturas sobre cultura laboral**
    -   Los mejores consejos que te han dado y que les darías a otros. NY Times. [*Link*](https://www.nytimes.com/es/2019/05/06/mejores-consejos-de-vida/).
        -   Todo por escrito". Ordenes, instrucciones, resultados por mensajes de texto o e-mail.Siempre hay dos bandos.
        -   No tome partido en ninguno.
        -   Sea neutral en su trabajo.
        -   Piense en largo plazo.
        -   No lo tome personal. Evalue el trabajo, no la persona (a menos que...
            -   Los cargos van y vienen
        -   No responder correos electrónicos no habla bien de ti ni de tu productividad. NYT. [*Link*](https://www.nytimes.com/es/2019/02/19/como-contestar-correo/?smid=tw-espanol&smtyp=cur). - *La pelota en la cancha de otro. Su bandeja de correo no debe tener pendientes.*
    -   "5-2-1". Cinco horas de trabajo efectivo. Dos horas para resolver asuntos secundarios. Una hora de trabajo libre y creativo. “You do not need to work 80 hours a week to succeed in academia”. [*Link*](http://www.nature.com/nature/journal/v546/n7656/full/nj7656-175a.html?WT.mc_id=TWT_NatureNews&sf84131996=1).
    -   Ningún trabajo es indispensable. Sepa dejar atrás cualquier trabajo. \*Don't waste time in a bad environment. Your life is not a game. Don't wait for strike three.\*\*[Link](https://science.sciencemag.org/content/363/6424/314)\*.
    -   Encuentre un balance entre trabajo y vida personal. [*Link*](https://blogs.scientificamerican.com/guest-blog/the-awesomest-7-year-postdoc-or-how-i-learned-to-stop-worrying-and-love-the-tenure-track-faculty-life/).
-   **Lecturas varias**
    -   Estudiar ¿para ser un desempleado? [*Link*](https://www.larepublica.co/analisis/rodolfo-correa-3159692/estudiar-para-ser-un-desempleado-3247048).
    -   Does Higher Education Still Prepare People for Jobs?. [*Link*](https://hbr.org/2019/01/does-higher-education-still-prepare-people-for-jobs?utm_medium=social&utm_campaign=hbr&utm_source=twitter&tpcc=orgsocial_edit).
    -   Why You Should Have (at Least) Two Careers. HBR. [*Link*](https://hbr.org/amp/2017/04/why-you-should-have-at-least-two-careers?__twitter_impression=true).\*\*\*
    -   Why People Lose Motivation — and What Managers Can Do to Help. HBR. [*Link*](https://hbr.org/amp/2018/03/why-people-lose-motivation-and-what-managers-can-do-to-help).
    -   Why People Really Quit Their Jobs. HBR. [*Link*](https://hbr.org/amp/2018/01/why-people-really-quit-their-jobs).
    -   How Company Culture Shapes Employee Motivation. HBR. [*Link*](https://hbr.org/2015/11/how-company-culture-shapes-employee-motivation).
    -   Is It Really Too Late to Learn New Skills? Newyorker. [*Link*](https://www.newyorker.com/magazine/2021/01/18/is-it-really-too-late-to-learn-new-skills).
    -   ¿Qué tanto -y de qué- debe saber un Presidente? 2022.
        -   " *Las tareas cruciales de la dirección ejecutiva en cualquier ámbito son básicamente las mismas: identificar y señalar los objetivos, escoger un buen equipo, coordinarlo, respaldarlo, darle lo que necesita y evaluarlo. La función del director ejecutivo, enfatizaba Bloomberg, no es hacer las cosas, sino conseguir y respaldar al equipo que las va a hacer."*
    -   The Little Things That Make Employees Feel Appreciated. HBR. [*Link*](https://hbr.org/amp/2020/01/the-little-things-that-make-employees-feel-appreciated).
    -   The 3 Things Employees Really Want: Career, Community, Cause. HBR. [Link](https://hbr.org/amp/2018/02/people-want-3-things-from-work-but-most-companies-are-built-around-only-one).
    -   Why Skills Training Can’t Replace Higher Education. [*Link*](https://hbr.org/amp/2019/10/why-skills-training-cant-replace-higher-education).
    -   If You’re Not Outside Your Comfort Zone, You Won’t Learn Anything. HBR. [*Link*](https://hbr.org/2016/07/if-youre-not-outside-your-comfort-zone-you-wont-learn-anything?utm_medium=social&utm_campaign=hbr&utm_source=twitter&tpcc=orgsocial_edit).
    -   Tips for Reading the Room Before a Meeting or Presentation. HBR. [*Link*](https://hbr.org/2018/05/tips-for-reading-the-room-before-a-meeting-or-presentation?utm_medium=social&utm_campaign=hbr&utm_source=twitter&tpcc=orgsocial_edit)
    -   *Pay attention to the people in it. Note who’s next to whom, who’s relaxed, who’s not, who’s standing, and who’s sitting. Look at their facial expressions, posture, and body language. Then try to make sense of what you’ve observed. Reflect on possible reasons for your colleagues’ emotional states. What’s happening in their lives and in their jobs? If the atmosphere feels tense, don’t let yourself be hijacked by negativity. Instead, shift the mood using humor or empathy. Keep an eye out for positive signals, too*
-   **Los trabajos del futuro**
    -   McKinsey: These are the skills you will need for the future of work. [*Link*](https://www.weforum.org/agenda/2021/06/defining-the-skills-citizens-will-need-in-the-future-world-of-work).
    -   ¿Su trabajo se automatizará? *Robots, jobs, and resilience*. [*Link*](https://lis2.epfl.ch/resiliencetorobots/#/).
-   **Manejo del tiempo**
    -   How Timeboxing Works and Why It Will Make You More Productive. HBR. [*Link*](https://hbr.org/2018/12/how-timeboxing-works-and-why-it-will-make-you-more-productive).
    -   Migrating to-do lists into calendars.
    -   Block out all distractions for that timeboxed period.
    -   If all of your critical work is in your calendar, colleagues can *see* it.
    -   Are You Having Trouble Focusing? These Simple Strategies Will Help. HBR. [*Link*](https://hbr.org/2017/12/are-you-having-trouble-focusing-these-simple-strategies-will-help)
-   **Contratación, entrevistas, reclutamiento**
    -   Cómo evaluar las habilidades de pensamiento crítico de un candidato a un puesto de trabajo en una entrevista. HBR. 2023. [*Link*](https://hbr.org/2023/09/how-to-evaluate-a-job-candidates-critical-thinking-skills-in-an-interview?utm_medium=paidsocial&utm_source=facebookinstagram&utm_campaign=intlcontent&hide_intromercial=true&tpcc=paidsocial.facebookinstagram.content%3D6468014740831&fbclid=IwAR16JHJS9XRouEQ5mBmKd2E8ZEd1Xk5Q2cwhfbiZGiEVUpG4xKw0XE6AE0g_aem_ATzZLonm_1kQTscm-h0VJeVOndNWBQEiBEJwfL7NOorrHA6Owo_RohAHsU3Ila_637zl2NexvvSB-XnSJo3dLjna). Entrevista invertida.
-   **The definitive 100 most useful productivity tips.**[*Link*](https://learn.filtered.com/hubfs/Definitive%20100%20Most%20Useful%20Productivity%20Hacks.pdf)
    1.  Time-boxing

    2.  Prioritise

    3.  Say no

    4.  Move!

    5.  Control your devices

    6.  Take short breaks

    7.  To-do lists

    8.  Eat well

    9.  2-minute rule

    10. Control social media

**Sobre el empleo en Colombia**

<https://youtu.be/4kmYFk-e2_0>

`<video controls src="https://inspira-apps.un.org/inspira/JFQ/Job_Requirements_How_to_Respond.mp4"`{=html}

</video>

-   **Lecturas**
-   Una creencia en la meritocracia no solo es falsa: es mala para ti. 2020.[*Link*](https://press.princeton.edu/ideas/a-belief-in-meritocracy-is-not-only-false-its-bad-for-you)*.*

# **Sobre el empleo en el sector público**

-   Diferencias en la calidad del empleo público en Colombia: una comparación entre empleados de planta y contratistas. Universidad de los Andes. [*Link*](https://egob.uniandes.edu.co/es/component/abook/book/12-documentos-de-trabajo/156-diferencias-en-la-calidad-del-empleo-publico-en-colombia-una-comparacion-entre-empleados-de-planta-y-contratistas)
-   ¿Cómo mejorar y racionalizar la contratación por prestación de servicios en el sector público en Colombia? Una mirada desde la calidad del empleo. Universidad de los Andes. [*Link*](https://egob.uniandes.edu.co/es/me-publicaciones/notas-de-politica/15-notas-de-politica/160-como-mejorar-y-racionalizar-la-contratacion-por-prestacion-de-servicios-en-el-sector-publico-en-colombia-una-mirada-desde-la-calidad-del-empleo).
-   ¿Cómo hacer estratégica la gestión del talento humano en las organizaciones públicas colombianas?. Universidad de los Andes. [*Link*](https://egob.uniandes.edu.co/es/me-publicaciones/notas-de-politica/15-notas-de-politica/80-como-hacer-estrategica-la-gestion-del-talento-humano-en-las-organizaciones-publicas-colombianas).
-   Contratos por prestación de servicios sí afectan la calidad del empleo público. Universidad de los Andes. [*Link*](https://uniandes.edu.co/es/noticias/gobierno-y-politica/contratos-por-prestacion-de-servicios-si-afectan-la-calidad-del-empleo-publico?fbclid=IwAR2JndEEo6DG_cwI30KPxNA8kxJT3KhO4bMRWKikthBRB1RWVoIluU0F8sw).
-   ¿Los contratistas son servidores públicos? **No**. [*Link*.](https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=77352)
-   En las clasificaciones internacionales no estamos bien: tenemos mala calidad laboral, somos poco productivos a pesar que trabajamos mucho.

<https://youtu.be/4kmYFk-e2_0>

-   **Recursos de educación del Estado**
    -   Función Pública.
        -   EVA - Espacio virtual de asesoría de la función pública. [*Link*](https://www.funcionpublica.gov.co/eva/admon/index.php).
        -   Gestión del Conocimiento. [*Link*](https://www.funcionpublica.gov.co/web/eva/generacion-y-produccion).
    -   SENA
        -   Sofia Plus. [*Link*](http://www.senasofiaplus.edu.co/).

#PhDlife

-   **Ejemplos de páginas personales**
    -   Bijan Ranjbar. [*Link*](https://www.mydataexpert.nl/).
-   ***#PhDlife***
    -   PhD training is no longer fit for purpose — it needs reform now. **Nature**. 2023. [*Link*](https://www.nature.com/articles/d41586-023-00084-3) \*\*\*
    -   Researchers’ career insecurity needs attention and reform now, says international coalition. **Nature**. 2021. [*Link*](https://www.nature.com/articles/d41586-021-01548-0).
    -   Eight career tips from Nobel Laureates. **Nature**. 2021. [*Link*](https://www.nature.com/articles/d41586-021-02772-4).
    -   Transitioning from postdoc researcher to gig-economy scientist. **Nature**. 2019. [*Link*](https://www.nature.com/articles/d41586-019-03021-5).
    -   You do not need to work 80 hours a week to succeed in academia. **Nature**. 2017. [*Link*](http://www.nature.com/nature/journal/v546/n7656/full/nj7656-175a.html?WT.mc_id=TWT_NatureNews&sf84131996=1).
    -   Why I pursued interdisciplinary research as an aspiring academic—despite the career risks. Science. 2024. [*Link*](https://www.science.org/content/article/why-pursued-interdisciplinary-research-as-aspiring-academic-despite-career-risks)
        -   *Having expertise in multiple disciplines is my superpower, and my university has shown it values that breadth. Although I expect there will be further setbacks, I hope to remain without a one-word definition of my expertise for as long as possible!*
-   **Hábitos laborales**
    -   Ten simple rules to improve academic work–life balance: **PloS**. 2021. [*Link*](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1009124).

How to Become Indistractable with Nir Eyal

-   **Documentos para contratación**
    -   Carpeta Digital Ciudadana. [*Link*](https://carpetaciudadana.and.gov.co/bienvenido).
    -   Función pública. [*Link*](https://www.funcionpublica.gov.co/).
    -   Hoja de vida del servidor público
        -   SIGEP I. [*Link*](https://www.funcionpublica.gov.co/web/sigep/).
        -   SIGEP II. [*Link*](https://www.funcionpublica.gov.co/sigep-web/sigep2/index.xhtml).
        -   Aplicativo por la Integridad Pública. [*Link*](https://www.funcionpublica.gov.co/fdci/login/auth).
    -   Certificado antecedentes disciplinarios - Procuraduría. [*Link*](https://www.procuraduria.gov.co/Pages/certificado-antecedentes.aspx).
    -   Certificado antecedentes fiscales - Contraloría. [*Link*](https://www.contraloria.gov.co/control-fiscal/responsabilidad-fiscal/certificado-de-antecedentes-fiscales).
    -   Certificado antecedentes judiciales - Policia. [*Línk*](https://antecedentespolicia.com.co/).
    -   Certificado de pensiones. Colfondos [*Link*](https://www.colfondos.com.co/dxp/personas/pensiones-obligatorias/certificado-afiliacion). Colpensiones [*Link*](https://www.colpensiones.gov.co/).
    -   Certificado EPS Sanitas. [*Link*](https://www.epssanitas.com/usuarios/web/nuevo-portal-eps/inicio)
    -   Certificado de cesantias. Porvenir [*Link*](https://transacciones.porvenir.com.co/Personas/Paginas/default.aspx). Protección [*Link*](https://www.proteccion.com/wps/portal/proteccion/web/cesantias/personas).
    -   Certificado de medidas correctivas (colocar fecha expedición cédula). [*Link*](https://srvcnpc.policia.gov.co/PSC/frm_cnp_consulta.aspx).
    -   Certificado de movimientos migratorios. [*Link*](https://www.migracioncolombia.gov.co/certificado-de-movimientos-migratorios).
    -   Certificado libreta militar. [*Link*](https://www.libretamilitar.mil.co/modules/consult/militarycardcertificate).
    -   Consulta de Inhabilidades. Delitos sexuales cometidos contra menores de 18 años. [*Link*](https://inhabilidades.policia.gov.co:8080/).
    -   Registro de Deudores Alimentarios Morosos. [*Link*](https://www.redam.gov.co/).
    -   Tramites del Estado. [*Link*](https://www.tramitesyconsultas.info/).
    -   RUAF. [*Link*](https://ruaf.sispro.gov.co/TerminosCondiciones.aspx).
    -   Positiva ARL. Certificado. [*Link*](https://www.positivaenlinea.gov.co/nuevo).
    -   Carpeta ciudadana. [*Link*](https://carpetaciudadana.and.gov.co/bienvenido).
-   **ARL**
    -   Glosario SURA. [*Link*](https://www.arlsura.com/index.php/glosario-arl).
-   **Hoja de vida**
    -   Make your cover letter and CV stand out. Nature Jobs. [*Link*](http://blogs.nature.com/naturejobs/2014/02/28/make-your-cover-letter-and-cv-stand-out/).
    -   Cover letter. Do your homework. Science. 2016. [*Link*](http://www.sciencemag.org/careers/2016/11/do-your-homework?utm_source=sciencecareers&utm_medium=facebook&utm_campaign=applications-9067)
    -   Job applications: Under the covers. [*Link*](http://www.nature.com/nature/journal/v538/n7623/full/nj7623-129a.html?WT.mc_id=TWT_NatureNews).
    -   Writing a job letter. Nature Jobs. [*Link.*](https://www.nature.com/scitable/topicpage/formal-letters-13988017)
    -   Open Science personal web page. [*Link*](https://osprojectsite.org/home).
    -   How to Get Your Resume Noticed (And Out of the Trash Bin). HBR. [*Link*](https://hbr.org/2020/09/how-to-get-your-resume-noticed-and-out-of-the-trash-bin?utm_medium=social&utm_campaign=hbr&utm_source=twitter&tpcc=orgsocial_edit).
    -   Why I wrote an impact CV. Nature. [*Link*](https://www.nature.com/articles/d41586-022-00300-6)
-   **Formato a documento de hoja de vida**
    -   How to create a CV with Rmarkdown, Awesome CV and Google Sheets. [*Link*](https://medium.com/@darwin.cubi/how-to-create-a-cv-with-rmarkdown-awesome-cv-and-google-sheets-7e9a05815f63).
    -   Job-winning CV templates. Resume.io. [*Link*](https://resume.io/cv-templates?ga_utm_source=google&ga_utm_medium=display&ga_utm_campaign=1505745092&ga_utm_term=cv%20experience&gclid=EAIaIQobChMIzIWRruuo_AIVzNuHCh23egUjEAEYASAAEgJ63fD_BwE).
-   **Bases de datos de ofertas laborales**
    -   TicJob. [*Link*](https://ticjob.co/es/search?skills=868).
-   **Instituciones públicas**
    -   Cuentas claras. [*Link*](http://www.cnecuentasclaras.com/).
    -   Registraduría. Historico de resultados. [*Link*](https://www.registraduria.gov.co/-Historico-de-Resultados,3635-.html).
    -   Auditores ciudadanos. [*Link*](https://auditoresciudadanos.dnp.gov.co/).
-   **Lecturas politica y economía**
    -   ¿Los politicos deben formarse en pensamiento cuantitativo? --- What Are the Odds?. To learn to think critically, take a statistics class. [*Link*](http://www.slate.com/articles/life/classes/2015/08/take_a_statistics_and_probability_class_in_college_to_improve_critical_thinking.html).
    -   Why some billionaires are bad for growth, and others aren’t. The Washington Post. [*Link*](https://www.washingtonpost.com/news/wonk/wp/2015/08/20/why-some-billionaires-are-bad-for-growth-and-others-arent/?utm_term=.644c0c332308).
        -   Does wealth inequality matter for growth? The effect of billionaire wealth, income distribution, and poverty. Journal of Comparative Economics (43) 3. 2015, [*Link*](http://www.sciencedirect.com/science/article/pii/S0147596715000505)*.*
    -   Luchar contra la corrupción desde tu computadora. El Pais. 2018. [*Link*](https://elpais.com/internacional/2018/05/30/argentina/1527690628_472138.html).
    -   Cuando el ciudadano de a pie puede poner multas de tráfico. El Pais. 2019. [*Link*](https://elpais.com/internacional/2019/05/28/actualidad/1559074423_054278.html).
    -   10 things to know about how to influence policy with research. [*Link*](https://www.odi.org/publications/10671-10-things-know-about-how-influence-policy-research).
    -   Clientelism, public goods provision, and governance. 2021. [*Link*](https://www.wider.unu.edu/publication/clientelism-public-goods-provision-and-governance).
    -   Inteligencia Artificial para Detectar Corrupción en la Administración Pública Municipal de Colombia. [*Link*](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3891812).

# **Contratación pública**

-   Curso contratación pública. Función pública. [*Link*](https://formacionvirtual.colombiacompra.gov.co/mod/page/view.php?id=2754)*.*