---
title: "Inundaciones"
format: html
editor: visual
---

## Instituciones nacionales

-   UNGRD. [*Link*](https://portal.gestiondelriesgo.gov.co/)
-   Minambiente.
-   IDEAM. *Link*
-   Fondo Adaptación
-   Bomberos de Colombia. *Link*

## Instituciones internacionales

## Amenaza por inundaciones

Europe floods: new tool to estimate water depth and extent. 2024. [*Link*](https://joint-research-centre.ec.europa.eu/jrc-news-and-updates/europe-floods-new-tool-estimate-water-depth-and-extent-2024-09-20_en).\
Satellite imaging reveals increased proportion of population exposed to floods. Nature, 2021. [*Link*](https://www.nature.com/articles/s41586-021-03695-w). - The fraction of the global population at risk of floods is growing. Nature News. 2021. [*Link*](https://www.nature.com/articles/d41586-021-01974-0). - ARSET – Monitoring and Modeling Floods using Earth Observations. NASA. [*Link*](https://appliedsciences.nasa.gov/join-mission/training/english/arset-monitoring-and-modeling-floods-using-earth-observations). - Global Floods. [*Link*](https://www.globalfloods.eu/) - What’s in Floodwaters? [*Link*](https://www.scientificamerican.com/article/whats-in-floodwaters/?utm_source=twitter&utm_medium=social&utm_campaign=socialflow).

::: {layout-ncol="2"}
{{< video "https://youtu.be/QWEXzQaYt9s" >}}

{{< video "https://youtu.be/4zY6-GdprWA" >}}

{{< video "https://www.youtube.com/watch?v=iY64O86eLB8" >}}

{{< video "https://www.youtube.com/watch?v=qIaw0IgtkfM" >}} Part 1: Overview of Flood Monitoring Tools based on Remote Sensing Observations

{{< video "https://www.youtube.com/watch?v=GWSV3SLi40c" >}}

Amenaza por inundaciones
:::

## Evaluación del riesgo por inundaciones

::: {layout-ncol="2"}
{{< video "https://youtu.be/swr4NlX2bVE" >}}

Evaluación del riesgo por incendios forestales.
:::

## Comunicación del riesgo por inundaciones

-   

::: {layout-ncol="2"}
{{< video "https://youtu.be/8u3F5f47i_M" >}}

Comunicación del riesgo por incendios forestales.
:::

## Reducción del riesgo de inundaciones

{{< video "https://youtu.be/ZtULL-6IcQg?si=jmWmRuvidFGTVYBM" >}} Planning for Safety: How Land Use Decisions Shape Flood Risk. [*Link*](https://www.aaas.org/events/planning-safety-how-land-use-decisions-shape-flood-risk)

## Manejo de desastres por inundaciones

-   Red

::: {layout-ncol="2"}
{{< video "https://vimeo.com/701418128" >}}
:::

## Lecturas

-   How to Know Your Flood Risk. NYT. 2025. [*Link*](https://www.nytimes.com/2025/07/15/climate/how-to-know-your-flood-risk.html).

## **Entrenamiento**

-   Cope

## Repositorios

-   A Collection of NASA ARSET Courses for Flood Mapping and Synthetic Aperture Radar (SAR). [*Link*](https://github.com/mebauer/floodmapping-sar).

## Videos

::: {layout-ncol="2"}
{{< video "https://vimeo.com/701418128" >}}
:::