---
title: "Gestión de tecnología e innovación"
format: html
editor: visual
---

# Lista de recursos para la gestión de la innovación en Colombia.

::: {layout-ncol="2"}
{{< video https://youtu.be/yCm9Ng0bbEQ >}} Está el mundo mejor o peor
:::

# **Manuales para la innovación**

-   Manual de Bogotá. .
-   Manual de Santiago. .
-   Manual de Oslo. .
-   Manual de Frascati. [*Link*](https://www.oecd.org/publications/manual-de-frascati-2015-9789264310681-es.htm).

# **Datos innovación latinoamérica**

-   Red de Indicadores de Ciencia y Tecnología Interamericana.
-   **Datos innovación mundiales**
    -   Organización Mundial de la Propiedad Intelectual (OMPI). [*Link*](https://www.wipo.int/portal/es/).
    -   Índice Mundial de Innovación. [*Link*](https://www.wipo.int/global_innovation_index/es/).
    -   The Innovation Policy Platform (IPP). [*Link*](http://www.innovationpolicyplatform.org/www.innovationpolicyplatform.org/frontpage/index.html).
    -   Innovation Policy: A Guide for Developing Countries. [*Link*](http://www.innovationpolicyplatform.org/www.innovationpolicyplatform.org/document/innovation-policy-guide-developing-countries/index.html).

# **Innovación en Colombia**

## **Innovación Colombia**

-   Innovamos. [*Link*](https://www.innovamos.gov.co/).
-   Camara de Comercio - Bogota. [*Link*](http://www.ccb.org.co/).
-   OCAD-DNP. [*Link*](https://www.sgr.gov.co/Qui%C3%A9nesSomos/%C3%93rganosdelSGR/%C3%93rganosColegiadosdeAdministraci%C3%B3nyDecisi%C3%B3n.aspx).
-   Oxelerator. [*Link*](https://www.oxelerator.com/).
-   Secretaria de Planeación - Bogota. *Link*.
-   Fondo Emprender. [*Link*](http://www.fondoemprender.com/SitePages/Home.aspx).
-   *Fondo Innpulsa. [Link](https://www.innpulsacolombia.com/)*.
-   DNP. Equipo de Innovación Pública. [*Link*](https://www.dnp.gov.co/programas/desarrollo-empresarial/Paginas/Innovacion-Publica.aspx).
-   Sistema Nacional de Competitividad e Innovación - SNCI. [*Link*](http://www.colombiacompetitiva.gov.co/snci/el-sistema/quienes-somos).
-   Compra pública para la innovación.
    -   Compra Pública para la Innovación –CPI. [*Link*](https://www.colombiacompra.gov.co/compra-publica-innovadora/que-es-compra-publica-para-la-innovacion).

::: {layout-ncol="2"}
{{< video "https://youtu.be/LmhdPB66LKs" >}} Socialización de la Política Nacional de Propiedad Intelectual - CONPES 4062. Marzo de 2022

{{< video "https://youtu.be/2YI-QJblf9c" >}}

{{< video "https://youtu.be/tjP6bnnay8U" >}} Barreras para la innovación

{{< video "https://youtu.be/yOo_uqEU-oY" >}} Metodología de Articulación para la Competitividad – ArCo

{{< video "https://www.youtube.com/live/l4WhvuyflcA" >}}
:::

## **Innovación universitaria**

-   Universidad Nacional de Colombia. [*Link*](http://innovacion.unal.edu.co/).
-   Universidad de los Andes[. *Link*.](https://conectate.uniandes.edu.co/)
-   **Datos y políticas de innovación Colombia**
    -   Índice Departamental de innovación para Colombia 2018. DNP. [*Link*](https://colaboracion.dnp.gov.co/CDT/Prensa/IndiceDepartamentalInnovacionColombia2018.pdf).
    -   Índice Departamental de innovación para Colombia 2019. DNP. [*Link*](https://www.dnp.gov.co/programas/desarrollo-empresarial/Competitividad/Paginas/Indice-Departamental-de-Innovacion-para-Colombia-2019.aspx).
    -   Índice Global de Innovación 2018. Informe para Colombia. 2018. DNP. [*Link*](https://colaboracion.dnp.gov.co/CDT/Prensa/%E2%80%8B%C3%8Dndice%20Global%20de%20Innovaci%C3%B3n%2C%202018.%20Informe%20para%20Colombia%20%E2%80%8B.pdf).
    -   CONPES 3975. Política Nacional de Transformación Digital e Inteligencia Artificial[*. Link*](https://www.mintic.gov.co/portal/604/articles-107147_recurso_1.pdf).
    -   Lineamientos para una política de Ciencia Abierta en Colombia. Minciencias. [*Link*](https://minciencias.gov.co/sites/default/files/ckeditor_files/Lineamientos%20ciencia%20abierta%2017-dic-2018-doc.pdf).
    -   **Metodología de Articulación ArCo**. DNP. [*Link*](https://www.dnp.gov.co/programas/desarrollo-empresarial/Competitividad/Paginas/Metodologia-de-Articulacion-ArCo.aspx).

::: {layout-ncol="2"}
{{< video "https://www.youtube.com/live/l4WhvuyflcA" >}} Metodología de Articulación para la Competitividad – ArCo
:::

# **Vigilancia tecnológica e inteligencia competitiva**

-   Vigilancia tecnologíca UTP. [*Link*](https://vicerrectorias.utp.edu.co/viie/herramientas-para-la-vigilancia-estrategica-e-inteligencia-competitiva/)

# **Curso de innovación pública**

-   ¿Qué es la innovación pública? [*Link*](https://medium.com/@eipdnp/qu%C3%A9-es-la-innovaci%C3%B3n-p%C3%BAblica-bbe2fcc65e1a)
-   Uso de Trello como herramienta para la gestión de tareas. [Link](https://medium.com/@eipdnp/uso-de-trello-como-herramienta-para-la-gesti%C3%B3n-de-tareas-4138ec8153e2).
-   Iteración del marco de competencias para innovadores públicos de Nesta en el EiP del DNP. [*Link*](https://medium.com/@eipdnp/iteraci%C3%B3n-del-marco-de-competencias-para-innovadores-p%C3%BAblicos-de-nesta-en-el-eip-del-dnp-e922c751fa1a).
-   Innovación pública con ciencia de datos. [*Link*](https://medium.com/@eipdnp/innovaci%C3%B3n-p%C3%BAblica-con-ciencia-de-datos-673cbbdc39d6).
-   Innovación y Gestión del Conocimiento en la Gestión Pública. [*Link*](https://contenidoseducativospublicos.esap.edu.co/index.php/categorias/categoria/93). \*\*\*
    -   [Parte 1](https://youtu.be/tsMmAg4edvY), [Parte 2](https://youtu.be/rwnzEe_eN7c), [Parte 3](https://youtu.be/e2TN3Bi6l0k)

# **Innovación social**

-   Pensar, decir, hacer: encuentros de Innovación Social. UNAL 2021. [*Link*](https://investigacion.unal.edu.co/boletin/notas-boletin-un-investiga/news/pensar-decir-hacer-encuentros-de-innovacion-social/).

# **Cursos en línea**

-   El valor de la creatividad y la innovación: La Economía Naranja. EdX. Banco Mundial. [*Link*](https://www.edx.org/es/course/el-valor-de-la-creatividad-y-la-innovacion-la-economia-naranja).
-   **Documental**
    -   El cerebro creativo. [Link.](https://www.netflix.com/us-es/title/81090128)

# **Lecturas innovación y emprendimiento**

-   A toolkit of policies to promote innovation. [*Link*](https://ideas.repec.org/p/cep/cepdps/dp1634.html).
-   Global labor flow network reveals the hierarchical organization and dynamics of geo-industrial clusters. [*Link*](https://www.nature.com/articles/s41467-019-11380-w?fbclid=IwAR3Wem1zj6QfAfinKsk1Y7rMKQjHl84jNFU4P9vZcv3SEYxWzxfrLqIQNoY#Abs1).
-   The Heilmeier Catechism: A Recipe For Managing Innovation. [*Link*](https://medium.com/art-of-the-start/the-heilmeier-catechism-a-recipe-for-managing-innovation-41511be748a)
    -   The Only 10 Slides You Need in Your Pitch. [*Link*](https://guykawasaki.com/the-only-10-slides-you-need-in-your-pitch/).
-   Scott Shane.
    -   Google Scholar: [*Link*](https://scholar.google.com/scholar?hl=es&as_sdt=0%2C5&q=Scott+Shane+Entrepreneurship&btnG=). Videos: [*Link*](https://www.youtube.com/watch?v=rMFCKaTckgI).
    -   2003\. A General Theory of Entrepreneurship: The Individual-opportunity Nexus. [*Link*](https://books.google.com.co/books?id=0FxO_Wsh30kC&printsec=frontcover&hl=es&source=gbs_ge_summary_r&cad=0#v=onepage&q&f=false).
-   **Algunos expertos**
    -   Joe Tidd. [*Link*](https://scholar.google.com/citations?hl=es&user=he2j1ugAAAAJ&view_op=list_works&sortby=pubdate).

# **Métodos de innovación**

**Spin-off**

Buenas prácticas en el acompañamiento a 'spin-offs' universitarios

Postdoc para crear empresas. Fernando Gomez.

## **Charlas sobre innovación**

Sistema Innovación, Transferencia Conocimiento y Emprendimiento [#UNAL](https://www.youtube.com/hashtag/unal) (Diego Torres)

# Aprender a innovar

-   Learning to Learn. [*Link*](https://hbr.org/2016/03/learning-to-learn).

Lanzamiento del programa Méntor - Spinn-off y Transferencia del Conocimiento

**Lecturas**

-   Linking Entrepreneurship and Economic Growth. 1999. [*Link*](https://link.springer.com/article/10.1023/a:1008063200484).
-   Innovation intermediaries, knowledge infrastructure and technological opportunities in emerging markets: the case of research and technological centers in the Colombian agricultural sector. Innovation and development. 2023. [*Link*](https://www.tandfonline.com/doi/abs/10.1080/2157930X.2022.2133380?journalCode=riad20).
-   La innovación se ha estancado y la academia es responsable. Forbes. 2023. [*Link*](https://forbes.co/2023/03/28/red-forbes/la-innovacion-se-ha-estancado-y-la-academia-es-responsable).