---
title: "Amazonas"
format: html
editor: visual
---

# **Sistemas de información y redes**

-   MapBiomas. [*Link*](https://plataforma.amazonia.mapbiomas.org/agua).
-   Observatorio regional del Amazonas ARO. [*Link*](https://oraotca.org/en/home/).
-   Atlas de Conflictos Socioambientales de la Amazonía colombiana. [*Link*](https://siatac.co/atlas-conflictos-socioambientales/?fbclid=IwAR1ZekAw3NNfsHnnZXiDpHFz0ONGYzax26xTVMwYyHOft1cfavwnXZx-G3g).

# **Programas**

-   Amazonía viva. Banco mundial. [*Link*](https://www.bancomundial.org/es/programs/supporting-amazonia#:~:text=Amazon%C3%ADa%20Viva%20es%20la%20iniciativa,de%20vida%20de%20su%20poblaci%C3%B3n.)
-   Amazonia Siempre. BID. [*Link*](https://www.iadb.org/es/quienes-somos/tematicas/Amazonia).
-   Amazonía +, Unión Europea. [*Link*](https://www.fiiapp.org/proyectos_fiiapp/programa-amazonia/).
-   GEF. Amazon. .
-   Fulbright Amazonia. [*Link*](https://www.fulbrightprogram.org/amazonia/) ([Policy brief](https://www.fulbrightprogram.org/amazonia/)).
-   Buscadores de proyectos
    -   Climate project explorer. [*Link*](https://climateprojectexplorer.org/geographies/colombia).

# **Organizaciones**

-   Organización del Tratado de Cooperación Amazónica. OTCA. [*Link*](http://otca.org/).

# Cursos de GRD con enfoque indigena

-   Integrating Gender and Indigenous Factors into Locally-Led Adaptation. [*Link*](https://ap-plat.nies.go.jp/adaptation_literacy/resources/e_learning/ait_lla/index.html)*.*
-   Mitigation Planning for Tribal Communities. FEMA. [*Link*](https://training.fema.gov/is/courseoverview.aspx?code=IS-350&lang=en)*.*

# **Ciencia**

-   Panel Científico para el Amazonas (SPA). [*Link*](https://www.laamazoniaquequeremos.org/).
-   Principios CREA para la Gobernanza de Datos Indigenas. [*Link*](https://www.gida-global.org/care).
-   Incendios forestales
    -   Global burned area increasingly explained by climate change. 2024. Nature. [*Link*](https://www.nature.com/articles/s41558-024-02140-w)
-   Cambio climático
    -   South America is becoming warmer, drier, and more flammable. Nature. 2024. [*Link*](https://www.nature.com/articles/s43247-024-01654-7).

# **Financiación**

-   Multilateral climate funds. [*Link*](https://climateprojectexplorer.org/)
-   ERC-funded research on the Amazon. Euraxess. [*Link*](https://euraxess.ec.europa.eu/worldwide/lac/events/webinar-showcasing-erc-funded-research-amazon).
-   Belmont Forum. Tropical Forest. [*Link*](https://belmontforum.org/cras#forests)
-   Biodiversa+. Biodiversity and Transformative Change. [*Link*](https://www.biodiversa.eu/2024/06/11/2024-2025-joint-call/).

# **Mercados, cadenas comerciales**

-   La UE y los países latinoamericanos ponen el foco en la protección de la Amazonia. El Pais. 2023/07. [*Link*](https://elpais.com/america-futura/2023-09-18/la-ue-y-los-paises-latinoamericanos-ponen-el-foco-en-la-proteccion-de-la-amazonia.html).
-   Europa adopta una ley pionera contra la deforestación pese a los recelos de Brasil y el sureste asiático. El Pais. 2023/07. [*Link*](https://elpais.com/clima-y-medio-ambiente/2023-05-16/europa-adopta-una-ley-pionera-contra-la-deforestacion-pese-a-los-recelos-de-brasil-y-el-sureste-asiatico.html).
-   Brasil, México, Colombia, Indonesia y otros 13 países reclaman a la UE que reconsidere su ley contra la deforestación. El Pais. 2023/07. [*Link*](https://elpais.com/clima-y-medio-ambiente/2023-09-11/brasil-mexico-colombia-indonesia-y-otros-13-paises-reclaman-a-la-ue-que-reconsidere-su-ley-contra-la-deforestacion.html).
-   La UE y los países latinoamericanos ponen el foco en la protección de la Amazonia. El Pais. 2023/07. [*Link*](https://elpais.com/america-futura/2023-09-18/la-ue-y-los-paises-latinoamericanos-ponen-el-foco-en-la-proteccion-de-la-amazonia.html).
-   Action needed to make carbon offsets from forest conservation work for climate change mitigation. 2023. Science. [*Link*](https://www.science.org/doi/10.1126/science.ade3535).

# **MOOCS**

-   The Living Amazon: Science, Cultures and Sustainability in Practice. EDx. [*Link*](https://www.edx.org/learn/sustainability/sdg-academy-the-living-amazon-science-cultures-and-sustainability-in-practice)

# **Lecturas de ciencia**

-   Trouble in the Amazon. The rainforest is starting to release its carbon. Is it heading towards a tipping point? Nature, 2023. [*Link*](https://www.nature.com/immersive/d41586-023-02599-1/index.html).
-   Advancing transdisciplinary research on social-ecological system transformations in the Global South. 2023. [*Link*](https://www.tandfonline.com/journals/tbsm22/collections/social-ecological-system).
-   Exploring climate extremes in Brazil’s Legal Amazon. 2023. [*Link*](https://link.springer.com/article/10.1007/s00477-023-02634-7).
-   Time to support Indigenous science. Science, 2024. [*Link*](https://www.science.org/doi/10.1126/science.ado0684)
-   How a surge in organized crime threatens the Amazon. Nature, 2024. [*Link*](https://www.nature.com/articles/d41586-023-04087-y).
-   Critical transitions in the Amazon forest system. Nature, 2024. [*Link*](https://www.nature.com/articles/s41586-023-06970-0).