---
title: "Amenazas extraterrestres"
format: html
editor: visual
---

## Instituciones nacionales

-   Comisión Colombiana del Espacio. [*Link*](https://cce.igac.gov.co/)
-   Fuerza Aerospacial
-   IGAC.
    -   Office for Outer Space Affairs UN-SPIDER Knowledge Portal. [*Link*](https://www.un-spider.org/es/network/regional-support-offices/oficina-regional-de-apoyo-en-colombia) , [*Link*](https://www.igac.gov.co/transparencia-y-acceso-a-la-informacion-publica/entidades/onu-spider)
-   AstroCo. [*Link*](https://astroco.org)).
    -   Plan de Acción para Colombia ante la amenaza de asteroides (el caso del Asteroide 2024 YR4). 2025. [*Link*](https://drive.usercontent.google.com/download?id=1eaYndepOM4IfbjZ3QHVqfWJnJ1AbTUpV&authuser=0&acrobatPromotionSource=GoogleDriveListView)
-   CONPES Desarrollo Espacial. [*Link*](http://cce.gov.co/prensa/Paginas/Politica-de-Desarrollo-Espacial-CONPES-3983.aspx).

## Instituciones internacionales

-   ONU. Oficina para Asuntos del Espacio Ultraterrestre. [*Link*](https://www.un-spider.org/). [*Link*](https://un-spider.org/sites/default/files/1_ONU_SPIDER_JCV.pdf).
-   Oficina Regional de Apoyo en Colombia. [*Link*](https://www.un-spider.org/es/network/regional-support-offices/oficina-regional-de-apoyo-en-colombia).
-   ONU, Near-Earth Objects (NEOs). [*Link*](https://www.unoosa.org/oosa/sk/ourwork/topics/neos/index.html#:~:text=A%20near%2DEarth%20object%20is,kilometres%2C%20of%20the%20Earth's%20orbit.)
-   International Asteroid Warning Network (IAWN). [*Link*](https://iawn.net/index.shtml)
-   NASA, Saving earth form asteroids. [*Link*](https://www.nasa.gov/feature/saving-earth-from-asteroids). [*Link*](https://ntrs.nasa.gov/api/citations/20180000805/downloads/20180000805.pdf).
-   The risk from space. Prevention web. [*Link*](https://www.preventionweb.net/files/11476_RichardCrowther2.pdf).
-   Fireballs Nasa. [*Link*](https://cneos.jpl.nasa.gov/fireballs/).

## Amenazas extraterrestres

-   EM-DAT Classification System. [*Link*](https://doc.emdat.be/docs/data-structure-and-content/disaster-classification-system/).
-   7th IAA Planetary Defense Conference and 2017 IAA Planetary Defense Conference
    -   [Session 1: Key International and Political Developments](https://www.youtube.com/live/yO8coRPnBiI)
    -   [Session 2: Advancements and Progress in NEO Discovery](https://www.youtube.com/live/kI9oeBob4x8?si=qbe0XiVCaOSyQK0C)

::: {layout-ncol="2"}

{{< video "https://youtu.be/vLF4EF2LYVQ" >}} La amenaza del impacto de asteroides cercanos a la Tierra

{{< video "https://youtu.be/543FvG9vIEY" >}} Biografía de un impacto: el meteorito ruso \| Ciencia en Bicicleta \| Planetario Medellín

{{< video "https://youtu.be/dpmXyJrs7iU" >}} Meteor Hits Russia Feb 15, 2013

{{< video "https://youtu.be/Q9KwK0izt5c" >}} [NASA \| NPP Sees Aftermath of the Chelyabinsk Meteor](https://youtu.be/Q9KwK0izt5c)

{{< video "https://youtu.be/wkqoUXds26U" >}} 7th IAA Planetary Defense Conference Day 2: Discovery and Characterization

:::

## Evaluación del riesgo

-   Risk assessment for asteroid impact threat scenarios. 2024. [*Link*](https://www.sciencedirect.com/science/article/pii/S0094576523006793)
-   Introduction to Asteroid Impact Risk Assessment. NASA. [*Link*](https://ntrs.nasa.gov/api/citations/20230001034/downloads/PDC23-ImpactRiskIntro-ReviewDraft-20230117.pdf)
-   A probabilistic asteroid impact risk model: assessment of sub-300 m impacts. 2027. [Link](https://www.sciencedirect.com/science/article/pii/S0019103516307126)
-   7th IAA Planetary Defense Conference Day 2: Discovery and Characterization
    -   [Session 8 Impact Risk Assessment & Decision to Act](https://www.youtube.com/live/dTrtKSAZaRk)

## Comunicación del riesgo

-   7th IAA Planetary Defense Conference Day 2: Discovery and Characterization
    -   [Session 9: Public Education & Communication](https://www.youtube.com/live/99UpnKwcBKI)

::: {layout-ncol="2"}
{{< video "https://youtu.be/bYbIPDkcsyQ" >}} 7th IAA Planetary Defense Conference Day 5: Decision to Act and Public Engagement

:::

## Reducción del riesgo

-   7th IAA Planetary Defense Conference Day 2: Discovery and Characterization
    -   [Session 4: Deflection and Disruption Models & Testing](https://www.youtube.com/live/EmuVrVCGwjU)

## Manejo de desastres

-   7th IAA Planetary Defense Conference Day 2: Discovery and Characterization
    -   [Session 6: Impact Consequences](https://www.youtube.com/live/2geYwwwpwLA)
    -   [Session 7: Disaster Response](https://www.youtube.com/live/yPnzku_vTRQ)
    -   [Session 10: Threat Response Exercise](https://www.youtube.com/live/3q7p8djdGD8)

::: {layout-ncol="2"}
{{< video "https://youtu.be/Cj9ikPkjYt8" >}} 7th IAA Planetary Defense Conference Day 4: Impact Effects and Disaster Management

:::

## Ciencia

-   9th IAA Planetary Defense Conference. [*Link*](https://iaaspace.org/event/9th-iaa-planetary-defense-conference-2025/) [*Link*](https://www.youtube.com/live/DpMormI8GOQ?si=_evDw7bNcAsr91ch&t=4110)

## Lecturas

-   Webinar - ¿Por qué desviar asteroides y estudiar sus meteoritos? [*Link*](https://www.youtube.com/watch?v=OcPstsPpeoM).
-   Podcast. Desafíos y soluciones en la detección de asteroides. UNAL, 2025. [*Link*](https://radio.unal.edu.co/detalle/desafios-y-soluciones-en-la-deteccion-de-asteroides).
-   El impacto de pequeños asteroides sobre la Tierra. 2015. *Revista Investigación y Ciencia*. [*Link*](https://www.investigacionyciencia.es/files/21228.pdf).
-   Meteorite impacts in the ocean: the danger of tsunamis on the coast of Buenos Aires Province, Argentina. 2020. [*Link*](https://doi.org/10.1007/s11069-020-04086-6)
-   Can we predict the impact conditions of metre-sized meteoroids? 2019. [*Link*](https://academic.oup.com/mnrasl/article/486/1/L69/5481033).
-   Segundo festival colombiano del asteroide. [*Link*](https://accefyn.com/microsites/nodos/astroco/ii-festival-colombiano-del-asteroide/) -
-   **Algunos expertos**
    -   Josep M. Trigo-Rodriguez. España. [*Link*](http://www.spmn.uji.es/ESP/trigo.html). [*Link*](https://scholar.google.com/citations?user=9zFTEQkAAAAJ&hl=en).
    -   Jorge Zuluaga. Colombia. [*Link*](https://scholar.google.com/citations?hl=en&user=qpGVqNwAAAAJ&view_op=list_works&sortby=pubdate).
    -   Pablo Restrepo. Colombia. [*Link*](https://scholar.google.com/citations?hl=en&user=c4zrU20AAAAJ&view_op=list_works&sortby=pubdate).