---
title: "Avenidas Torrenciales"
format: html
editor: visual
---

## Instituciones nacionales

-   UNGRD. [*Link*](https://portal.gestiondelriesgo.gov.co/)
-   

## Instituciones internacionales

## Amenaza por avenidas torrenciales

Lecturas:

-   Guía metodológica para zonificación de amenaza por avenidas torrenciales. 2021. [*Link*](https://libros.sgc.gov.co/index.php/editorial/catalog/book/75).

-   Definición y clasificación de las avenidas torrenciales y su impacto en los Andes colombianos. 2020. [*Link*](https://doi.org/10.15446/rcdg.v29n1.72612).

-   Real-Time Early Warning System Design for Pluvial Flash Floods—A Review. 2018. [*Link*](https://doi.org/10.3390/s18072255).

::: {layout-ncol="2"}
{{< video "https://youtu.be/Ojtm4RA-faQ" >}} Lanzamiento guía metodológica para zonificación de amenaza por avenidas torrenciales

{{< video "https://youtu.be/I1jr1ieIxYk" >}} Avenidas torrenciales y movimientos en masa en los Andes colombianos

Amenaza por inundaciones
:::

## Evaluación del riesgo por avenidas torrenciales

::: {layout-ncol="2"}
{{< video "https://youtu.be/swr4NlX2bVE" >}}

Evaluación del riesgo por incendios forestales.
:::

## Comunicación del riesgo por avenidas torrenciales

-   

::: {layout-ncol="2"}
{{< video "https://youtu.be/8u3F5f47i_M" >}}

Comunicación del riesgo por incendios forestales.
:::

## Reducción del riesgo de avenidas torrenciales

-   P

## Manejo de desastres por avenidas torrenciales

-   Red

::: {layout-ncol="2"}
{{< video "https://vimeo.com/701418128" >}}
:::

## Lecturas

-   The

## **Entrenamiento**

-   Cope

## Repositorios

-   Download

## Videos

::: {layout-ncol="2"}
{{< video " " >}}
:::