---
title: "Ciencia y tecnología"
format: html
editor: visual
---

## Cursos en ciencia y tecnología en grd

-   Risk-informed governance and innovative technology for disaster risk reduction and resilience. UNDRR. [*Link*](https://unsec.unssc.org/course/view.php?id=309).
    -   Unit 1: Risk-Informed Governance for DRR and Resilience
    -   Unit 2: Science Technology and Government Innovation in Public Governance for DRR and Resilience
    -   Unit 3: Practical and Planned Application of Emerging Technology and Government Innovation for DRR and Resilience
    -   Unit 4: Implementation of Emerging Technologies and Government Innovation for DRR and Resilience
    -   Unit 5: Reflecting on and Planning for Monitoring and Evaluation (optional)
    -   Unit 6:Case Studies - Application of Technology for Reducing Disaster Risks

::: {layout-ncol="2"}
{{< video "https://youtu.be/LnsbKliwaog" >}} eLearning Course: Risk-informed Governance and Innovative Technology for DRR and Resilience

{{< video "https://youtu.be/tiEh5vivKjU" >}} Session 6: Government Innovation and Technologies for DRR and Resilience (22 Sep 2020)
:::

## **Lecturas de referencia**

-   **Objetivos de desarrollo sostenible y reducción del riesgo de desastres**.
    -   Los ODS. [*Link*](https://www.un.org/sustainabledevelopment/es/).
    -   Comunicado de las Naciones Unidas y relación de la RRD con ODS. .
-   **Libros de referencia en GDR Colombia**
    -   **Investigaciones en gestión del riesgo de desastres para Colombia: avances, perspectivas y casos de estudio**. UNGRD. 2021. [*Link*](https://repositorio.gestiondelriesgo.gov.co/handle/20.500.11762/32470).
    -   **Evaluación de la gobernanza del riesgo en Colombia**, OECD (2019). OECD Publishing, Paris, [Link](https://doi.org/10.1787/f4ff1a69-es). [Link](https://www.oecd.org/countries/colombia/evaluacion-de-la-gobernanza-del-riesgo-en-colombia-f4ff1a69-es.htm). [Link](https://books.google.com.co/books?id=QnmtDwAAQBAJ).
    -   **Atlas de Riesgo de Colombia: revelando los desastres latentes.2018**. Unidad Nacional para la Gestión del Riesgo de Desastres (UNGRD). 2018. [*Link*](https://repositorio.gestiondelriesgo.gov.co/handle/20.500.11762/27179).
    -   **Análisis de la gestión del riesgo de desastres en Colombia**. GFDRR, BM. [*Link*](https://repositorio.gestiondelriesgo.gov.co/handle/20.500.11762/18426)
    -   **La gestión del riesgo de desastres**. Narváez et al. 2009. [*Link*](https://repositorio.gestiondelriesgo.gov.co/handle/20.500.11762/19759).
    -   **Desastres de origen natural en Colombia, 1979-2004**. Michel Hermelín. 2005. [*Link.*](https://books.google.com.co/books?hl=es&lr=&id=FhxXMyuLJ8oC&oi=fnd&pg=PA121&dq=desastres+wilches&ots=DhOw84EKV2&sig=6-ZubX3xhPmog7NAQySM3daT3Vk&redir_esc=y#v=onepage&q&f=false)
-   **Documentos de GRD de la OCDE**
    -   Disaster preparedness and response in Colombia. 2019. [*Link*](https://doi.org/10.1787/529133b5-en).
    -   Disaster risk identification and assessment in Colombia. 2019. [*Link*](https://doi.org/10.1787/57d2d1a7-en).
    -   Disaster recovery and reconstruction in Colombia. 2019. [*Link*](https://doi.org/10.1787/9cf613fe-en).
    -   Disaster risk reduction in Colombia. 2019. [*Link*](https://doi.org/10.1787/0697460c-en).
    -   Colombia’s strategic framework for disaster risk governance. 2019. [*Link*](https://doi.org/10.1787/ac20a9c8-en).
-   **Libros de referencia internacionales**
    -   The Routledge Handbook of Hazards and Disaster Risk Reduction. 2012. [*Link*](https://www.routledgehandbooks.com/doi/10.4324/9780203844236).
    -   The Routledge Handbook of Disaster Risk Reduction Including Climate Change Adaptation. 2017. [*Link*](https://books.google.com.co/books?id=4mgPEAAAQBAJ).
    -   Crisis and Emergency Management: Theory and Practice, Second Edition. 2017. [*Link*](https://books.google.com.co/books?id=cq1JDwAAQBAJ).
    -   Extreme Natural Hazards, Disaster Risks and Societal Implications. 2014. [*Link*](https://books.google.com.co/books?hl=es&lr=&id=XzE4AwAAQBAJ).
    -   Encyclopedia of Natural Hazards. 2013. [*Link*](https://link.springer.com/referencework/10.1007/978-1-4020-4399-4).
    -   Encyclopedia of Natural Hazard Science. OUP. [*Link*](https://oxfordre.com/naturalhazardscience/).
    -   Education for Sustainable Development and Disaster Risk Reduction. 2014. [*Link*](https://books.google.com.co/books?id=SCM9BAAAQBAJ).
    -   Sustainable Development and Disaster Risk Reduction. 2016. [*Link*](https://books.google.com.co/books?id=79bjCgAAQBAJ).
    -   Natural Hazards, Second Edition: Explanation and Integration. 2017. [*Link*](https://books.google.com.co/books?hl=es&lr=&id=gw_kDAAAQBAJ&oi=fnd&pg=PP1&dq=Natural+Hazard+risk&ots=DJenfdnkZr&sig=uZnu_qPSrYCKlBryI0KZc6qEdDY&redir_esc=y#v=onepage&q&f=false).
    -   Natural Hazards and Disasters. Fifth Ed. Hyndman. 2017. [*Link*](https://books.google.com.co/books?id=nMgaCgAAQBAJ).
    -   The Role of Ecosystems in Disaster Risk Reduction. 2013. [*Link*](https://books.google.com.co/books?id=9mTRjKmN1LwC). \*\*\*
    -   Social Vulnerability to Disasters, Second Edition. 2013. [*Link*](https://books.google.com.co/books?id=onAWhiaVsuIC&printsec=frontcover&dq=social+vulnerability+to+disasters&hl=es-419&sa=X&redir_esc=y#v=onepage&q&f=false).
    -   Systemic Risk: History, Measurement and Regulation. 2019. [*Link*](https://www.worldscientific.com/worldscibooks/10.1142/11301#t=aboutBook).
    -   Systemic Disaster Risk Handbook. [*2021*](https://knowledge.aidr.org.au/resources/handbook-disaster-risk/)
    -   Integrated Research on Disaster Risks. Springer. 2021. [*Link*](https://link.springer.com/book/10.1007/978-3-030-55563-4#:~:text=Integrated%20Research%20on%20Disaster%20Risk,Disaster%20Risk%20Reduction%20(UNDRR).).
    -   Natural Climate Solutions Handbook: A Technical Guide for Assessing NatureBased Mitigation Opportunities in Countries. 2021. [*Link*](https://www.nature.org/content/dam/tnc/nature/en/documents/TNC_Natural_Climate_Solutions_Handbook.pdf).
    -   The Invention of Disaster. Power and Knowledge in Discourses on Hazard and Vulnerability. Routledge. 2022. [*Link*](https://www.routledge.com/The-Invention-of-Disaster-Power-and-Knowledge-in-Discourses-on-Hazard-and/Gaillard/p/book/9781138805620#).
    -   Creating Resilient Futures. Integrating Disaster Risk Reduction, Sustainable Development Goals and Climate Change Adaptation Agendas. 2022. Springer. [*Link*](https://link.springer.com/book/10.1007/978-3-030-80791-7).
    -   Handbook on Climate Change and Disasters. 2023. [*Link*](https://books.google.com.co/books?id=vW-VEAAAQBAJ&lpg=PP1&hl=es&pg=PR5#v=onepage&q&f=false).
    -   Disaster Risk Reduction for Resilience. Climate Change and Disaster Risk Adaptation. 2023. [*Link*](https://link.springer.com/book/10.1007/978-3-031-22112-5)
    -   Física del caos en la predicción meteorológica. 2023. AEMET España. [*Link*](https://www.aemet.es/es/conocermas/recursos_en_linea/publicaciones_y_estudios/publicaciones/detalles/Fisica_del_caos_en_la_predicc_meteo).
-   **Lecturas sobre conceptos**
    -   Managing the Risks of Extreme Events and Disasters to Advance Climate Change Adaptation. IPCC. 2012. [*Link*](https://www.ipcc.ch/report/managing-the-risks-of-extreme-events-and-disasters-to-advance-climate-change-adaptation/).
        -   Chapter 2. Determinants of risk: exposure and **vulnerability**. [*Link*](https://www.researchgate.net/publication/244062037_Determinants_of_risk_exposure_and_vulnerability).
        -   Gestión de los riesgos de fenómenos meteorológicos extremos y desastres para mejorar la adaptación al cambio climático. IPCC, 2012. [*Link*](https://www.ipcc.ch/site/assets/uploads/2018/03/IPCC_SREX_ES_web-1.pdf). [*Link*](https://www.ipcc.ch/report/managing-the-risks-of-extreme-events-and-disasters-to-advance-climate-change-adaptation/).
    -   Briefing note on systemic risk. UNDRR, 2022. [*Link*](https://floodresilience.net/resources/item/briefing-note-on-systemic-risk/).
    -   A framework for complex climate change risk assessment. One Earth. 2021. [Link](https://www.cell.com/one-earth/fulltext/S2590-3322(21)00179-2).
-   **Otros documentos de política pública e iniciativas públicas relacionadas con la GRD.**
    -   CONPES 3920. POLÍTICA NACIONAL DE EXPLOTACIÓN DE DATOS (BIG DATA). [*Link*](https://colaboracion.dnp.gov.co/CDT/Conpes/Econ%C3%B3micos/3920.pdf).
    -   Equipo de Innovación Pública. DNP. [*Link*](https://www.dnp.gov.co/programas/desarrollo-empresarial/Paginas/Innovacion-Publica.aspx).
    -   Encuesta Nacional de Salud. [*Link*](https://clustersalud.americaeconomia.com/gestion-hospitalaria/colombia-presentan-recomendaciones-basadas-en-encuesta-nacional-en-salud).
-   **En medios**
    -   The climate disaster is here. The Guardian. [*Link*](https://www.theguardian.com/environment/ng-interactive/2021/oct/14/climate-change-happening-now-stats-graphs-maps-cop26)
    -   El volcán al desnudo. El País. [*Link*](https://elpais.com/ciencia/2021-11-06/el-volcan-al-desnudo-como-interpretar-las-senales-de-la-erupcion-de-la-palma.html).
-   **Los desastres no son naturales**
    -   There is no natural disasters. The elements of disaster. [*Link*](https://www.preventionweb.net/news/there-are-no-natural-disasters).
    -   Los desastres no son naturales. La Red. 1993. [*Link*](https://www.desenredando.org/public/libros/1993/ldnsn/LosDesastresNoSonNaturales-1.0.0.pdf).
    -   Beyond «natural-disasters-are-not-natural»:the work of state and nature after the 2010 earthquake in Chile. JPE. 2016. [*Link*](https://journals.uair.arizona.edu/index.php/JPE/article/view/20181/19809).
    -   <https://nonaturaldisasters.com/>

::: {layout-ncol="2"}
{{< video "https://www.youtube.com/watch?v=5HG0CHm6M5o" >}} Systemic Disaster Risk Handbook

{{< video "https://www.youtube.com/watch?v=5pnQKSV5hn4" >}} Climate change and disaster risk management

{{< video "https://www.youtube.com/watch?v=9nrPQNHwvCc" >}} Los desastres no son naturales
:::

## **Educación**

-   **Lecturas educación**
    -   IFRC (Federación Internacional de Sociedades de la Cruz Roja y Media Luna Roja). 2011. Guía: Para la sensibilización y educación pública sobre la reducción de riesgos de desastres. Ginebra, Suiza. [*Link*](https://www.preventionweb.net/files/61592_302200publicawarenessddrguidees.pdf).
    -   Plan nacional de capacitación y formación en gestión del riesgo de desastres 2022-2030. [*Link*](https://repositorio.gestiondelriesgo.gov.co/handle/20.500.11762/38718?fbclid=IwAR18I1UGQjs6QY50qGJiSpHwZSovFTo_q9wL8p4Q0k7jh9bBsOUFgX5aqrk).
    -   Postgraduate modules, University College London. [*Link*](https://www.ucl.ac.uk/risk-disaster-reduction/study/postgraduate-modules).

## **Entrenamiento**

-   Disaster Reduction Learning Center (DRLC). [*Link*](https://www.jica.go.jp/english/activities/issues/disaster/disaster.html).

-   FEMA. [*Link*](https://training.fema.gov/ndemu/curriculum/)

-   Disaster Risk Management Training Center. [*Link*](https://drmkc.jrc.ec.europa.eu/).

    -   Training Corner. [*Link*](https://drmkc.jrc.ec.europa.eu/science-for-drm/training-corner).

-   Disaster Risk Management Training online series 2022. European Commision. [*Link*](https://drmkc.jrc.ec.europa.eu/science-for-drm/training-corner/disaster-risk-management-training-online-series-2022).

    ## **MOOCS**

    -   Bushfires: Response, Relief and Resilience. [*Link*](https://www.futurelearn.com/courses/bushfires).
    -   CONVERGE Training Modules. [*Link*.](https://converge.colorado.edu/resources/training-modules)
    -   Comunicando el cambio climático de manera efectiva. CDKN. [*Link*](https://cdkn.org/comunicando/?loclang=es_es&fbclid=IwAR0sQ3LypFp0Atq5eOtWgPrOisQkKmMeBlaS-woYhp5JvqKFE122-_LIur8).
    -   Disasters and Ecosystems: Resilience in a Changing Climate. [*Link*](https://www.youtube.com/playlist?list=PLH___LL2LODuduh-dhLSFKOhyJZtRnIc_).
    -   Disaster Preparedness. [*Link*](https://www.coursera.org/learn/disaster-preparedness).
    -   Disaster Risk Management and Korean Policies. [*Link*](https://www.coursera.org/learn/disaster-risk-management-korean-policies).
    -   Evaluación de peligros y riesgos por fenómenos naturales. [*Link*](https://www.coursera.org/learn/riesgos-fenomenos-naturales/home/welcome).
    -   Flood Risk Management. [*Link*](https://www.edx.org/es/course/flood-risk-management).
    -   Fundamentals of Remote Sensing. [*Link*](https://arset.gsfc.nasa.gov/webinars/fundamentals-remote-sensing).
    -   Natural Disasters. [*Link*](https://www.edx.org/es/course/natural-disasters). [*Link*](http://www.meteo.mcgill.ca/atoc185/).
    -   Open learning campus. World Bank. [*Link*](https://olc.worldbank.org/content/resilience-and-disaster-risk-management-learning-lab)
    -   Regional DDR e-learning platform. [*Link*](https://courses.adpc.net/).
    -   A Resilient Future: Science and Technology for Disaster Risk Reduction. [*Link*](https://www.edx.org/es/course/a-resilient-future-science-and-technology-for-disa).
    -   Resilience – The art of coping with disasters. [*Link*](https://www.edx.org/es/course/resilience-the-art-of-coping-with-disasters).
    -   Social Vulnerability and Disasters. Converge. [*Link*](https://converge-training.colorado.edu/courses/vulnerable-populations/).
    -   Tsunamis and Storm Surges: Introduction to Coastal Disasters. [*Link*](https://www.edx.org/es/course/tsunamis-and-storm-surges-introduction-to-coastal).
    -   UNESCO. Online courses to promote disaster risk reduction awareness. [*Link*](https://en.unesco.org/greencitizens/stories/online-courses-promote-disaster-risk-reduction-awareness). [*Link*](http://elearning.unep.org/moocs/courses).
    -   When Disaster Meets Conflict. [*Link*](https://www.coursera.org/learn/whendisastermeetsconflict).

-   **En español**

    -   Gestión integral del riesgo de desastres. [*Link*](https://www.coursera.org/learn/gestion-riesgo/home/welcome)
    -   Género-Diversidad en la reducción del riesgo de desastres y cambio climático. [*Link*](https://es.grripp.net/cursoonline/1-video-introductorio).
    -   Análisis del Riesgo de Desastres y Cambio Climático en Proyectos de Infraestructura. BID. [*Link*](https://cursos.iadb.org/es/temas/infraestructura/analisis-riesgo-desastres-cambio-climatico-proyectos-infraestructura).

-   **E-learning**

    -   USGS- Spatial Data. [*Link*](https://lpdaac.usgs.gov/resources/e-learning/).
    -   NASA – Earth Science, Applied Science online trainings [*Link*](https://appliedsciences.nasa.gov/join-mission/training?program_area=14).
    -   Teaching climate. Climate Gov. [*Link*](https://www.climate.gov/teaching).
    -   Coastal Aquaculture Planning Portal (CAPP). [*Link*](https://coastalscience.noaa.gov/research/marine-spatial-ecology/coastal-aquaculture-planning-portal-capp/).
    -   UICN. Water. [*Link*](https://learningelc.org/course/index.php?categoryid=6).

-   **Seminarios web**

    -   Riesgo por cambio climático en Colombia. Estrategia Climática de Largo Plazo Colombia E2050. [*Link*](https://youtu.be/4v9T0QaI7ZU).
    -   Converge Webinar series. [*Link*](https://converge.colorado.edu/communications/webinar-series).
    -   APRU Multi-Hazards Webinar Series. [*Link*](https://apru.org/event/the-apru-multi-hazards-webinar-series-a-new-approach-for-disaster-risk-management-after-covid-19/).
    -   Knowledge Action Network on Emergent Risks and Extreme Events. [*Link*](https://www.risk-kan.org/webinars/)

-   **Recursos**

    -   The Climate Reanalyzer. Climate.gov. [*Link*](https://www.climate.gov/teaching/resources/climate-reanalyzer-0). [*Link*](https://climatereanalyzer.org/).

-   **The Australian Disaster Resilience Knowledge Hub**

    -   Emergency planning collection. [*Link*](https://knowledge.aidr.org.au/collections/emergency-planning/).
    -   Disasters. [*Link*](https://knowledge.aidr.org.au/disasters/).
    -   Glossary. [*Link*](https://knowledge.aidr.org.au/glossary/).
    -   Emergency Management Library. [*Link*](https://knowledge.aidr.org.au/collections/emergency-management-library/).
    -   Recovery Matters webinar series. [*Link*](https://knowledge.aidr.org.au/resources/recovery-matters-webinar-series/?utm_source=Updates+from+AIDR&utm_campaign=f666ebcb63-EMAIL_CAMPAIGN_2020_03_10_03_44_COPY_01&utm_medium=email&utm_term=0_a0a8e928c9-f666ebcb63-184368417#story).

-   **The Australian Institute for Disaster Resilience**. [*Link*](https://www.aidr.org.au/)

::: {layout-ncol="2"}
{{< video "https://www.youtube.com/watch?v=1Aq_2kEL4yo" >}}
:::

-   **Museos de ciencia**
-   **Expertos**:
    -   John Falk. [*Link*](https://scholar.google.com/citations?user=1hytoUMAAAAJ&hl=en&oi=sra)
    -   Falk, J. H., & Dierking, L. D. (2013). The Museum Experience Revisited. [*Link*](https://doi.org/10.4324/9781315417851).
-   **Lecturas**
    -   Barriault, C., & Pearson, D. (2010). Assessing exhibits for learning in science centers: A practical tool. Visitor Studies, 13(1), 90–106. [*Link*](https://doi.org/10.1080/10645571003618824).
    -   Ma, J., Shahar, E., Eliceiri, K., Mehta, G., & Yu, K. (2019). Shedding light: Integrating bioimaging technologies into the design of an interactive museum exhibit. DIS 2019 – Proceedings of the 2019 ACM Designing Interactive Systems Conference. [*Link*](https://doi.org/10.1145/3322276.3322299).
    -   King, D., Ma, J., Armendariz, A., & Yu, K. (2018). Developing Interactive Exhibits with Scientists: Three Example Collaborations from the Life Sciences Collection at the Exploratorium. Integrative and Comparative Biology, 58(1), 94–102. [*Link*](https://doi.org/10.1093/icb/icy010).
    -   Kratz, S. & Merritt E. (2011). Museums and the future of education. On the Horizon, 19 (3), 188-195
    -   MacDonald, E., Johnson, V., Gillies, M., & Johnston, D. (2017). The impact of a museum-based hazard education program on students, teachers and parents. *International Journal of Disaster Risk Reduction*, *21*, 360–366.[*Link*.](https://doi.org/10.1016/j.ijdrr.2017.01.010)
    -   Martin, A. J., Durksen, T. L., Williamson, D., Kiss, J., & Ginns, P. (2016). The role of a museum-based science education program in promoting content knowledge and science motivation. *Journal of Research in Science Teaching*, *53* (9), 1364–1384. [*Link*](https://doi.org/10.1002/tea.21332).
    -   Motschnig, R. & Cornelius-White J. (2012). Experiential/Significant Learning. Encyclopedia of the Sciences of Learning. Springer US. pp: 1219-1223. [*Link*](https://doi.org/10.1007/978-1-4419-1428-6_574)
    -   Museums and the future of education. 2011. [*Link*](https://www.emerald.com/insight/content/doi/10.1108/10748121111163896/full/html)
-   **Qué aprenden o recuerdan los visitantes en un museo de ciencia**
    -   Mensajes que apoyan sus necesidades e intereses.
    -   Mensajes que son novedosos, extraños o interesantes.
    -   Mensajes que contienen un alto contenido emocional para el individuo.
    -   Mensajes respaldados por experiencias posteriores (medición *ex post facto* ).

::: {layout-ncol="2"}
{{< video "https://www.youtube.com/watch?v=m-p8kUrUWd4" >}}
:::

**CIENCIA, TECNOLOGÍA E INNOVACIÓN** **EN GRD**

::: {layout-ncol="2"}
{{< video "https://www.youtube.com/watch?v=T4TVVT2_x3M" >}}

{{< video "https://www.youtube.com/watch?v=BNIT8mOdYRE" >}}
:::

-   

    ## **Institutos y organizaciones internacionales**

    -   APRU – Association of Pacific Rim Universities. [*Link*](https://apru.org/).
    -   Center for Emergency Management and Homeland Security. ASU. [*Link*](https://cemhs.asu.edu/).
    -   Columbia Climate School. [*Link*](https://climate.columbia.edu/research).
    -   DesignSafe CI. [*Link*](https://www.designsafe-ci.org/#learning)
    -   FAO Ciencia, tecnología e innovación. [*Link*](https://www.fao.org/science-technology-and-innovation/about/es).
    -   GADRI – Global Aliance of Disaster Risk Institutes. [*Link*](https://gadri.net/).
    -   Global Assessment Repo. [Link](https://gar.unisdr.org/).
    -   Harvard Humanitarian Initiative. [*Link*](https://hhi.harvard.edu/).
    -   Hazards & Vulnerability Research Institute. [Link](http://artsandsciences.sc.edu/geog/hvri/front-page). [Link](https://www.youtube.com/channel/UCQ22ABWTJkxolMXLAnLKMLQ/videos).
    -   I ntegrated Research on Disaster Risk International Center of Excellence Vulnerability and Resilience Metrics. [*Link*](http://www.irdrinternational.org/)
    -   Integrated Research on Disaster Risk (IRDR). [*Link*](https://www.irdrinternational.org/) [*Link*](https://council.science/what-we-do/research-programmes/thematic-organizations/integrated-research-on-disaster-risk-irdr/).
    -   International Science Council. [Link](https://council.science/).
    -   IRIDes – International Research Institute for Disaster Science. [*Link*](https://irides.tohoku.ac.jp/eng/)
    -   Natural Hazards Center. [*Link*](https://hazards.colorado.edu/news/center-news).
    -   CONVERGE. [*Link*](https://converge.colorado.edu/).
        -   Past Webinar Recordings. [*Link*](https://hazards.colorado.edu/training/webinars/pastrecordings).
            -   CONVERGE Training Modules. [Link.](https://converge.colorado.edu/resources/training-modules)
    -   NIED, Science for resilience. Japón. [*Link*](https://www.bosai.go.jp/e/index.html).
    -   Resilient America. [*Link*](https://sites.nationalacademies.org/pga/resilientamerica/)

-   **Latinoamerica**

    -   CIGIDEN Chile. [*Link*](https://www.cigiden.cl/).
    -   CEPREDENAC. [*Link*](http://www.cepredenac.org/)
    -   La Red. Desenredando. [*Link*](https://www.desenredando.org/).
    -   Senapred. [*Link*](https://senapred.cl/).

-   **Redes UNDRR**

    -   PreventionWeb community. [*Link*](https://cc.preventionweb.net/).

-   **Plataformas de análisis de riesgos**

    -   Plataforma CAPRA – Uniandes. [*Link*](https://ecapra.org/es).
    -   Riesgos.de. [*Link*](https://www.riesgos.de/de/).

-   **Sistemas de información de Colombia**

    -   Consolidados de emergencia y desastres. [*Link*](https://lookerstudio.google.com/u/0/reporting/a850fdeb-1229-4623-8a35-13895d4ec484/page/DyhoD).
    -   Corporación OSSO. [*Link*](https://osso.org.co/).
    -   Sistema de Alerta Temprana de Medellín y el Valle de Aburrá (SIATA). [*Link*](https://siata.gov.co/).
    -   Departamento Administrativo del Sistema para la Prevención, Atención y Recuperación de Desastres de la Gobernación de Antioquia (DAPARD). [*Link*](http://dapard.antioquia.gov.co/).
    -   Sistema de Información Ambiental de Colombia (SIAC). [*Link*](http://www.siac.gov.co/).
    -   Sistema Integrado de Monitoreo Ambiental de Caldas (SIMAC). [*Link*](http://cdiac.manizales.unal.edu.co/sistema-alerta-temprana-test/MapaManizales/).
    -   FEWS Colombia. Sistemas de pronósticos hidrológicos y alerta temprana. [*Link*](http://www.ideam.gov.co/web/agua/fews)
    -   DHIME: Consulta y Descarga de Datos Hidrometeorológicos, IDEAM. [*Link*](http://dhime.ideam.gov.co/atencionciudadano/).
    -   Plataforma Observatorio Bahia de Cartagena. [*Link*](https://www.basic-cartagena.org/).

-   **Manejo de desastres**

    -   Charter. [*Link*](https://disasterscharter.org/web/guest/about-the-charter). Activation list. [*Link.*](https://disasterscharter.org/web/guest/charter-activations)
        -   Colombia, Providencia. [*Link*](https://disasterscharter.org/web/guest/activations/-/article/storm-hurricane-urban-in-colombia-activation-687-).

    ## **Bases de datosde amenazas y eventos de desastre de Colombia**

    -   Datos del Consolidado de atención a emergencias. UNGRD. [*Link*](http://portal.gestiondelriesgo.gov.co/Paginas/Consolidado-Atencion-de-Emergencias.aspx).
    -   DESINVENTAR. Base de datos de pérdidas históricas en Colombia (período 1970-2011). [*Link*](http://online.desinventar.org/).
    -   COLOMBIA – Censo Nacional de Población y Vivienda – CNPV – 2018.[*Link*](http://microdatos.dane.gov.co/index.php/catalog/643/get_microdata).

    ## Bases de datos **de amenazas y eventos de desastre** **regionales y mundiales**

    -   Plataforma para las Am é ricas. [*Link*](https://eird.org/pr18/eng/).
    -   Atlas de Riesgos Climáticos para Chile. [*Link*](https://arclim.mma.gob.cl/).
    -   Mapa digital de amenazas y desastres de Chile. [*Link*](https://chileterritorioenmovimiento.cl/mapa-interactivo/).
    -   Prevention web. .
    -   NatCatSERVICE Database. [*Link*](https://www.munichre.com/en/solutions/for-industry-clients/natcatservice.html).
    -   EM-DAT. Centre for Research on the Epidemiology of Disasters (CRED). [*Link*](https://www.emdat.be/). [Git](https://github.com/GFDRR/pyEmdat)
    -   SIGMA (Swiss Re). [*Link*](https://www.sigma-explorer.com/).
    -   G Lobal unique disaster IDEntifier (GLIDE). [*Link*](https://glidenumber.net/glide/public/about.jsp).
    -   Metabuscador Climate Adapt. [*Link*](https://climate-adapt.eea.europa.eu/data-and-downloads/?source=%7B%22query%22%3A%7B%22function_score%22%3A%7B%22query%22%3A%7B%22bool%22%3A%7B%22must%22%3A%7B%22bool%22%3A%7B%22must%22%3A%5B%7B%22term%22%3A%7B%22hasWorkflowState%22%3A%22published%22%7D%7D%5D%7D%7D%2C%22filter%22%3A%7B%22bool%22%3A%7B%22should%22%3A%5B%7B%22term%22%3A%7B%22typeOfData%22%3A%22Information%20portals%22%7D%7D%5D%7D%7D%7D%7D%2C%22functions%22%3A%5B%7B%22gauss%22%3A%7B%22issued%22%3A%7B%22scale%22%3A%2214d%22%7D%7D%7D%5D%2C%22score_mode%22%3A%22sum%22%7D%7D%2C%22display_type%22%3A%22list%22%2C%22sort%22%3A%5B%7B%22issued%22%3A%7B%22order%22%3A%22desc%22%7D%7D%5D%2C%22highlight%22%3A%7B%22fields%22%3A%7B%22*%22%3A%7B%7D%7D%7D%7D).

-   **Otros**

    -   GDIS, a global dataset of geocoded disaster locations. Scientific Data. 2021. [*Link*](https://www.nature.com/articles/s41597-021-00846-6).
    -   World tectonic plates and boundaries. Github. [*Link*](https://github.com/fraxen/tectonicplates/)
    -   The Lloyd’s Register Foundation World Risk Poll. [*Link*](https://wrp.lrfoundation.org.uk/data-resources/a-world-of-risk-country-overviews/).

-   **Lecturas**:

    -   Worldwide disaster loss and damage databases: A systematic review. 2021. [*Link*](https://www.jehp.net/article.asp?issn=2277-9531;year=2021;volume=10;issue=1;spage=329;epage=329;aulast=Mazhin).

-   **Otras bases de datos nacionales**

    -   LEILA – Librería de calidad de datos. DNP. [*Link*](https://ucd-dnp.github.io/leila/index.html)

-   **Bases de datos de información técnica**

    -   OECD. [*Link*](https://www.oecd.org/).
        -   OECD One. [*Link*](https://one.oecd.org/). [*Link*](https://login.oecd.org/?appId=293718&targetAppId=18060&referer=https%3A%2F%2Fone.oecd.org%2F). [*Tutorials*](https://community.oecd.org/community/one-feedback/tutorials). [Co-creation project](https://community.oecd.org/community/cstp/tip/cocreation)
    -   United Nations Climate Change. [*Link*](https://www4.unfccc.int/sites/nwpstaging/pages/Search.aspx).

**A Decade of the Sendai Framework for Disaster Risk Reduction – Envisioning the Road Ahead» on 26 September at UNESCO Headquarters, in Paris France, 2024**

::: {layout-ncol="2"}
{{< video "https://www.youtube.com/watch?v=F1fp2aDGth8" >}}

{{< video "https://www.youtube.com/watch?v=FfHlOYKoCbY" >}}

{{< video "https://www.youtube.com/watch?v=Rf8g0sgQ93s" >}}

{{< video "https://www.youtube.com/watch?v=Fp_eWW7bDtA" >}}
:::

## **Revistas en gestión de riesgos**

-   **Internacionales**
    -   International Journal of Disaster Risk Reduction. [*Link*](https://www.journals.elsevier.com/international-journal-of-disaster-risk-reduction).
    -   International Journal of Disaster Risk Science. [*Link*](https://www.springer.com/journal/13753).
    -   Natural Hazards. [*Link*](https://link.springer.com/journal/11069).
    -   Natural Hazards Review. [*Link*](https://ascelibrary.org/journal/nhrefo).
    -   Natural Hazards and Earth System Sciences. [*Link*](https://www.natural-hazards-and-earth-system-sciences.net/).
    -   Environmental Science and Policy. [*Link*](https://www.journals.elsevier.com/environmental-science-and-policy).
    -   Environment: Science and Policy for Sustainable Development. [*Link*](https://www.tandfonline.com/loi/venv20).
    -   Progress in Disaster Science. [*Link*](https://www.sciencedirect.com/journal/progress-in-disaster-science).
    -   Safety Science. [*Link*](https://www.journals.elsevier.com/safety-science).
    -   Risk Analysis. [*Link*](https://onlinelibrary.wiley.com/journal/15396924).
    -   Risk, Hazards, & Crisis in Public Policy. [*Link*](https://onlinelibrary.wiley.com/journal/19444079).
    -   Advances in Natural and Technological Hazards Research. [*Link*](https://www.springer.com/series/6362?detailsPage=titles).
    -   Nature, Collection Natural Hazards. [*Link*](https://www.nature.com/collections/bdhajfjhbc).
-   **Natural Hazard Center.**
    -   List of Hazards and Disaster Journals. [*Link*](https://hazards.colorado.edu/resources/hazards-and-disaster-journals).
    -   Research Check Sheets Series. [*Link*](https://converge.colorado.edu/resources/check-sheets/)
-   **Latinoamericanas**
    -   Revista de Estudios Latinoamericanos sobre Reducción del Riesgo de Desastres REDER. [Link.](http://revistareder.com/ojs/index.php/reder/issue/archive)
-   **Colombianas**
    -   Cuadernos de Geografía: Revista Colombiana de Geografía. [*Link*](https://revistas.unal.edu.co/index.php/rcg).
    -   Boletín de Geología. [*Link*](https://revistas.uis.edu.co/index.php/revistaboletindegeologia/index).
    -   Earth Sciences Research Journal. [*Link*](https://revistas.unal.edu.co/index.php/esrj).
    -   CT y F – Ciencia, Tecnologia y Futuro. [*Link*](https://ctyf.journal.ecopetrol.com.co/index.php/ctyf).
    -   Geología Colombiana. [*Link*](https://revistas.unal.edu.co/index.php/geocol/issue/archive).
    -   Ingenieria e Investigacion. [*Link*](https://revistas.unal.edu.co/index.php/ingeinv/index).
    -   Revista Facultad de Ingenieria. [*Link*](https://revistas.udea.edu.co/index.php/ingenieria/issue/archive).
    -   Revistas de divulgación Seguros Sura. [*Link*](https://www.segurossura.com.co/paginas/comunicaciones/revista-geociencias-sura.aspx).
    -   Revista DYNA. [*Link*](https://www.scimagojr.com/journalsearch.php?q=12600154771&tip=sid&exact=no).
    -   Perspectiva Geográfica. [*Link*](https://revistas.uptc.edu.co/index.php/perspectiva).
    -   Legislación prospectiva. [*Link*](https://legislacionyprospectiva.co/).
-   **Ranking de Revistas en GRD**
    -   En google académico
        -   Area Emergency management. [*Link*](https://scholar.google.com/citations?view_op=top_venues&hl=es&venue=YeOoAtCjeHUJ.2019&vq=bus_emergencymanagement).
    -   En SJR
        -   Area Safety research. [*Link*](https://www.scimagojr.com/journalrank.php?category=3311) Latinoamerica. [*Link*](https://www.scimagojr.com/journalrank.php?category=3311&country=Latin%20America).
        -   Area Geography, Planning and Development. [*Link*](https://www.scimagojr.com/journalrank.php?category=3305). Latinoamerica. [*Link*](https://www.scimagojr.com/journalrank.php?category=3305&country=Latin%20America).

## Algunos investigadores Internacionales en DRR

```         
-   Irasema Alcántara Ayala. [*Link*](https://scholar.google.co.uk/citations?hl=en&user=bDAzleQAAAAJ&view_op=list_works&sortby=pubdate).
-   David E. Alexander. [*Link*](https://scholar.google.co.uk/citations?hl=en&user=F6l81zAAAAAJ).
-   Susan L. Cutter. [*Link*](https://scholar.google.com/citations?hl=es&user=BCo8hAwAAAAJ&view_op=list_works&sortby=pubdate).
-   Juergen Weichselgartner. [*Link*](https://scholar.google.com/citations?hl=es&user=fES1svQAAAAJ&view_op=list_works&sortby=pubdate).
-   Benigno Aguirre. [*Link*](https://scholar.google.com/citations?hl=es&user=i36JlYgAAAAJ&view_op=list_works&sortby=pubdate).
-   Douglas Paton (Risk communication). [*Link*](https://scholar.google.com/citations?hl=en&user=3luSZvYAAAAJ&view_op=list_works).
-   JC Gaillard. [*Link*](https://jcgaillard.wordpress.com/).
-   Gonzalo Lizarralde. [*Link*](https://scholar.google.com/citations?user=T6VcEwUAAAAJ&hl=es&oi=ao).
-   Cees Van Westen. [*Link*](https://scholar.google.com/citations?hl=es&user=Y_wCIDYAAAAJ&view_op=list_works&sortby=pubdate)
```

-   **Eventos internacionales**
    -   Annual Natural Hazards Workshop. [*Link*](https://hazards.colorado.edu/workshop).
    -   ICGNH 2020: 14. International Conference on Geography and Natural Hazards. [*Link*](https://waset.org/geography-and-natural-hazards-conference-in-april-2020-in-boston).
-   **Riesgos y salud pública**
    -   The Lancet Countdown: tracking progress on health and climate change. [*Link*](https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(19)32596-6/fulltext).
-   **Programas institucionales asociados a la ciencia de los desastres**
    -   Servicio Geológico Colombiano. Plan Estratégico del Conocimiento Geocientífico del Territorio Colombiano 2022 – 2032.[*Link*](https://www2.sgc.gov.co/Noticias/Paginas/plan-estrategico-del-conocimiento-geocientifico-2022-2032.aspx).
    -   Plan Estratégico Nacional de Investigación Ambiental – PENIA. [*Link*](https://www.minambiente.gov.co/wp-content/uploads/2021/12/PLAN-ESTRATEGICO-NACIONAL-DE-INVESTIGACION-AMBIENTAL-PENIA-2021-2030_12.pdf).
-   **Ciencia y datos abiertos para DRR**
    -   OpenDRI Open data for resilience. [*Link*](https://www.opendri.org/about/).
    -   Digital Public Goods for Disaster Risk Reduction in a Changing Climate. Banco Mundial. 2023. [*Link*](https://openknowledge.worldbank.org/entities/publication/a5534ede-04d2-4b1f-a317-1c5886e631ee).
    -   Open Data for Resilient Urban Planning. [*Link*](https://towardsdatascience.com/the-open-cities-ai-challenge-3d0b35a721cc). Github. [*Link*](https://github.com/drivendataorg/open-cities-ai-challenge).
    -   GFDRR open-risk-data-dashboard. [*Link*](https://github.com/GFDRR/open-risk-data-dashboard).
    -   **CODATA**.
        -   FAIR Data for Disaster Risk Research. [*Link*](https://codata.org/initiatives/task-groups/fair-data-for-disaster-risk-research/).
        -   Webinars. [*Link*](https://codata.org/events/webinars/).
        -   CODATA-RDA Schools of Research Data Science. [*Link*](https://codata.org/initiatives/data-skills/research-data-science-summer-schools/).
-   **InaSAFE** is free software that produces realistic natural hazard impact scenarios for better planning. [*Link*](http://inasafe.org/home/index.html).
-   UNESCO. Multistakeholder Consultations on Open Science. [*Link*](https://en.unesco.org/science-sustainable-future/open-science/consultation).
-   **Lecturas**
    -   Harnessing risk-informed data for disaster and climate resilience. 2022. [*Link*](https://www.preventionweb.net/publication/harnessing-risk-informed-data-disaster-and-climate-resilience?utm_source=LinkedIn&utm_campaign=PreventionSavesLives). [*Link*](https://www.sciencedirect.com/science/article/pii/S2590061722000412).

::: {layout-ncol="2"}
{{< video "https://www.youtube.com/watch?v=-ImINBEeiIs" >}}

{{< video "https://www.youtube.com/watch?v=kb6OpSIVP7I " >}}

<iframe title="2021-06-21 CODATA DDI Alliance webinar: Implementing FAIR - What DDI Can Do for You!" src="https://player.vimeo.com/video/565557781?dnt=1&amp;app_id=122963" width="570" height="320" frameborder="0" allow="autoplay; fullscreen; picture-in-picture; clipboard-write; encrypted-media">

</iframe>
:::

Mapeo de Asentamientos Informales basado en Inteligencia Artificial. Banco Mundial.[ *Link*](https://www.iadb.org/es/quienes-somos/topicos/desarrollo-urbano-y-vivienda/maiia).

-   **Ciencia, tecnología e innovación en GRD.**
-   Science, Technology and Academia.
    -   UNDRR. [*Link*](https://www.undrr.org/implementing-sendai-framework-partners-and-stakeholders/science-and-technology-action-group).
    -   APRU Multi-Hazards. [*Link*](https://apru.org/our-work/pacific-rim-challenges/multi-hazards/).
    -   The science and technology roadmap to support the implementation of the Sendai Framework for Disaster Risk Reduction 2015-2030. [*Link*](https://www.google.com/search?q=he+science+and+technology+roadmap+to+support+the+implementation+of+the+Sendai+Framework+for+Disaster+Risk+Reduction+2015-2030.&rlz=1C5OZZY_enCO1132CO1132&sourceid=chrome&ie=UTF-8#:~:text=The%20Science%20and,%E2%80%BA%20files%20%E2%80%BA%2065131_file).
    -   Prevention Web Science and Technology. [*Link*](https://www.preventionweb.net/themes/view/761#hits=20&sortby=default&view=pw&filter=themes%3A%5E%22Science+and+Technology%22%24).
-   **30 innovations**
    -   Disaster risk reduction and innovations. *Progress in Disaster Science*, 2019. [*Link*](https://www.sciencedirect.com/science/article/pii/S259006171930033X).
    -   30 Innovations linking disaster risk reduction with sustainable development goals. [*Link*](https://www.preventionweb.net/publications/view/70713).
    -   30 innovations for disaster risk reduction. [*Link*](https://www.preventionweb.net/publications/view/64473).
    -   Applications of artificial intelligence for disaster management. *Natural Hazards,* 2020. [*Link*](https://link.springer.com/article/10.1007/s11069-020-04124-3).
-   **Lecturas**
    -   Exploring the emerging evolution trends of disaster risk reduction research: a global scenario. *International Journal of Environmental Science and Technology,* 2021. [*Link*](https://link.springer.com/article/10.1007/s13762-020-02847-1).

    -   Knowledge and Disaster Risk Reduction. *The Routledge Handbook of Hazards and Disaster Risk Reduction*. 2011. [*Link*](https://www.routledgehandbooks.com/doi/10.4324/9780203844236.ch9)

    -   Perspectives of Science and Technology in Disaster RiskReduction of Asia. 2016. International Journal of Disaster Risk Science. [*Link*](https://doi.org/10.1007/s13753-016-0104-7).

    -   Three innovative approaches for managing disaster risks. [*Link*](https://blogs.worldbank.org/sustainablecities/three-innovative-approaches-managing-disaster-risks).

    -   2021 APRU Multi-Hazards Webinar Series: Health, Climate Change and Innovation in Disaster Risk Reduction. [*Link*](https://apru.org/event/2021-apru-multi-hazards-webinar-series-health-climate-change-and-innovation-in-disaster-risk-reduction/), [*link*](https://apru.org/wp-content/uploads/2021/10/MH-webinar_oct-2021.pdf).

    -   ADB and OECD. 2020. Leveraging Technology and Innovation for Disaster Risk Management and Financing. [*Link*](https://www.adb.org/sites/default/files/publication/664501/tech-innovation-disaster-risk-mgt-financing.pdf)

    -   Success, innovation and challenge: School safety and disaster education in South America and the Caribbean, 2020. [*Link*](https://www.sciencedirect.com/science/article/abs/pii/S2212420919305813).

**IRDR Compilation 2010-2020: A Ten Year Science Quest for Disaster Risk Reduction**. [*Link*](https://www.irdrinternational.org/knowledge_pool/publications/868)

**The Integrated Research on Disaster Risk 2021 International Conference.**[*Link.*](https://conference.irdrinternational.org/)

**A framework for global science in support of risk-informed sustainable development and planetary health**. 2021. [*Link*](https://www.undrr.org/publication/framework-global-science-support-risk-informed-sustainable-development-and-planetary).

::: {layout-ncol="2"}
{{< video "https://www.youtube.com/watch?v=Kv6LUyDTivQ" >}}

{{< video "https://www.youtube.com/watch?v=SRNPohtu6zo" >}}

{{< video "https://www.youtube.com/watch?v=txi60sxkgjg" >}}

{{< video "https://www.youtube.com/watch?v=uZswTWn9nyU" >}}

{{< video "https://www.youtube.com/watch?v=65yMaoofboQ" >}}
:::