---
title: "Cursos, entrenamiento y redes"
format: html
editor: visual
---

# **Centros, entrenamiento y redes**

-   **The Australian Disaster Resilience Knowledge Hub**
    -   Emergency planning collection. [*Link*](https://knowledge.aidr.org.au/collections/emergency-planning/).
    -   Disasters. [*Link*](https://knowledge.aidr.org.au/disasters/).
    -   Glossary. [*Link*](https://knowledge.aidr.org.au/glossary/).
    -   Emergency Management Library. [*Link*](https://knowledge.aidr.org.au/collections/emergency-management-library/).
    -   Recovery Matters webinar series. [*Link*](https://knowledge.aidr.org.au/resources/recovery-matters-webinar-series/?utm_source=Updates+from+AIDR&utm_campaign=f666ebcb63-EMAIL_CAMPAIGN_2020_03_10_03_44_COPY_01&utm_medium=email&utm_term=0_a0a8e928c9-f666ebcb63-184368417#story).
    -   The Australian Institute for Disaster Resilience. [*Link*](https://www.aidr.org.au/)
-   CONVERGE Training Modules. [*Link*.](https://converge.colorado.edu/resources/training-modules)
-   Disaster Reduction Learning Center (DRLC). [*Link*](https://www.jica.go.jp/english/activities/issues/disaster/disaster.html).
-   Regional DDR e-learning platform. [*Link*](https://courses.adpc.net/).
-   The National Disaster & Emergency Management University. FEMA. [*Link*](https://training.fema.gov/).
    -   Independent Study Program. [*Link*](https://training.fema.gov/is/)*.*
    -   Curriculum. [*Link*](https://training.fema.gov/ndemu/curriculum/)*.*
-   Pacific Disaster Center. Online Courses. [*Link*](https://www.pdc.org/help/)*.*
-   Disaster Risk Management Training Center. [*Link*](https://drmkc.jrc.ec.europa.eu/).
    -   Training Corner. [*Link*](https://drmkc.jrc.ec.europa.eu/science-for-drm/training-corner).

    -   Disaster Risk Management Training online series 2022. European Commision. [*Link*](https://drmkc.jrc.ec.europa.eu/science-for-drm/training-corner/disaster-risk-management-training-online-series-2022).

# Cursos en inglés

-   Building resilience to compound and cascading disaster risks.[*Link*](https://ap-plat.nies.go.jp/adaptation_literacy/resources/e_learning/drr/index.html). [*Link*](https://www.youtube.com/watch?v=TGH4FMUIEHg&list=PL9jaKxAv72Izbx17XKZhbFLvczH-5t7AV)
-   Bushfires: Response, Relief and Resilience. [*Link*](https://www.futurelearn.com/courses/bushfires).
-   Disasters and Ecosystems: Resilience in a Changing Climate. [*Link*](https://www.youtube.com/playlist?list=PLH___LL2LODuduh-dhLSFKOhyJZtRnIc_).
-   Disaster Preparedness. [*Link*](https://www.coursera.org/learn/disaster-preparedness).
-   Disaster Risk Management and Korean Policies. [*Link*](https://www.coursera.org/learn/disaster-risk-management-korean-policies).
-   Flood Risk Management. [*Link*](https://www.edx.org/es/course/flood-risk-management).
-   Natural Disasters. [*Link*](https://www.edx.org/es/course/natural-disasters). [*Link*](http://www.meteo.mcgill.ca/atoc185/).
-   Open learning campus. World Bank. [*Link*](https://olc.worldbank.org/content/resilience-and-disaster-risk-management-learning-lab)
-   A Resilient Future: Science and Technology for Disaster Risk Reduction. [*Link*](https://www.edx.org/es/course/a-resilient-future-science-and-technology-for-disa).
-   Resilience – The art of coping with disasters. [*Link*](https://www.edx.org/es/course/resilience-the-art-of-coping-with-disasters).
-   Social Vulnerability and Disasters. Converge. [*Link*](https://converge-training.colorado.edu/courses/vulnerable-populations/).
-   Tsunamis and Storm Surges: Introduction to Coastal Disasters. [*Link*](https://www.edx.org/es/course/tsunamis-and-storm-surges-introduction-to-coastal).
-   UNESCO. Online courses to promote disaster risk reduction awareness. [*Link*](https://en.unesco.org/greencitizens/stories/online-courses-promote-disaster-risk-reduction-awareness). [*Link*](http://elearning.unep.org/moocs/courses).
-   When Disaster Meets Conflict. [*Link*](https://www.coursera.org/learn/whendisastermeetsconflict).

## El riesgo en la sociedad moderna

::: {layout-ncol="2"}
{{< video "https://youtu.be/96_I4wEoTjM" >}} 1.1 The History of Risk

{{< video "https://youtu.be/ERa7trqyQlY" >}} 1.2 The Study of Risk: Security Studies

{{< video "https://youtu.be/7yzp3x85jdc" >}} 1.3 The Study of Risk: Safety Science

{{< video "https://youtu.be/FehtVq--_S0" >}} 2.1 Risk Management

{{< video "https://youtu.be/8EsX84P7hsU" >}} 2.6 Risk Management: Strengths and Weaknesses

{{< video "https://youtu.be/dNgrKQo0gMg" >}} 3.1 Risk Perception

[Coursera.](https://www.coursera.org/learn/risk-in-modern-society/home/module/1)
:::

## **Building resilience to compound and cascading disaster risks**

::: {layout-ncol="2"}
{{< video "https://youtu.be/TGH4FMUIEHg" >}} Building resilience to compound and cascading disaster risks

{{< video "https://youtu.be/vSq7mV96U4s" >}} Lesson 1：Compound and cascading disaster risks. What are they?

{{< video "https://youtu.be/xtkGBrkzpFI" >}} Lesson 2：Six steps of disaster risk assessment

{{< video "https://youtu.be/R9UrAFUeFIY" >}} Lesson 3：Designing resilience enhancing measures

{{< video "https://youtu.be/B5MqJiRS4Lc" >}} Lesson 4：Adaptive implementation framework

{{< video "https://youtu.be/2mBnTcttTao" >}} Conclusion：Summary of the course
:::

# Cursos en español

-   Análisis del Riesgo de Desastres y Cambio Climático en Proyectos de Infraestructura. BID. [*Link*](https://cursos.iadb.org/es/temas/infraestructura/analisis-riesgo-desastres-cambio-climatico-proyectos-infraestructura).
-   Comunicando el cambio climático de manera efectiva. CDKN. [*Link*](https://cdkn.org/comunicando/?loclang=es_es&fbclid=IwAR0sQ3LypFp0Atq5eOtWgPrOisQkKmMeBlaS-woYhp5JvqKFE122-_LIur8).
-   Evaluación de peligros y riesgos por fenómenos naturales. [*Link*](https://www.coursera.org/learn/riesgos-fenomenos-naturales/home/welcome).
-   Gobierno de Santiago e Itrend lanzan plataforma docente para enseñar sobre desastres en la región Metropolitana. [*Link*](https://plataforma.aprendedesastres.cl/).
-   Gestión integral del riesgo de desastres. [*Link*](https://www.coursera.org/learn/gestion-riesgo/home/welcome).
-   Género-Diversidad en la reducción del riesgo de desastres y cambio climático. [*Link*](https://es.grripp.net/cursoonline/1-video-introductorio).

# Cursos de GRD con enfoque indigena

-   Integrating Gender and Indigenous Factors into Locally-Led Adaptation. [*Link*](https://ap-plat.nies.go.jp/adaptation_literacy/resources/e_learning/ait_lla/index.html)*.*
-   Mitigation Planning for Tribal Communities. FEMA. [*Link*](https://training.fema.gov/is/courseoverview.aspx?code=IS-350&lang=en)*.*

{{< video "https://youtu.be/V06jgGkSmmM >}} Asia-Pacific Indigenous Studies Seminar Series (April 29) - Indigenous Design and Property Regimes

# Otros temas

-   Fundamentals of Remote Sensing. [*Link*](https://arset.gsfc.nasa.gov/webinars/fundamentals-remote-sensing).
-   USGS- Spatial Data. [*Link*](https://lpdaac.usgs.gov/resources/e-learning/).
-   NASA – Earth Science, Applied Science online trainings [*Link*](https://appliedsciences.nasa.gov/join-mission/training?program_area=14).
-   Teaching climate. Climate Gov. [*Link*](https://www.climate.gov/teaching).
-   Coastal Aquaculture Planning Portal (CAPP). [*Link*](https://coastalscience.noaa.gov/research/marine-spatial-ecology/coastal-aquaculture-planning-portal-capp/).
-   UICN. Water. [*Link*](https://learningelc.org/course/index.php?categoryid=6).

# **Seminarios y series**

-   Riesgo por cambio climático en Colombia. Estrategia Climática de Largo Plazo Colombia E2050. [*Link*](https://youtu.be/4v9T0QaI7ZU).
-   Converge Webinar series. [*Link*](https://converge.colorado.edu/communications/webinar-series).
-   APRU Multi-Hazards. [*Link*](https://www.apru.org/our-work/pacific-rim-challenges/multi-hazards/)*,* Webinar Series. [*Link*](https://apru.org/event/the-apru-multi-hazards-webinar-series-a-new-approach-for-disaster-risk-management-after-covid-19/).
-   Knowledge Action Network on Emergent Risks and Extreme Events. [*Link*](https://www.risk-kan.org/webinars/)

::: {layout-ncol="2"}
{{< video"https://youtu.be/RX2H7kacamM" >}} APRU-IRIDeS Multi-Hazards Virtual Summer School 2020 (Part I)

{{< video"https://youtu.be/9725LyLYuc4" >}} APRU-IRIDeS Multi-Hazards Virtual Summer School 2020 (Part II)

APRU Multi-Hazards Webinar Series.
:::

# **Otros recursos**

-   The Climate Reanalyzer. Climate.gov. [*Link*](https://www.climate.gov/teaching/resources/climate-reanalyzer-0). [*Link*](https://climatereanalyzer.org/).