---
title: "Educación en Gestión del Riesgo de Desastres"
format: html
editor: visual
---

# Leyes, decretos, programas, estrategias

-   Ley [2272](https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=197883#2272 "vinculo") de 2022 Servicio Social para la Paz
-   Decreto 1079 de 2024. para reglamentar el Servicio Social para la Paz creado mediante la Ley [2272](https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=197883#2272 "vinculo") de 2022. [*Link*](https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=249476)
-   Ley 2427 de 2024. Por medio de la cual se establece la capacitación, la profundización y la enseñanza para la sostenibilldad ambiental, cambio climático y gestión del riesgo de desastres. [*Link*](https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=250916)

# Recursos

-   Disaster risk reduction for children. UNDRR. [*Link*](https://www.undrr.org/implementing-sendai-framework/sendai-framework-action/disaster-risk-reduction-for-children) *\*\*\**
    -   Child-friendly glossary. UNDRR. [*Link*](https://www.preventionweb.net/publication/child-friendly-glossary)
-   Ready kids. FEMA. [*Link*](https://www.ready.gov/es/kids). \*\*\*
-   Education for Young People. AIDR Australia. [*Link*](https://schools.aidr.org.au/). \*\*\*
    -   Education resources. [*Link*](https://schools.aidr.org.au/disaster-resilience-education/teaching-resources/#/)
-   Climate change starter's guidebook: an issues guide for education planners and practitioners. UNESCO. [*Link*](https://unesdoc.unesco.org/ark:/48223/pf0000211136).
-   Green Vocabulary: Teaching Kids About Climate Change. [*Link*](https://www.performingenglish.net/green-vocabulary-teaching-kids-about-climate-change/).
-   Vocabulary for a Changing Climate. [*Link*](https://kidsagainstclimatechange.co/vocabulary-for-a-changing-climate/).
-   Climate glossary for young people. UNICEF. [*Link*](https://www.unicef.org/lac/media/19321/file/climate-glossary-for-young-people.pdf)
-   A Student's Guide to Global Climate Change. EPA. [*Link*](https://archive.epa.gov/climatechange/kids/glossary.html).

# Programas internacionales

-   Climate change education. UNESCO. [*Link*](https://www.unesco.org/en/climate-change/education).

# Educación para la niñez

-   COPE. The Disaster Book Series. [*Link*](https://cope-disaster-champions.com/)
-   Save the Children. Child-led Disaster Risk Reduction-A practical guide-Part 1: [*Link*](https://resourcecentre.savethechildren.net/document/child-led-disaster-risk-reduction-practical-guide-part-1https://resourcecentre.savethechildren.net/document/child-led-disaster-risk-reduction-practical-guide-part-1)

::: {layout-ncol="2"}
{{< video "https://youtu.be/kKA23uASxeg?si=LH3YLU-jGk_KaYMK" >}} COPE Disasters Champions

{{< video "https://youtu.be/XfTKBeWELjY" >}} Disaster Resilience Education for Young People Handbook \| [*Link*](https://knowledge.aidr.org.au/resources/handbook-disaster-resilience-education-for-young-people/)
:::

::: {layout-ncol="2"}
:::

# Lecturas

-   IFRC (Federación Internacional de Sociedades de la Cruz Roja y Media Luna Roja). 2011. Guía: Para la sensibilización y educación pública sobre la reducción de riesgos de desastres. Ginebra, Suiza. [*Link*](https://www.preventionweb.net/files/61592_302200publicawarenessddrguidees.pdf).
-   Plan nacional de capacitación y formación en gestión del riesgo de desastres 2022-2030. [*Link*](https://repositorio.gestiondelriesgo.gov.co/handle/20.500.11762/38718?fbclid=IwAR18I1UGQjs6QY50qGJiSpHwZSovFTo_q9wL8p4Q0k7jh9bBsOUFgX5aqrk).
-   Postgraduate modules, University College London. [*Link*](https://www.ucl.ac.uk/risk-disaster-reduction/study/postgraduate-modules).
-   Education for Sustainable Development and Disaster Risk Reduction. 2014. [*Link*](https://books.google.com.co/books?id=SCM9BAAAQBAJ).
-   How Best to Educate People About Climate Change?. 2024. [*Link*](https://news.climate.columbia.edu/2024/01/22/how-best-to-educate-people-about-climate-change/#:~:text=Climate%20change%20is%20multidimensional%20and,%2C%20biology%2C%20geochemistry%20and%20economics.).
-   Climate Change Education An Earth Institute Sustainability Primer. Cassie Xu and Radhika Iyengar Columbia University Press. 2023. [*Link*](https://books.google.com.co/books?id=0brFEAAAQBAJ&printsec=frontcover&dq=Climate+Change+Education+An+Earth+Institute+Sustainability+Primer&hl=es-419&newbks=1&newbks_redir=0&sa=X&redir_esc=y#v=onepage&q=Climate%20Change%20Education%20An%20Earth%20Institute%20Sustainability%20Primer&f=false)

# Museos de ciencia

::: {layout-ncol="2"}
{{< video "https://www.youtube.com/watch?v=m-p8kUrUWd4" >}} Comunicación del riesgo volcánico

{{< video "https://www.youtube.com/watch?v=Mn7EgWsnzUo" >}} Global platform for disaster risk reduction, Indonesia 2022

Comunicación del riesgo
:::

::: callout-tip
## Qué aprenden o recuerdan los visitantes en un museo de ciencia

-   Mensajes que apoyan sus necesidades e intereses.

-   Mensajes que son novedosos, extraños o interesantes.

-   Mensajes que contienen un alto contenido emocional para el individuo.

-   Mensajes respaldados por experiencias posteriores (medición ex post facto ).
:::

## Lista de expertos y lecturas

-   John Falk. Link
    -   Falk, J. H., & Dierking, L. D. (2013). The Museum Experience Revisited. [*Link*](https://books.google.com.co/books?id=Pzo3-SI3DPAC&printsec=frontcover&source=gbs_ge_summary_r&cad=0#v=onepage&q&f=false).

<!-- -->

-   **Expertos**:

    -   John Falk. [*Link*](https://scholar.google.com/citations?user=1hytoUMAAAAJ&hl=en&oi=sra)
    -   Falk, J. H., & Dierking, L. D. (2013). The Museum Experience Revisited. [*Link*](https://doi.org/10.4324/9781315417851).

-   **Lecturas**

    -   Barriault, C., & Pearson, D. (2010). Assessing exhibits for learning in science centers: A practical tool. Visitor Studies, 13(1), 90–106. [*Link*](https://doi.org/10.1080/10645571003618824).

    -   Ma, J., Shahar, E., Eliceiri, K., Mehta, G., & Yu, K. (2019). Shedding light: Integrating bioimaging technologies into the design of an interactive museum exhibit. DIS 2019 – Proceedings of the 2019 ACM Designing Interactive Systems Conference. [*Link*](https://doi.org/10.1145/3322276.3322299).

    -   King, D., Ma, J., Armendariz, A., & Yu, K. (2018). Developing Interactive Exhibits with Scientists: Three Example Collaborations from the Life Sciences Collection at the Exploratorium. Integrative and Comparative Biology, 58(1), 94–102. [*Link*](https://doi.org/10.1093/icb/icy010).

    -   Kratz, S. & Merritt E. (2011). Museums and the future of education. On the Horizon, 19 (3), 188-195

    -   MacDonald, E., Johnson, V., Gillies, M., & Johnston, D. (2017). The impact of a museum-based hazard education program on students, teachers and parents. *International Journal of Disaster Risk Reduction*, *21*, 360–366. [*Link*.](https://doi.org/10.1016/j.ijdrr.2017.01.010)

    -   Martin, A. J., Durksen, T. L., Williamson, D., Kiss, J., & Ginns, P. (2016). The role of a museum-based science education program in promoting content knowledge and science motivation. *Journal of Research in Science Teaching*, *53* (9), 1364–1384. [*Link*](https://doi.org/10.1002/tea.21332).

    -   Motschnig, R. & Cornelius-White J. (2012). Experiential/Significant Learning. Encyclopedia of the Sciences of Learning. Springer US. pp: 1219-1223. [*Link*](https://doi.org/10.1007/978-1-4419-1428-6_574)

    -   Museums and the future of education. 2011. [*Link*](https://www.emerald.com/insight/content/doi/10.1108/10748121111163896/full/html)