---
title: "El Niño/La Niña Oscilación del Sur"
format: html
editor: visual
---

{{< video "https://youtu.be/gaFjlZxM7S4" >}} Extraordinary animation reveals ocean’s role in El Niños

# Mecanismos y procesos

-   NOAA El Nino Southern Oscillation. [*Link*](http://www.cpc.ncep.noaa.gov/products/precip/CWlink/MJO/enso.shtml).

-   El Niño & La Niña (El Niño-Southern Oscillation) - Climate.gov. [*Link*](https://www.climate.gov/enso).

-   ENSO \@ the Australian Bureau of Meteorology. [*Link*](http://www.bom.gov.au/climate/enso/outlook/).

-   Multivariate ENSO Index Version 2 (MEI.v2). [*Link*](https://psl.noaa.gov/enso/mei/).

-   El Niño and La Niña Years and Intensities. [*Link*](http://ggweather.com/enso/oni.htm).

-   Kelvin wave [*Link*](https://www.youtube.com/watch?v=s4bvEnIMqAE).

-   Rossby wave. [*Link*](https://oceanservice.noaa.gov/facts/rossby-wave.html).

{{< video "https://youtu.be/WPA-KpldDVc" >}} El Nino - What is it?

# Pronóstico

-   The El Niño/Southern Oscillation 2015-17: Analysis and Predictions. Steve Paton Physical Monitoring Program. STRI. [*Link*](http://www.ustream.tv/recorded/90225621).
-   El Niño and La Niña Years and Intensities. [*Link*](http://ggweather.com/enso/oni.htm).
-   Forecasting El Niño-Southern Oscillation (ENSO). [*Link*](https://blogs.rstudio.com/ai/posts/2021-02-02-enso-prediction/).

# Impactos

-   Investigating Coral Bleaching Using Data in the Classroom. [*Link*](https://portal.nnvl.noaa.gov/arcgis/apps/MapSeries/index.html?appid=138acf1bee62443fae7e8ab10e2e0266)
-   Bleaching observations (1963-2010). WRI. [*Link*](http://datasets.wri.org/dataset/bleaching-observations-1963-2010).
-   Coral Reefs Special issue: The 2014-2017 Global Coral Bleaching Event: Drivers, Impacts, and Lessons Learned Volume 38, Issue 4, August 2019. [*Link*](https://link.springer.com/journal/338/38/4/page/1).

# Otros

-   Pacific Decadal Oscillation (PDO). [*Link*](https://www.ncdc.noaa.gov/teleconnections/pdo/).
-   Climate Indices. [*Link*](http://www.cgd.ucar.edu/cas/catalog/climind/).

# Lecturas

-   Do you know that El Niño has a little brother?. [*Link*](https://climate.gov/news-features/blogs/enso/do-you-know-el-ni%C3%B1o-has-little-brother).
-   ¿La frecuencia de ENOS se incrementará con el cambio climático global?
    -   El Niño events will intensify under global warming. Nature 2018. [*Link*](https://www.nature.com/articles/d41586-018-07638-w).
    -   Increased variability of eastern Pacific El Niño under greenhouse warming. Nature 2018. [*Link*](https://www.nature.com/articles/s41586-018-0776-9).