---
title: "Glosario de Términos"
format: html
---

::: glossary-index
[**A**](#a) [**B**](#b) [**C**](#c) [**D**](#d) [**E**](#e) [**F**](#f) [**G**](#g) [**H**](#h) [**I**](#i) [**J**](#j) [**K**](#k) [**L**](#l) [**M**](#m) [**N**](#n) [**O**](#o) [**P**](#p) [**Q**](#q) [**R**](#r) [**S**](#s) [**T**](#t) [**U**](#u) [**V**](#v) [**W**](#w) [**X**](#x) [**Y**](#y) [**Z**](#z)
:::

## A {#a}

**Afectado**  
Personas afectadas de forma directa o indirectamente por un evento amenazante. Los afectados directamente son quienes presentan lesiones, enfermedades u otros efectos en la salud, quienes fueron evacuados o desplazados, reubicados o quienes han sufrido daños directos en sus medios de sustento y bienes económicos, físicos, sociales, culturales y ambientales. Los afectados indirectamente, son personas quienes han sufrido consecuencias (distintas a los efectos directos) a través del tiempo, debido a la interrupción o cambios con consecuencias psicológicas, sociales y de salud, en la economía, infraestructura indispensable, servicios básicos, comercio y trabajo (UNGA. 2016). (Tomado de UNGRD, 2017)

**Alerta**  
Estado que se declara con anterioridad a la manifestación de un evento peligroso, con base en el monitoreo del comportamiento del respectivo fenómeno, con el fin de que las entidades y la población involucrada activen procedimientos de acción previamente establecidos (Ley 1523 de 2012). (Tomado de UNGRD, 2017)

---

## B {#b}

**Base de datos de pérdidas por desastres y emergencias**  
Conjunto de registros sistemáticamente recolectados sobre la ocurrencia de emergencias y desastres, pérdidas e impactos (UNGA, 2016). (Tomado de UNGRD, 2017)

---

## C {#c}

**Calamidad pública**  
Es el resultado que se desencadena de la manifestación de uno o varios eventos naturales o antropogénicos no intencionales que al encontrar condiciones propicias de vulnerabilidad en las personas, los bienes, la infraestructura, los medios de subsistencia, la prestación de servicios o los recursos ambientales, causa daños o pérdidas humanas, materiales, económicas o ambientales, generando una alteración intensa, grave y extendida en las condiciones normales de funcionamiento de la población, en el respectivo territorio, que exige al municipio, distrito o departamento ejecutar acciones de respuesta a la emergencia, rehabilitación y reconstrucción (Ley 1523 de 2012). (Tomado de UNGRD, 2017)

**Comunidad**  
Grupo de personas que se localiza en un espacio determinado y establecen vínculos espontáneos de solidaridad construidos en el tiempo. Esta interacción hace posible que se generen elementos de identidad que favorecen la cohesión y el auto reconocimiento del grupo. Los intereses de la comunidad se sobreponen a los intereses particulares para el logro de objetivos comunes. Por su parte, una comunidad vulnerable es aquella que, ante un evento extremo, puede recibir mayor afectación, debido a factores como la localización y a la incapacidad para implementar acciones de prevención y adaptación orientadas la recuperación de sus medios de subsistencia en el corto plazo (Méndez, sf). (Tomado de UNGRD, 2017)

**Construcción social del riesgo**  
Se refiere a los procesos a través de los cuales la sociedad y los distintos agentes sociales contribuyen a la creación de contextos y entornos de riesgo. Esto ocurre o por la transformación de eventos naturales en amenazas debido a la inadecuada ubicación de edificaciones e infraestructuras, producción y satisfactores de la vida, etc.; por la transformación de recursos naturales en amenazas a través de procesos de degradación ambiental; o por la creación y consolidación de condiciones diversas de vulnerabilidad, las cuales potencian la acción negativa de las amenazas y eventos peligrosos. Algunos autores también ven en el proceso de percepción y subjetivización del riesgo, un proceso de “construcción social” del riesgo (Lavell, 2007). (Tomado de UNGRD, 2017)

**Desastre**  
Es el resultado que se desencadena de la manifestación de uno o varios eventos naturales o antropogénicos no intencionales que al encontrar condiciones propicias de vulnerabilidad en las personas, los bienes, la infraestructura, los medios de subsistencia, la prestación de servicios o los recursos ambientales, causa daños o pérdidas humanas, materiales, económicas o ambientales, generando una alteración intensa, grave y extendida en las condiciones normales de funcionamiento de la sociedad, que exige del Estado y del sistema nacional ejecutar acciones de respuesta a la emergencia, rehabilitación y reconstrucción (Ley 1523 de 2012). (Tomado de UNGRD, 2017)

---

## E {#e}

**Emergencia**  
Situación caracterizada por la alteración o interrupción intensa y grave de las condiciones normales de funcionamiento u operación de una comunidad, causada por un evento adverso o por la inminencia del mismo, que obliga a una reacción inmediata y que requiere la respuesta de las instituciones del Estado, los medios de comunicación y de la comunidad en general (Ley 1523 de 2012). (Tomado de UNGRD, 2017)

**Estrategia de respuesta a emergencias (ETRE)**  
Es el marco de actuación de las entidades del Sistema Nacional para la Gestión del Riesgo de Desastres para la reacción y atención de emergencias. Se refiere a todos los aspectos que deben activarse por las entidades en forma individual y colectiva con el propósito de ejecutar la respuesta a emergencias de manera oportuna y efectiva. (Tomado de UNGRD, 2017)

**Evacuación**  
Traslado temporal de personas y bienes a sitios seguros, antes, durante o después de la ocurrencia de un fenómeno amenazante para protegerlos (a partir de UNGA, 2016). (Tomado de UNGRD, 2017)

---

## F {#f}

**Frecuencia**  
Número de eventos por una unidad de tiempo definida (ISO/IEC, 2009). (Tomado de UNGRD, 2017)

---

## G {#g}

**Gestión ambiental**  
Se refiere a las acciones que, en forma consciente y dirigida a propósitos definidos, realice la sociedad para administrar los recursos naturales, renovables o no. Esto implica conservar, recuperar, mejorar, proteger o utilizar moderadamente los recursos naturales; orientar los procesos culturales al logro de sostenibilidad; ocupar y transformar el territorio de manera racional y sostenible; y revertir los efectos del deterioro y la contaminación sobre la calidad de vida, el estado de los ecosistemas, y la actividad económica (MADS, 2012). (Tomado de UNGRD, 2017)

**Gestión del riesgo**  
Es el proceso social de planeación, ejecución, seguimiento y evaluación de políticas y acciones permanentes para el conocimiento del riesgo y promoción de una mayor conciencia del mismo, impedir o evitar que se genere, reducirlo o controlarlo cuando ya existe y para prepararse y manejar las situaciones de desastre, así como para la posterior recuperación, entiéndase: rehabilitación y reconstrucción. Estas acciones tienen el propósito explícito de contribuir a la seguridad, el bienestar y calidad de vida de las personas y al desarrollo sostenible (Ley 1523 de 2012). (Tomado de UNGRD, 2017)

**Gobernanza del riesgo de desastres**  
Sistema de instituciones, mecanismos, políticas y marcos legales y otros mecanismos diseñados para guiar, coordinar y supervisar la gestión del riesgo de desastres y áreas relacionadas con políticas públicas y privadas (a partir de UNGA, 2016). (Tomado de UNGRD, 2017)

---

## I {#i}

**Infraestructura indispensable**  
Las estructuras físicas, instalaciones, redes y otros bienes que proveen servicios que son esenciales para el funcionamiento socioeconómico de una comunidad (a partir de UNGA, 2016). (Tomado de UNGRD, 2017)

---

## L {#l}

**Logística en emergencia**  
En situaciones de emergencia es la movilización de personal, equipos, accesorios, herramientas, suministros y ayuda humanitaria de emergencia para el trabajo del personal operativo y/o la atención de la población afectada (UNGRD, 2016-1). (Tomado de UNGRD, 2017)

---

## M {#m}

**Manejo de desastres**  
Es el proceso de la gestión del riesgo compuesto por la preparación para la respuesta a emergencias, la preparación para la recuperación posdesastre, la ejecución de dicha respuesta y la ejecución de la respectiva recuperación, entiéndase: rehabilitación y recuperación (Ley 1523 de 2012). (Tomado de UNGRD, 2017)

---

## P {#p}

**Pérdidas económicas**  
Impacto económico total que se compone de pérdidas económicas directas e indirectas. La pérdida económica directa hace referencia al valor monetario de la destrucción total o parcial de bienes físicos existentes en el área afectada. La pérdida económica directa es casi equivalente a los daños físicos. Por su parte, la pérdida económica indirecta se refiere a una disminución en la valorización económica como consecuencia de una pérdida económica directa y/o impactos humanos y ambientales (UNGA, 2016). (Tomado de UNGRD, 2017)

**Plan de evacuación**  
Corresponde a las acciones de preparación para que la respuesta que permite que las personas que se encuentran en una edificación (vivienda, oficina, institución educativa, establecimiento comercial, entre otras.) puedan realizar una salida ordenada, rápida y segura, con el fin de proteger la vida (UNGRD, 2016-2). (Tomado de UNGRD, 2017)

**Plan de gestión del riesgo de desastres**  
Es el instrumento que define los objetivos, programas, acciones, responsables y presupuestos, mediante las cuales se ejecutan los procesos de conocimiento del riesgo, reducción del riesgo y de manejo de desastres, en el marco de la planificación del desarrollo. (Tomado de UNGRD, 2017)

**Preparación**  
Es el conjunto de acciones principalmente de coordinación, sistemas de alerta, capacitación, equipamiento, centros de reserva y albergues y entrenamiento, con el propósito de optimizar la ejecución de los diferentes servicios básicos de respuesta, como accesibilidad y transporte, telecomunicaciones, evaluación de daños y análisis de necesidades, salud y saneamiento básico, búsqueda y rescate, extinción de incendios y manejo de materiales peligrosos, albergues y alimentación, servicios públicos, seguridad y convivencia, aspectos financieros y legales, información pública y el manejo general de la respuesta, entre otros (Ley 1523 de 2012). (Tomado de UNGRD, 2017)

**Prevención de riesgo**  
Medidas y acciones de intervención restrictiva o prospectiva dispuestas con anticipación con el fin de evitar que se genere riesgo. Puede enfocarse a evitar o neutralizar la amenaza o la exposición y la vulnerabilidad ante la misma en forma definitiva para impedir que se genere nuevo riesgo. Los instrumentos esenciales de la prevención son aquellos previstos en la planificación, la inversión pública y el ordenamiento ambiental territorial, que tienen como objetivo reglamentar el uso y la ocupación del suelo de forma segura y sostenible. (Ley 1523 de 2012). (Tomado de UNGRD, 2017)

**Principio de autoconservación**  
Toda persona natural o jurídica, bien sea de derecho público o privado, tiene el deber de adoptar las medidas necesarias para una adecuada gestión del riesgo en su ámbito personal y funcional, con miras a salvaguardarse, que es condición necesaria para el ejercicio de la solidaridad social. (Tomado de UNGRD, 2017)

**Principio de concurrencia**  
La concurrencia de competencias entre entidades nacionales y territoriales de los ámbitos público, privado y comunitario que constituyen el sistema nacional de gestión del riesgo de desastres, tiene lugar cuando la eficacia en los procesos, acciones y tareas se logre mediante la unión de esfuerzos y la colaboración no jerárquica entre las autoridades y entidades involucradas. La acción concurrente puede darse en beneficio de todas o de algunas de las entidades. El ejercicio concurrente de competencias exige el respeto de las atribuciones propias de las autoridades involucradas, el acuerdo expreso sobre las metas comunes y sobre los procesos y procedimientos para alcanzarlas. (Tomado de UNGRD, 2017)

**Principio de coordinación**  
La coordinación de competencias es la actuación integrada de servicios tanto estatales como privados y comunitarios especializados y diferenciados, cuyas funciones tienen objetivos comunes para garantizar la armonía en el ejercicio de las funciones y el logro de los fines o cometidos del Sistema Nacional de Gestión del Riesgo de Desastres. (Tomado de UNGRD, 2017)

**Principio de diversidad cultural**  
En reconocimiento de los derechos económicos, sociales y culturales de las personas, los procesos de la gestión del riesgo deben ser respetuosos de las particularidades culturales de cada comunidad y aprovechar al máximo los recursos culturales de la misma. (Tomado de UNGRD, 2017)

**Principio de igualdad**  
Todas las personas naturales tendrán la misma ayuda y el mismo trato al momento de atendérseles con ayuda humanitaria, en las situaciones de desastre y peligro que desarrolla esta ley. (Tomado de UNGRD, 2017)

**Principio de oportuna información**  
Para todos los efectos de esta ley, es obligación de las autoridades del Sistema Nacional de Gestión del Riesgo de Desastres, mantener debidamente informadas a todas las personas naturales y jurídicas sobre: posibilidades de riesgo, gestión de desastres, acciones de rehabilitación y construcción así como también sobre las donaciones recibidas, las donaciones administradas y las donaciones. (Tomado de UNGRD, 2017)

**Principio participativo**  
Es deber de las autoridades y entidades del Sistema Nacional de Gestión del Riesgo de Desastres, reconocer, facilitar y promover la organización y participación de comunidades étnicas, asociaciones cívicas, comunitarias, vecinales, benéficas, de voluntariado y de utilidad común. Es deber de todas las personas hacer parte del proceso de gestión del riesgo en su comunidad. (Tomado de UNGRD, 2017)

**Principio de precaución**  
Cuando exista la posibilidad de daños graves o irreversibles a las vidas, a los bienes y derechos de las personas, a las instituciones y a los ecosistemas como resultado de la materialización del riesgo en desastre, las autoridades y los particulares aplicarán el principio de precaución en virtud del cual la falta de certeza científica absoluta no será óbice para adoptar medidas encaminadas a prevenir, mitigar la situación de riesgo. (Tomado de UNGRD, 2017)

**Principio de protección**  
Los residentes en Colombia deben ser protegidos por las autoridades en su vida e integridad física y mental, en sus bienes y en sus derechos colectivos a la seguridad, la tranquilidad y la salubridad públicas y a gozar de un ambiente sano, frente a posibles desastres o fenómenos peligrosos que amenacen o infieran daño a los valores enunciados. (Tomado de UNGRD, 2017)

**Principio de solidaridad social**  
Todas las personas naturales y jurídicas, sean estas últimas de derecho público o privado, apoyarán con acciones humanitarias a las situaciones de desastre y peligro para la vida o la salud de las personas. (Tomado de UNGRD, 2017)

**Principio de sostenibilidad ambiental**  
El desarrollo es sostenible cuando satisface las necesidades del presente sin comprometer la capacidad de los sistemas ambientales de satisfacer las necesidades futuras e implica tener en cuenta la dimensión económica, social y ambiental del desarrollo. El riesgo de desastre se deriva de procesos de uso y ocupación insostenible del territorio, por tanto, la explotación racional de los recursos naturales y la protección del medio ambiente constituyen características irreductibles de sostenibilidad ambiental y contribuyen a la gestión del riesgo de desastres. (Tomado de UNGRD, 2017)

**Principio sistémico**  
La política de gestión del riesgo se hará efectiva mediante un sistema administrativo de coordinación de actividades estatales y particulares. El sistema operará en modos de integración sectorial y territorial; garantizará la continuidad de los procesos, la interacción y enlazamiento de las actividades mediante bases de acción comunes y coordinación de competencias. Como sistema abierto, estructurado y organizado, exhibirá las calidades de interconexión, diferenciación, recursividad, control, sinergia y reiteración. (Tomado de UNGRD, 2017)

**Principio de gradualidad**  
La gestión del riesgo se despliega de manera continua, mediante procesos secuenciales en tiempos y alcances que se renuevan permanentemente. Dicha gestión continuada estará regida por los principios de gestión pública consagrados en el artículo 209 de la Constitución y debe entenderse a la luz del desarrollo político, histórico y socioeconómico de la sociedad que se beneficia. (Tomado de UNGRD, 2017)

**Principio del interés público o social**  
En toda situación de riesgo o de desastre, el interés público o social prevalecerá sobre el interés particular. Los intereses locales, regionales, sectoriales y colectivos cederán frente al interés nacional, sin detrimento de los derechos fundamentales del individuo y, sin demérito, de la autonomía de las entidades territoriales. (Tomado de UNGRD, 2017)

**Principio de subsidiariedad**  
Se refiere al reconocimiento de la autonomía de las entidades territoriales para ejercer sus competencias. La subsidiariedad puede ser de dos tipos: la subsidiariedad negativa, cuando la autoridad territorial de rango superior se abstiene de intervenir el riesgo y su materialización en el ámbito de las autoridades de rango inferior, si estas tienen los medios para hacerlo. La subsidiariedad positiva, impone a las autoridades de rango superior, el deber de acudir en ayuda de las autoridades de rango inferior, cuando estas últimas, no tengan los medios para enfrentar el riesgo y su materialización en desastre o cuando esté en riesgo un valor, un interés o un bien jurídico protegido relevante para la autoridad superior que acude en ayuda de la entidad afectada. (Tomado de UNGRD, 2017)

---

## R {#r}

**Recuperación**  
Son las acciones para el restablecimiento de las condiciones normales de vida mediante la rehabilitación, reparación o reconstrucción del área afectada, los bienes y servicios interrumpidos o deteriorados y el restablecimiento e impulso del desarrollo económico y social de la comunidad. La recuperación tiene como propósito central evitar la reproducción de las condiciones de riesgo preexistentes en el área o sector afectado (Ley 1523 de 2012). (Tomado de UNGRD, 2017)

**Reconstrucción**  
Se refiere a la reconstrucción a medio y largo plazo y restauración sostenible de infraestructuras críticas resilientes, servicios, vivienda, instalaciones y medios de subsistencia necesarios para el pleno funcionamiento de una comunidad o una sociedad afectada por un desastre, en concordancia con los principios del desarrollo sostenible y reconstruir mejor para evitar o reducir el riesgo futuro (UNGA, 2016). (Tomado de UNGRD, 2017)

**Rehabilitación**  
Acciones que se realizan inmediatamente después del desastre. Consiste fundamentalmente en la recuperación temporal de los servicios básicos (agua, desagüe, comunicaciones, alimentación y otros) que permitan normalizar las actividades en la zona afectada por el desastre. La rehabilitación es parte de la respuesta ante una emergencia. Restablecimiento de las condiciones mínimas de vida, mediante la recuperación a corto plazo de los servicios básicos y del inicio de la reparación del daño físico, social y económico causado por un desastre (Lavell, 2007). (Tomado de UNGRD, 2017)

**Resiliencia**  
La capacidad de un sistema, comunidad o sociedad expuestos a una amenaza para resistir, absorber, adaptarse y recuperarse de sus efectos de manera oportuna y eficaz, lo que incluye la preservación y la restauración de sus estructuras y funciones básicas (UNISDR, 2009). (Tomado de UNGRD, 2017)

**Respuesta**  
Ejecución de las actividades necesarias para la atención de la emergencia como accesibilidad y transporte, telecomunicaciones, evaluación de daños y análisis de necesidades, salud y saneamiento básico, búsqueda y rescate, extinción de incendios y manejo de materiales peligrosos, albergues y alimentación, servicios públicos, seguridad y convivencia, aspectos financieros y legales, información pública y el manejo general de la respuesta, entre otros. La efectividad de la respuesta depende de la calidad de preparación (Ley 1523 de 2012). (Tomado de UNGRD, 2017)

**Riesgo aceptable**  
Posibles consecuencias sociales y económicas que, implícita o explícitamente, una sociedad o un segmento de la misma asume o tolera en forma consciente por considerar innecesaria, inoportuna o imposible una intervención para su reducción dado el contexto económico, social, político, cultural y técnico existente. La noción es de pertinencia formal y técnica en condiciones donde la información existe y cierta racionalización en el proceso de toma de decisiones puede ejercerse, y sirve para determinar las mínimas exigencias o requisitos de seguridad, con fines de protección y planificación, ante posibles fenómenos peligrosos (Lavel, 2007). (Tomado de UNGRD, 2017)

**Riesgo de desastres**  
Corresponde a los daños o pérdidas potenciales que pueden presentarse debido a los eventos físicos peligrosos de origen natural, socio-natural, tecnológico, biosanitário o humano no intencional, en un período de tiempo específico y que son determinados por la vulnerabilidad de los elementos expuestos; por consiguiente, el riesgo de desastres se deriva de la combinación de la amenaza y la vulnerabilidad (Ley 1523 de 2012). (Tomado de UNGRD, 2017)

**Riesgo extensivo**  
El riesgo generalizado que se relaciona con la exposición de poblaciones dispersas a condiciones reiteradas o persistentes con una intensidad baja o moderada, a menudo de naturaleza altamente localizada, lo cual puede conducir a un impacto acumulativo muy debilitante de los desastres (UNISDR, 2009). (Tomado de UNGRD, 2017)

**Riesgo intensivo**  
El riesgo asociado con la exposición de grandes concentraciones poblacionales y actividades económicas a intensos eventos relativos a las amenazas existentes, los cuales pueden conducir al surgimiento de impactos potencialmente catastróficos de desastres que incluirían una gran cantidad de muertes y la pérdida de bienes (UNISDR, 2009). (Tomado de UNGRD, 2017)

**Riesgo residual**  
El riesgo que todavía no se ha gestionado, aun cuando existan medidas eficaces para la reducción del riesgo de desastres y para los cuales se debe mantener las capacidades de respuesta de emergencia y de recuperación (UNISDR, 2009). (Tomado de UNGRD, 2017)

**Riesgo tecnológico**  
Daños o pérdidas potenciales que pueden presentarse debido a los eventos mayores generados por el uso y acceso a la tecnología, originados en sucesos antrópicos, naturales, socio-naturales y propios de la operación. Se excluyen de su alcance i) los riesgos asociados a la seguridad informática y gestión de información, con excepción de las instalaciones operativas, ii) los establecimientos, las instalaciones o zonas de almacenamientos militares, iii) los riesgos asociados a las radiaciones ionizantes que tienen su origen en sustancias, iv) las armas o agentes de destrucción masiva y v) los riesgo asociados a los agentes biológicos, con excepción de las instalaciones operativas (UNGRD, Resolución 1770 de 2013). (Tomado de UNGRD, 2017)

---

## S {#s}

**Seguridad territorial**  
La seguridad territorial se refiere a la sostenibilidad de las relaciones entre la dinámica de la naturaleza y la dinámica de las comunidades en un territorio en particular. Este concepto incluye las nociones de seguridad alimentaria, seguridad jurídica o institucional, seguridad económica, seguridad ecológica y seguridad social (Ley 1523 de 2012). (Tomado de UNGRD, 2017)

**Servicios de emergencia**  
El conjunto de agencias especializadas con la responsabilidad y los objetivos específicos de proteger a la población y los bienes en situaciones de emergencia (UNISDR, 2009). (Tomado de UNGRD, 2017)

**Simulación**  
Es un juego de roles que se realiza en un ambiente controlado, normalmente es un salón o sala, por lo que son llamados “ejercicios de escritorio”. En una simulación participan los tomadores de decisiones y los actores más representativos del contexto de emergencias en el nivel nacional, departamental y/o municipal. Se basa en situaciones hipotéticas que se derivan del análisis de riesgo del municipio, estrategia de respuesta y protocolos específicos (Tomado de UNGRD, 2016-3). (Tomado de UNGRD, 2017)

**Simulacro**  
Son ejercicios prácticos que representan una situación de emergencia lo más cercano a lo que sería en la realidad, basados siempre en el análisis del riesgo, en consecuencia, una simulación es una forma de poner a prueba la Estrategia Municipal de Respuesta y sus protocolos (UNGRD, 2016). (Tomado de UNGRD, 2017)

**Sistemas de alerta temprana**  
Sistema integrado de vigilancia, previsión y predicción de riesgos, evaluación de riesgos de desastres, comunicación y preparación, sistemas y procesos que permiten a las personas, comunidades, gobiernos, empresas y otros, tomar medidas oportunas para reducir los riesgos de desastres ante la manifestación de un evento amenazante (a partir de UNGA, 2016). (Tomado de UNGRD, 2017)

---

## V {#v}

**Variabilidad del clima**  
La variabilidad del clima se refiere a las variaciones en el estado medio y otros datos estadísticos (como las desviaciones típicas, la ocurrencia de fenómenos extremos, etc.) del clima en todas las escalas temporales y espaciales, más allá de fenómenos meteorológicos determinados. La variabilidad se puede deber a procesos internos naturales dentro del sistema climático (variabilidad interna), o a variaciones en los forzamientos externos antropogénicos (variabilidad externa) (IPCC, 2013). (Tomado de UNGRD, 2017)