---
title: "Reducción del riesgo de desastres"
format: html
editor: visual
---

# Planes municipales de gestión del riesgo

-   Guía metodológica para la formulación y actualización de planes municipales de gestión del riesgo de desastres (PMGRD). UNGRD. 2021. [*Link*](https://repositorio.gestiondelriesgo.gov.co:8443/handle/20.500.11762/32750)

::: {layout-ncol="2"}
{{< video "https://youtu.be/cbLFVsg5ZQM" >}} Planes Municipales de Gestión del Riesgo

{{< video "https://www.youtube.com/embed/iC8vIM__LLE" >}} Instrumentos de planificación en gestión de riesgo de desastres- Caja de herramientas

{{< video "https://www.youtube.com/embed/UnkIdgYkpYA" >}} Guía técnica para la implementación de los Planes de Gestión del Riesgo de Desastres
:::

# Ordenamiento territorial y gestión de riesgos

-   Guía para la Integración de la Gestión del Riesgo de Desastres en los Planes de Desarrollo Territorial 2020 – 2023. UNGRD. [*Link*](http://portal.gestiondelriesgo.gov.co/Paginas/Slide_home/Guia-para-la-Integracion-de-la-GRD-en-los-PDT-2020-2023.aspx).
-   Minambiente. Gestión del Riesgo en el Ordenamiento Territorial. [*Link*](https://www.minambiente.gov.co/cambio-climatico-y-gestion-del-riesgo/gestion-del-riesgo-en-el-ordenamiento-territorial/). [*Link*](https://archivo.minambiente.gov.co/index.php/gestion-del-riesgo-de-desastres/la-incorporacion-de-riesgo-en-el-ordenamiento-territorial).
-   Minvivienda. Gestion del riesto - POT. [*Link*](https://minvivienda.gov.co/viceministerio-de-vivienda-espacio-urbano-y-territorial-plan-ordenamiento-territorial-gestion-del-riesgo-pot)
-   Calderon. 2017. El ordenamiento territorial para la gestión del riesgo de desastres en Colombia. [*Link*](http://www.scielo.org.co/pdf/terri/n36/n36a11.pdf).
-   Reasentamiento. Climate-induced relocation. Science. 2021. Special Issue. [*Link*](https://youtu.be/0duVmu2bRDoReasentamiento. Climate-induced relocation. Science. 2021. Special Issue. Link.).

::: {layout-ncol="2"}
{{< video "https://youtu.be/LW5jfQsTcOY" >}} Ordenamiento territorial y gestión de riesgos

{{< video "https://youtu.be/0duVmu2bRDo" >}} Gestión de riesgo y ordenamiento territorial para geólogos
:::

# Interacción de la GRD con otros instrumentos de planificación

-   Planes Integrales de Gestión del Cambio Climático Territorial (PIGCCT). [*Link*](https://www.minambiente.gov.co/cambio-climatico-y-gestion-del-riesgo/planes-integrales-de-gestion-del-cambio-climatico-territorial/).

-   Planes de Ordenación y Manejo de Cuencas Hidrográficas (POMCA). [*Link*](https://archivo.minambiente.gov.co/index.php/gestion-integral-del-recurso-hidrico/planificacion-de-cuencas-hidrograficas/cuenca-hidrografica/planes-de-ordenacion)*.*

-   

::: {layout-ncol="2"}
{{< video "https://www.youtube.com/embed/NF3Yac2Dzro" >}} Planes integrales de gestión de cambio climático territoriales

{{< video "https://www.youtube.com/embed/85WE1wtvMEU" >}} Lanzamiento de la Guía de Territorios Empoderados para la Acción Climática

{{< video "https://youtu.be/WT5bHnSrhsk" >}} Planes de Ordenación y Manejo de Cuencas Hidrográficas -POMCA
:::

# Protección financiera

Suramericana de seguros (2:37:10). [*Link*](https://youtu.be/6gzPgYW1ETg?t=9430).

Public Investment Profile for Disaster Risk Reduction: A Macro-Economic Study. IDB. 2020. [*Link*](https://publications.iadb.org/en/public-investment-profile-disaster-risk-reduction-macro-economic-study).

::: {layout-ncol="2"}

{{< video "https://www.youtube.com/watch?v=6gzPgYW1ETgu0026amp;t=9430s">}} Charla Suramericana de seguros

{{< video "https://youtu.be/\_guf0LOwPW0">}} Navigating the financial impacts of disasters | Recovery Matters webinar series

{{< video "https://youtu.be/xjlPmSXj24Y">}} Integrated Approach to Disaster Risk Management:Prevent, Residual risk Prepare, Respond, Recover

{{< video "https://www.youtube.com/embed/FVF1L4MlGZU2" >}}

{{< video "https://youtu.be/mwRG4RFOEYY">}} Earthquake loss modelling for (re)insurance

:::

# **Soluciones basadas en la naturaleza ECO-DRR**

-   **UICN**
    -   Eco-DRR: What are IUCN's solutions?. [*Link*](https://www.iucn.org/es/node/24798).
    -   Disaster Risk Reduction. [*Link*](https://www.iucn.org/es/node/19177).
-   **ONU.** Programa para el medio ambiente. Ecosystem-based disaster risk reduction. [*Link*](https://www.unenvironment.org/explore-topics/disasters-conflicts/what-we-do/risk-reduction/ecosystem-based-disaster-risk).
-   **World bank**. Nature-based Solutions: a Cost-effective Approach for Disaster Risk and Water Resource Management. [*Link*](https://www.worldbank.org/en/topic/disasterriskmanagement/brief/nature-based-solutions-cost-effective-approach-for-disaster-risk-and-water-resource-management).
-   Measuring the success of climate change adaptation and mitigation in terrestrial ecosystems. Science 2019. [*Link*](https://science.sciencemag.org/content/366/6471/eaaw9256).
-   UNEP y la UICN lanzan fondo global para la adaptación basada en ecosistemas. [Link](https://www.unenvironment.org/es/noticias-y-reportajes/comunicado-de-prensa/unep-y-la-uicn-lanzan-fondo-global-para-la-adaptacion).
-   The Role of Ecosystems in Disaster Risk Reduction. 2013. [*Link*](https://books.google.com.co/books?id=9mTRjKmN1LwC).
-   Public review of the Words into Action guide: ‘Nature-based solutions for disaster risk reduction’. [*Link*](https://www.preventionweb.net/news/view/74080).
-   Words into Action: Nature-based solutions for disaster risk reduction. [*Link*](https://www.undrr.org/publication/words-action-nature-based-solutions-disaster-risk-reduction).
-   Ecopetrol. SbN. [*Link*](https://www.ecopetrol.com.co/wps/portal/Home/sostecnibilidad/ambiental/biodiversidad/sbn).
-   The Role of Nature-Based Solutions in Supporting Social-Ecological Resilience for Climate Change Adaptation. 2022. [*Link*](https://www.annualreviews.org/doi/10.1146/annurev-environ-012220-010017)
-   Curso "Integración de Soluciones Basadas en la Naturaleza (SBN) en la planificación urbana. 2022. [*Link*](https://www.youtube.com/@solucionesbasadasenlanatur3309/streams)
-   Factsheet: Soluciones basadas en la Naturaleza (SbN) en las NDC de América Latina y el Caribe: clasificación de los compromisos para la acción climática. [*Link*](https://www.euroclima.org/seccion-publicaciones/tipo-de-documentos/folletos-publicaciones/ultimas-publicaciones/soluciones-basadas-en-la-naturaleza-sbn-en-las-ndc-de-america-latina-y-el-caribe-clasificacion-de-los-compromisos-para-la-accion-climatica).
-   Nature-based Solutions: Opportunities and Challenges for Scaling Up. [*Link*](https://www.unep.org/resources/report/nature-based-solutions-opportunities-and-challenges-scaling).
-   Factsheet: Soluciones basadas en la Naturaleza (SbN) en las NDC de América Latina y el Caribe: clasificación de los compromisos para la acción climática. [*Link*](https://www.euroclima.org/seccion-publicaciones/tipo-de-documentos/folletos-publicaciones/ultimas-publicaciones/soluciones-basadas-en-la-naturaleza-sbn-en-las-ndc-de-america-latina-y-el-caribe-clasificacion-de-los-compromisos-para-la-accion-climatica).
-   Nature-based Solutions: Opportunities and Challenges for Scaling Up. [*Link*](https://www.unep.org/resources/report/nature-based-solutions-opportunities-and-challenges-scaling).
-   Words into Action: Nature-based Solutions for Disaster Risk Reduction guide. UNDRR. 2023. [Link](https://www.undrr.org/words-action-nature-based-solutions-disaster-risk-reduction)
-   **Bases de datos**
    -   *Weadapt*. Base de datos. [*Link*](https://www.weadapt.org/).
    -   Nature-based Solutions Initiative. *University of Oxford*. [*Link*](https://www.naturebasedsolutionsinitiative.org/).
    -   TRY plant trait database – enhanced coverage and open access. GCB. 2020. [*Link*](https://onlinelibrary.wiley.com/doi/10.1111/gcb.14904).
    -   Urban Nature Atlas. [*Link*](https://una.city/).

https://www.youtube.com/live/XaeyqSWqs4w?feature=share

La Reducción del riesgo de Desastres basada en Ecosistemas en Colombia

https://youtu.be/Pf_t2h_9Z98

<https://youtu.be/Pf_t2h_9Z98> <https://youtu.be/hhGEprt89ks>

<https://www.youtube.com/watch?v=GGuAbB0jBm4u0026amp;t=3s>

Eco-DRR y SbN para la adaptación. 2023

<https://youtu.be/lCFG2u9xnWc> Words into Action: Nature-based Solutions for Disaster Risk Reduction. 2023