---
title: "Repositorios Fair y data science en gestión del riesgo de desastres"
format: html
editor: visual
---

## **Lista de repositorios en GRD Colombia**

-   **Evaluación del riesgo sísmico a nivel urbano Santiago de Cali**. [*Link*](https://github.com/gem/treq-riesgo-urbano/tree/main/Cali).

## **Lista de repositorios en GRD**

------------------------------------------------------------------------

-   **CLIMAAX CRA Handbook**. [*Link*](https://handbook.climaax.eu/intro.html)*. [Link](https://github.com/CLIMAAX/crabook)*. A regional climate risk assessment is often needed to design or update a climate adaptation and/or risk management plan. Regular updates are needed considering changing climate risk profiles
-   **Global Facility for Disaster Reduction and Recovery (GFDRR)**. [*Link*](https://github.com/GFDRR). GFDRR supports developing countries on disaster risk reduction and climate change adaptation. 
    -   **CCDR-tools**. [*Link*](https://gfdrr.github.io/CCDR-tools/home.html).
-   **Design safe**. [*Link*](https://www.designsafe-ci.org/use-designsafe/tools-applications/). [*Link*](https://www.designsafe-ci.org/)*. [Training videos](https://designsafe-ci.org/learning-center/training/). [Jupiter hub](https://jupyter.designsafe-ci.org/hub/login?next=%2Fhub%2F%3F_gl%3D1%2Ai1u2ai%2A_ga%2AMjczNjA1MTcuMTc2Mjg2NjY0OA..%2A_ga_D96RT1T24K%2AczE3NjM4NTI5NzgkbzgkZzEkdDE3NjM4NTMzOTUkajI1JGwwJGgw)*
    -   Texas Advanced Computing Center. [*Link*](https://tacc.utexas.edu/)
    -   R2D application. [*Link*](https://simcenter.designsafe-ci.org/research-tools/r2dtool/?_gl=1y2emqu_gaODEwMzIzNzQzLjE3Njk1MTk5MDk._ga_D96RT1T24K*czE3NzA2MDE3NTQkbzMkZzEkdDE3NzA2MDE4NDgkajMyJGwwJGgw)
        -   Examples. [*Link*](https://nheri-simcenter.github.io/R2D-Documentation/common/user_manual/examples/desktop/examples.html) *\*\*\**
    -   User Guide. [*Link*](https://www.designsafe-ci.org/user-guide/tools/jupyterhub/#examples-of-jupyter-notebooks-available-via-designsafe)

<iframe width="560" height="315" src="https://www.youtube.com/embed/_aUuCGiZhys?si=ilb6vrDttozIP7xy" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen>

</iframe>

------------------------------------------------------------------------

-   **Climate Informed Risk Index.** [Link](https://github.com/fulton-ring/nri-future-risk)**.** This tool is a replica of the National Risk Index (NRI) Future Risk tool, which was removed from the public by the US Government in February, 2025. It references the following datasets which were downloaded before the tool was taken down.
-   Climate change AI. [*Link*](https://www.climatechange.ai/tutorials?).
-   [Climate-conflict.org](https://climate-conflict.org/ "https://climate-conflict.org"). [*Link*](https://github.com/ccew-unibw/ccvi-data/)
-   Copernicus Climate Change Service (C3S) Data Tutorials. [*Link*](https://ecmwf-projects.github.io/copernicus-training-c3s/intro.html)
-   **GeoAI: Artificial Intelligence for Geospatial Data.** [*Link*](https://github.com/opengeos/geoai)
-   **Global Earthquake Model**. [*Link*](https://github.com/gem)
    -   Perfil Colombia. *Link*
-   **Copernicus Browser.** [Link](https://github.com/eu-cdse/copernicus-browser).
-   **EM-DAT Documentation**. [*Link*](https://doc.emdat.be/docs/)*. [Link](https://github.com/em-dat/). [Python](https://github.com/em-dat/python_tutorials).*
-   **Disaster-Risk-Analysis-Platform**. [Link](https://github.com/invcble/Disaster-Risk-Analysis-Platform). Welcome to our project, "Disaster Risk Analytics Platform," developed with an aim to provide comprehensive disaster risk analysis for investment firms operating within the U.S. markets. Using advanced statistical analysis and deep learning technologies, this platform helps predict potential disasters and their financial impacts on various states, aiding firms in making informed, resilient investment decisions.
-   **Disaster-Risk-Monitoring-Using-Satellite-Imagery**. [Link](https://github.com/Pray-d/Disaster-Risk-Monitoring-Using-Satellite-Imagery). A suggestion of task provided by NIVIDEA in its course Disaster Risk Monitoring Using Satellite Imagery
-   **Disaster Risk Pooling tool**. [*Link*](https://idf-rmsg.github.io/DisasterRiskPooling/index.html)
-   **Disaster Vulnerability Map**. Catholic Charities USA Disaster Vulnerability Map. [*Link*](https://github.com/ccusa/Disaster_Vulnerability_Map)
-   **Demostrador RIESGOS**. [*Link*](https://github.com/riesgos/dlr-riesgos-frontend)
-   **Flood** Probability Prediction using Artificial Neural Network. [*Link*](https://github.com/adeel-iqbal/flood-probability-prediction-ann)
-   **Hazus**. FEMA Natural Hazards Risk Assessment Program. [*Link*](https://github.com/nhrap-hazus)*. [Link](https://github.com/Niyam-Projects/sphere/tree/main)*
-   **TOMRAP – Tool for Multi-hazard Risk Assessment in Python.** [Link](https://github.com/BritishGeologicalSurvey/TOMRAP). The project builds on outputs from the METEOR project (NEE6423R) to generate a tool that can be used in future projects to assess multi-hazard risk. The METEOR model was initially developed in ArcGIS. By streamlining this code in Python we will make multi-hazard risk analysis faster and more widely applicable. 
-   **Seismic Hazard and Risk Analysis calculations.** [Link](https://github.com/bakerjw/seismic-hazard-and-risk). Supporting calculations for the textbook Seismic Hazard and Risk Analysis.
-   **Project Pythia**. [Link](https://projectpythia.org/). An education and training hub for the geoscientific Python community
-   **PO.DAAC Cookbook.** [*Link*](https://podaac.github.io/tutorials/)*. [Español](https://podaac-github-io.translate.goog/tutorials/index.html?_x_tr_sl=en&_x_tr_tl=es&_x_tr_hl=es&_x_tr_pto=tc)*
-   **Probability of Fire** **🔥,** Jupyter Book, ECMWF. [*Link*](https://ecmwf.github.io/AI-Probability-of-Fire/)
-   **NASA Earthdata Cloud Cookbook.** [*Link*](https://nasa-openscapes.github.io/earthdata-cloud-cookbook/)
-   Mapeo de Asentamientos Informales basado en Inteligencia Artificial. Banco Mundial. [*Link*](https://www.iadb.org/es/quienes-somos/topicos/desarrollo-urbano-y-vivienda/maiia).
-   **Github**
    -   #DRR. [*Link*](https://github.com/topics/disaster-risk-management)

{{< video "https://riesgos.de/images/downloads/RIESGOS2.0_Project_Video_Presentation_V1.0_2022.mp4 width = 400">}}

## **Proyectos internacionales**

-   Valorada. [*Link*](https://valorada-project.eu/)
    -   Demostrator 1. [*Link*](https://valorada-project.eu/demonstrator-1-bulgaria/)

## **Entrenamiento en GRD**

-   ESRI Disaster Response Program. [*Link*](https://www.esri.com/en-us/disaster-response/overview)
-   Risk Profiler (Canada). [*Link*](https://www.riskprofiler.ca/learn-more/training-materials/index.html)
-   FEMA, [mapas de inundacion](https://www.fema.gov/es/flood-maps)

{{< video "https://youtu.be/jdK-cleFUkc" width = 350 >}} GeoAI Workshop: Unlocking the Power of GeoAI with Python

## **Data science para desastres**

-   Risk data library. Risk data is for everyone. [*Link*](https://riskdatalibrary.org/)*.*
    -   Development Data Hub. [*Link*](https://riskdatalibrary.org/data/)*.*

    -   Risk Data Fellows. [*Link*](https://riskdatalibrary.org/fellows/)*.*

\<iframe width="560" height="315" src="https://www.youtube.com/embed/J3yfu6A-Clc?si=Cg-tWBqb4nxAlPqv" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen\>\</iframe\>

How data is saving lives in Colombia \| UNDRR