---
title: "Riesgo sísmico"
format: html
editor: visual
---

## Instituciones nacionales

-   UNGRD. [*Link*](https://portal.gestiondelriesgo.gov.co/)
-   Asociación Colombiana de Ingeniería Sísmica - AIS. [*Link*](https://asosismica.org.co/).

## Instituciones internacionales

-   Global Earthquake Model Foundation. [*Link*](https://www.globalquakemodel.org/).
-   

## Programas internacionales

-   OpenQuake - Plataforma. [*Link*](https://platform.openquake.org/).
-   Compilation and data manipulation scripts. [*Link*](https://github.com/OpenDRR/model-factory).
-   Geopoderes Webinar. [*Link*](http://www.geopoderes.com/webinars/).

## Amenaza sísmica

-   Modelo nacional de amenaza sísmica para Colombia. SGC. [*Link*](https://libros.sgc.gov.co/index.php/editorial/catalog/book/38#:~:text=En%20el%20modelo%2C%20la%20sismicidad,procedimiento%20propuesto%20por%20los%20autores.).
-   Modelo nacional de amenaza sísmica para Colombia. Bogotá: Servicio Geológico Colombiano y Fundación Global Earthquake Model. [*Link*](https://libros.sgc.gov.co/index.php/editorial/catalog/book/38). [*Link*](https://amenazasismica.sgc.gov.co/).
-   Modelo de Amenaza Sísmica de Colombia. [*Link*](https://amenazasismica.sgc.gov.co/).
-   What is seismic hazard? What is a seismic hazard map? How are they made? How are they used? Why are there different maps, and which one should I use?. USGS. [*Link*](https://www.usgs.gov/faqs/what-seismic-hazard-what-seismic-hazard-map-how-are-they-made-how-are-they-used-why-are-there).
-   Earthquake Hazard Maps. FEMA. [Link](https://www.fema.gov/es/emergency-managers/risk-management/earthquake/hazard-maps).
-   Iris Earthquake Browser. [*Link*](http://ds.iris.edu/ieb/index.html?).
-   Geohazards Europa. [*Link*](https://geohazards-tep.eu/#!).
-   Mapping Global Earthquakes and Hurricane tracks with R. [*Link*](http://david-lallemant.com/mapping-global-earthquakes-and-hurricane-tracks-with-r-2/).

::: {layout-ncol="2"}
{{< video "https://youtu.be/f40923_wegA" >}} Modelo Nacional de Riesgo Sísmico

{{< video "https://youtu.be/e5X4baH1jMA" >}} Webinar AIS: Presentación de la amenaza sísmica de AIS 300 y plataforma SAGA

{{< video "https://www.youtube.com/live/vhOXSfuLyN8" >}} Modelo Nacional de Riesgo Sísmico de Colombia: Trabajo en equipo y oportunidades de innovación

{{< video "https://youtu.be/_9VEYORBAi4" >}} Plataforma AIS Saga

Amenaza sísmica
:::

## Evaluación del riesgo por amenaza sísmica

-   Why is Probabilistic Seismic Hazard Analysis (PSHA) still used?. 2017. [*Link*](https://www.sciencedirect.com/science/article/pii/S0031920116303016)

## Comunicación del riesgo

## Reducción del riesgo

-   Reglamento Colombiano de Construcción Sismo Resistente NSR. [*Link*](https://www.idrd.gov.co/sitio/idrd/sites/default/files/imagenes/titulo-a-nsr-100.pdf).

::: {layout-ncol="2"}
{{< video "https://youtu.be/QVhEC4VwExM" >}} Cómo construir edificaciones sismo resistentes
:::

## Manejo de desastres

## Lecturas

-   International Geoscience Programme (IGCP). [*Link*](https://en.unesco.org/international-geoscience-programme).

## **Entrenamiento**

## Repositorios

## Videos

::: {layout-ncol="2"}
{{< video "https://youtu.be/VjFRiFt321o" >}} Presentation of the Geohazards theme of UNESCO’s International Geoscience Programme
:::