---
title: "Sistemas de Alerta Temprana"
format: html
editor: visual
---

## 

# **Recursos**

-   Access to early warning systems and disaster risk information and assessments. Naciones Unidas. [*Link*](https://www.un.org/en/observances/disaster-reduction-day).
-   Sistema de Alerta Temprana de Medellín y el Valle de Aburrá. SIATA. [*Link*](https://siata.gov.co/siata_nuevo/).
-   Early Warning Systems. Naciones Unidas. [*Link*](https://www.un-spider.org/risks-and-disasters/early-warning-systems#no-back).
    -   Dashboard. [*Link*](https://earlywarningsforall.org/site/early-warnings-all/early-warnings-all-dashboard)
-   Institutional Partnerships in Multi-Hazard Early Warning Systems. [*Link*](https://public.wmo.int/en/programmes/disaster-risk-reduction-programme).

::: {layout-ncol="2"}
{{< video "https://www.youtube.com/watch?v=dgsoS5oyMPQ" >}} 1er Intercambio de Experiencias sobre Sistemas de Alerta Temprana Comunitaria

{{< video "https://www.youtube.com/watch?v=CG2WHuvXTg0" >}} Early Warning for Early Action \| International Day for Disaster Risk Reduction Virtual Panel

{{< video "https://www.youtube.com/watch?v=bPqp00RYMko" >}} Special Session on International Day for Disaster Risk Reduction: Early Warning and Early Action

{{< video "https://www.youtube.com/watch?v=CYe3UBT11DQ" >}}

{{< video "https://www.youtube.com/watch?v=J-5yDWbpwsE" >}}

{{< video "https://youtu.be/SITGO4yDJYE" >}}

Sistemas de alerta temprana
:::

# Proyectos

## Inform Risk

-   Inform\@Risk Sistema Participativo de Alertas Tempranas en Bello Oriente. [*Facebook, link.*](https://www.facebook.com/watch/?v=658519892678306)

::: {layout-ncol="2"}
{{< video "https://youtu.be/qRxBbCGlJp8" >}} Entrevista con Carolina García Londoño, coordinadora Inform\@risk Urbam, Eafit

{{< video "https://youtu.be/3LZzCVcbu_Y" >}} Ecuador. Fortalecimiento de Capacidades en Gestión de Riesgos con la metodología INFORM Index For Risk
:::