---
title: "Tsunami"
format: html
editor: visual
---

# Instituciones nacionales

-   UNGRD. [*Link*](https://portal.gestiondelriesgo.gov.co/)
-   DIMAR
-   SGC

# Instituciones internacionales

-   

# Programas internacionales

# Amenaza por tsunami

{{< video "https://youtu.be/xgUoaEO13LA?si=y6YqIowjrlHI2AHK" >}} Navigating the Challenge of Sequential Hazards: Evolving Building Design for Earthquakes and Tsunami

-   Tsunami news. UNDRR. [*Link*](https://www.undrr.org/publication/tsunami-news-2020-2021).
-   Visor de alerta por tsunami. DIMAR. [*Link*](https://experience.arcgis.com/experience/8a874d3eb0c34fddac24dab577d5b95c/page/App/).
-   Forecasting Tsunami Damage in Real Time. [*Link*](https://gov-online.go.jp/eng/publicity/book/hlj/html/202203/202203_10_en.html).

# Evaluación del riesgo por por tsunami

-   Libros:
    -   Probabilistic Tsunami Hazard and Risk Analysis. Towards Disaster Risk Reduction and Resilience. 2024. [*Link*](https://www.sciencedirect.com/book/9780443189876/probabilistic-tsunami-hazard-and-risk-analysis). [*Google*](https://books.google.com.co/books?id=-cIAEQAAQBAJ&printsec=frontcover&dq=Probabilistic+Tsunami+Hazard+and+Risk+Analysis&hl=es-419&newbks=1&newbks_redir=0&sa=X&redir_esc=y#v=onepage&q&f=false)
    -   Probabilistic Tsunami Hazard and Risk Analysis: Towards Disaster Risk. [*Link*](https://books.google.com.co/books?id=BqVYEAAAQBAJ&printsec=frontcover&dq=Probabilistic+Tsunami+Hazard+and+Risk+Analysis&hl=es-419&newbks=1&newbks_redir=0&sa=X&redir_esc=y#v=onepage&q=Probabilistic%20Tsunami%20Hazard%20and%20Risk%20Analysis&f=false).

# Comunicación del riesgo

# Reducción del riesgo

# Manejo de desastres

# Lecturas

Tsunami paso a paso: los escandalosos errores y omisiones del SHOA y la ONEMI. [*Link*](https://ciperchile.cl/2012/01/18/tsunami-paso-a-paso-los-escandalosos-errores-y-omisiones-del-shoa-y-la-onemi/).

## Videos

{{\<video "https://www.youtube.com/watch?v=w2BIPxPaolQ" \>}}

{{\<video "https://www.youtube.com/watch?v=DdGO9Tqp98Q" \>}}