---
title: "Riesgo volcánico"
format: html
editor: visual
---

## Instituciones nacionales

-   **Servicio Geológico Colombiano**

    -   Atlas Geológico de Colombia 2023: Volcanes 2023. [*Link.*](https://datos.sgc.gov.co/datasets/de7da66446854f559e421ea175e53733_0/explore?location=3.253900%2C-75.532621%2C6.96)
    -   Observatorio Vulcanológico y Sismológico de Manizales. [*Link*](https://www2.sgc.gov.co/ProgramasDeInvestigacion/geoamenazas/Paginas/OVS-Manizales.aspx)
    -   Geoportal - Geoamenazas. [*Link.*](https://www2.sgc.gov.co/sgc/mapas/Paginas/geoportal.aspx#)
    -   Estados de alerta por actividad volcánica. [*Link*](https://www2.sgc.gov.co/volcanes2017/index.html)
    -   Portal Datos Abiertos. Atlas Geológico de Colombia 2023: Volcanes 2023. [*Link*](https://datos.sgc.gov.co/datasets/de7da66446854f559e421ea175e53733_0/explore?location=4.441166%2C-75.250585%2C6.99)

## Instituciones internacionales

-   USGS. Volcano Hazards Program. [*Link*](https://www.usgs.gov/programs/VHP)
-   Asociación Latinoamericana de Volcanología (ALVO). [*Link*](https://oficialalvo.org/)
-   International Association of Volcanology and Chemistry of the Earth's Interior. [*Link*](https://www.iavceivolcano.org/)
-   Visor de emisiones de gases. NOAA. [*Link*](https://satepsanone.nesdis.noaa.gov/pub/OMI/OMISO2/ecuador.html#End).

## [Volcanes de Colombia](https://www.sgc.gov.co/volcanes) (SGC)

-   Campo volcánico Guamuéz - Sibundoy
-   Volcán Azufral
-   Volcán Cerro Bravo
-   Volcán Cerro Machín
-   Volcán Cerro Negro
-   Volcán Chiles
-   Volcán Cumbal
-   Volcán Doña Juana
-   Volcán Galeras
-   Volcán las Ánimas
-   Volcán Nevado de Santa Isabel
-   Volcán Nevado del Huila
-   Volcán Nevado del Ruiz

## Mapa de volcanes

## Amenaza volcánica

-   Mapas de amenaza volcánica. [*Link*](https://srvags.sgc.gov.co/JSViewer/Amenaza_volcanica_JS/?itemid=d749a30e99eb46d69b20f908db9ccda9&page=Azufral&views=View-2%2CMachin "Mapas Amenaza Volcanica")
-   Global volcanic hazards and risk: Summary background paper. 2015. UNDRR. [*Link*](https://www.undrr.org/publication/global-volcanic-hazards-and-risk-summary-background-paper#downloads).
-   Global volcanic hazards and risk: Technical background paper. 2015. UNDRR. [*Link*](https://www.undrr.org/publication/global-volcanic-hazards-and-risk-technical-background-paper).
-   Volcano hazards assessments support decision making. USGS. [*Link*](https://www.usgs.gov/programs/VHP/volcano-hazards-assessments-support-decision-making)
-   Volcano Hazard Assessments are based on the geologic record. USGS. [*Link*](https://www.usgs.gov/programs/VHP/volcano-hazard-assessments-are-based-geologic-record)

::: {layout-ncol="2"}
{{< video "https://youtu.be/29DoJPNTeao" >}}

{{< video "https://youtu.be/0A_pxOHNQHw?si=MkNattLFYnqh5Eu-" >}}

Amenaza volcánica
:::

::: {layout-ncol="2"}
{{< video "https://youtu.be/xkZrZqMqHa8" >}}

{{< video "https://youtu.be/N1jnPKIoWCY" >}}

Amenaza volcánica: volcanes Nevado del Ruiz y Galeras
:::

## Evaluación del riesgo volcánico

-   Riesgo volcánico probabilístico con ejemplo de aplicación. 2024 Editorial Universidad de Nariño. [*Link*](https://editorial.udenar.edu.co).
-   Implicaciones del Enfoque Metodológico de Evaluación de la Amenaza y el Riesgo de Desastres por Erupciones del Volcán Galeras, Colombia. 2024. REDER. [*Link*](https://www.revistareder.com/ojs/index.php/reder/article/view/137)
-   Volcanic risk assessment: Quantifying physical vulnerability in the built environment. Journal of Volcanology and Geothermal Research. [*Link*](https://doi.org/10.1016/j.jvolgeores.2014.03.002).
-   Open Quake Foundation. Ecenarios de riesgo volcanito. Taller de entrenamiento. [*Link*](https://www.training.openquake.org/volcanic-scenarios?lang=es). Atributos geográficos, atributos estructurales, modelo de exposición. Fragilidad y vulnerabilidad. Calculadora de escenacios de daños, escenarios de evaluación del riesgo.

::: {layout-ncol="2"}
{{< video "https://youtu.be/leF4aQXGdjk" >}}

{{< video "https://youtu.be/iB1uiaxScek" >}}

Evaluación del riesgo volcánico.
:::

## Comunicación del riesgo volcánico

-   Esquema estados de alerta por actividad volcánica en Colombia. [*Link*](https://www2.sgc.gov.co/Paginas/estados-de-alerta-volcanes.aspx). Alerta verde, alerta amarilla, alerta naranja, alerta roja.
-   Guía para comunicar sobre volcanes en Colombia. [*Link*](https://www2.sgc.gov.co/Noticias/Paginas/Consulta-aqui-la-guia-para-comunicar-sobre-volcanes-en-Colombia.aspx)
-   Volcán, riesgo y territorio. [*Link*](http://www.volcanriesgoyterritorio.gov.co/)
-   Estrategias del Servicio Geológico Colombiano en la búsqueda de la apropiación social del conocimiento geocientífico y la gestión del riesgo volcánico del Nevado del Ruiz. 2023. REDER. [*Link*](https://doi.org/10.55467/reder.v7i2.122)
-   Communication About Volcanic Hazards. USGS. [*Link*](https://www.usgs.gov/observatories/cvo/communication-about-volcanic-hazards)
-   Volcano disaster risk management during crisis: implementation of risk communication in Indonesia. 2023. Journal of Applied Volcanology. [*Link*](https://appliedvolc.biomedcentral.com/articles/10.1186/s13617-023-00129-2)

::: {layout-ncol="2"}
{{< video "https://www.youtube.com/embed/3scW4pa8l-c" >}}

{{< video "https://youtu.be/H2Dn_b1Ad3k" >}}
:::

::: {layout-ncol="2"}
{{< video "https://youtu.be/-Rve9yreZ3g" >}}

{{< video "https://youtu.be/48F5h4D1hQ8" >}}

Comunicación del riesgo volcánico
:::

## Reducción del riesgo volcánico

-   Ordenamiento territorial.
    -   Sentencia T-269/15. Corte Constitucional. Volcán Galeras. [*Link*](https://www.corteconstitucional.gov.co/relatoria/2015/T-269-15.htm).

## Manejo de desastres

-   Plan Nacional de Respuesta del Volcán Nevado del Ruiz, 2021. [*Link*](https://reliefweb.int/report/colombia/plan-nacional-de-respuesta-del-volcan-nevado-del-ruiz-2021)
-   Plan Nacional de Preparación y Respuesta por Actividad del Volcán Puracé. 2025. [*Link*](https://portal.gestiondelriesgo.gov.co/Documents/Planes-respuesta/PLAN-NACIONAL-DE-PREPARACION-Y-RESPUESTA-VOLCAN-PURACE.pdf)

## Lecturas

-   The Encyclopedia of Volcanoes. Elsevier. 2015. [*Link*](https://www.sciencedirect.com/book/9780123859389/the-encyclopedia-of-volcanoes).
-   Assessing Volcanic Hazard: A Review. Oxford Handbooks. 2017. [Link](https://link.springer.com/chapter/10.1007/11157_2016_46).
-   Observing the Volcano World. Springer 2018. [*Link*](https://link.springer.com/book/10.1007/978-3-319-44097-2).
-   If I Understand, I Am Understood: Experiences of Volcanic Risk Communication in Colombia. [Link](https://link.springer.com/book/10.1007/978-3-319-44097-2).
-   Chronology of the principal scientific and governmental actions leading up to the November 13, 1985 eruption of Nevado del Ruiz, Colombia. Journal of Volcanology and Geothermal Research. 1990. [Link](https://www.oxfordhandbooks.com/view/10.1093/oxfordhb/9780190699420.001.0001/oxfordhb-9780190699420-e-32).
-   Risk perception and volcanic hazard mitigation: Individual and social perspectives. Journal of Volcanology and Geothermal Research. 2008. [Link](https://doi.org/10.1016/j.jvolgeores.2007.12.026).
-   “There’s no Plastic in Our Volcano”: A Story About Losing and Finding a Path to Participatory Volcanic Risk Management in Colombia. 2017. [Link](https://link.springer.com/chapter/10.1007/11157_2017_16).
-   Worlding resilience in the Doña Juana Volcano-Páramo, Northern Andes (Colombia): A transdisciplinary view. 2021. Natural Hazards. [Link](https://link.springer.com/article/10.1007/s11069-021-04662-4).
-   Volcanic evolution through geomorphological mapping: A case study of Cerro Bravo volcano (Colombia). 2023, Journal of South American Earth Sciences. [Link](https://doi.org/10.1016/j.jsames.2023.104472)

## Videos

::: {layout-ncol="2"}
{{< video "https://youtu.be/No7RnYitOTQ" >}}
:::